gazebosim/gz-rendering

CONTRIBUTING.md
Changelog.md
README.md
bitbucket-pipelines.yml

Signed-off-by: Louise Poubel <louise@openrobotics.org>

[ign-rendering2] Update BitBucket links

---

CMakeLists.txt
Changelog.md

PRs merged since 2.3.0:
https://bitbucket.org/ignitionrobotics/ign-rendering/branches/compare/ign-rendering2%0Dignition-rendering2_2.3.0#pull-requests

Bump version to 2.4.0

---

CONTRIBUTING.md
README.md
bitbucket-pipelines.yml

Signed-off-by: Louise Poubel <louise@openrobotics.org>

[ign-rendering0] Update BitBucket links

---

CONTRIBUTING.md
Changelog.md
README.md
bitbucket-pipelines.yml

Signed-off-by: Louise Poubel <louise@openrobotics.org>

[master] Update BitBucket links

---

CONTRIBUTING.md
Changelog.md
README.md
bitbucket-pipelines.yml

Signed-off-by: Louise Poubel <louise@openrobotics.org>

[ign-rendering3] Update BitBucket links

---

.github/CODEOWNERS
.github/workflows/ci-bionic.yml
.github/workflows/pr-collection-labeler.yml
.github/workflows/triage.yml
README.md

* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update codecov badge
* Port `CODEOWNERS`

[ign-rendering0] Workflow updates

---

.github/CODEOWNERS
.github/workflows/ci-bionic.yml
.github/workflows/pr-collection-labeler.yml
.github/workflows/triage.yml
README.md

* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update codecov badge
* Port `CODEOWNERS`

[ign-rendering2] Workflow updates

---

.github/workflows/ci-bionic.yml
.github/workflows/pr-collection-labeler.yml
.github/workflows/triage.yml
README.md

* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update codecov badge
---
~BitBucket pipelines was building `ign-common` from source but the action doesn't support that yet. If this PR fails, this PR will wait for https://github.com/ignition-tooling/ubuntu-bionic-ci-action/issues/5 to be addressed.~

[master] Workflow updates

---

BUILD.bazel
examples/ogre2_demo/Main.cc
examples/simple_demo/Main.cc
ogre2/BUILD.bazel
ogre2/src/Ogre2RenderEngine.cc
src/RenderEngineManager.cc
test/BUILD.bazel

Signed-off-by: Michael Carroll <michael@openrobotics.org>

Fix ignition rendering tests

---

BUILD.bazel
examples/ogre2_demo/Main.cc
examples/simple_demo/Main.cc
ogre2/BUILD.bazel
ogre2/src/Ogre2RenderEngine.cc
src/RenderEngineManager.cc
test/BUILD.bazel

~We'll need to set some of the resource paths (which might be why most of the tests are failing).~
All tests passing except for `RenderingIface_TEST` due to a local define issue I explained [here](https://github.com/ignitionrobotics/ign-rendering/pull/106) 
Signed-off-by: John Shepherd <john@openrobotics.org>

[Bazel] Init Bazel attempt

---

ogre2/BUILD.bazel

Signed-off-by: John Shepherd <john@openrobotics.org>

[Bazel] Remove slash

---

ogre2/src/Ogre2LidarVisual.cc

@chapulina I believe this should fix the failing test in #120

FIX failing lidar visual integration test

---

CMakeLists.txt
Changelog.md

Bump to 2.5.0
Signed-off-by: Nate Koenig <nate@openrobotics.org>

2.5.0 release prep

---

tutorials/02_install.md

* removed text that says the packages are unstable
* removed pre-release repo from setup

Update installation tutorial

---

examples/hello_world_plugin/HelloWorldPlugin.cc
examples/hello_world_plugin/README.md
src/base/BaseRenderEngine.cc

The null checks I added are in BaseRenderEngine.cc

Add null checks when loading example render engine

---

CMakeLists.txt
Changelog.md

Prepare for 2.5.1 release

---

CMakeLists.txt
examples/actor_animation/CMakeLists.txt
examples/camera_tracking/CMakeLists.txt
examples/custom_scene_viewer/CMakeLists.txt
examples/custom_shaders/CMakeLists.txt
examples/gazebo_scene_viewer/CMakeLists.txt
examples/lidar_visual/CMakeLists.txt
examples/mesh_viewer/CMakeLists.txt
examples/mouse_picking/CMakeLists.txt
examples/ogre2_demo/CMakeLists.txt
examples/particles_demo/CMakeLists.txt
examples/render_pass/CMakeLists.txt
examples/simple_demo/CMakeLists.txt
examples/text_geom/CMakeLists.txt
examples/thermal_camera/CMakeLists.txt
examples/transform_control/CMakeLists.txt
examples/view_control/CMakeLists.txt
tutorials/17_render_pass_tutorial.md
tutorials/18_simple_demo_tutorial.md
tutorials/19_text_geom_tutorial.md
tutorials/20_particles_tutorial.md

The `ign-rendering4` branch was created off `main` for the Dome release.
Now bumping `main` to version 5 so it may receive breaking changes.

⬆️  Bump main to 5.0.0~pre1

---

src/Utils.cc

I clicked too much in gazebo, and the gui crashed :(
This function is called a bunch when Transform Control is used. Because the display was not cleaned up, eventually `XOpenDisplay` will throw an exception about too many connections. 
Signed-off-by: Stephen Brawner <brawner@gmail.com>

Call XCloseDisplay in screenScalingFactor

---

CMakeLists.txt
Changelog.md

https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering4_4.1.0...ign-rendering4
Signed-off-by: Nate Koenig <nate@openrobotics.org>

4.2.0 prep

---

.github/ci/after_make.sh
ogre2/src/Ogre2RenderEngine.cc
test/integration/camera.cc

Port `ign-rendering3` to `ign-rendering4`
Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering4...ign-rendering3
---
https://github.com/osrf/buildfarmer/issues/161

👩‍🌾 3 ➡️ 4

---

ogre2/src/media/materials/programs/depth_camera_final_fs.glsl
ogre2/src/media/materials/scripts/depth_camera.material
test/integration/depth_camera.cc

Testing fix from #333. This PR re-enables the depth camera integration test to see if it'll pass on our homebrew CI machine.

Test re-enabling depth camera integration test on mac

---

ogre2/src/Ogre2SelectionBuffer.cc
src/Image.cc

Backport pull request #337 and #338 

Backport memory fixes found by ASAN

---

CMakeLists.txt
Changelog.md
test/integration/camera.cc
test/integration/scene.cc

Port ign-rendering3 to ign-rendering4
Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering4...ign-rendering3

Merge 3 -> 4

---

README.md

Tweak to README about optix. Marked it as experimental since it's not very well maintained.

Add note about optix in README

---

CMakeLists.txt
Changelog.md

Preparation for 6.0.1 release.
Comparison to 6.0.0: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering6_6.0.0...prep_6.0.1

Prepare for 6.0.1 patch release

---

.github/ci/packages.apt
CMakeLists.txt
src/CMakeLists.txt

Part of #491.
Depend on ignition-utils1 so we can use `ImplPtr` (see https://github.com/ignitionrobotics/ign-rendering/pull/490#discussion_r751910398 )

Use ignition-utils1

---

CMakeLists.txt
Changelog.md
examples/custom_shaders_uniforms/GlutWindow.cc
examples/custom_shaders_uniforms/Main.cc
examples/custom_shaders_uniforms/media/fragment_shader_330.glsl
examples/custom_shaders_uniforms/media/vertex_shader_330.glsl
examples/render_pass/Main.cc
include/ignition/rendering/DistortionPass.hh
include/ignition/rendering/RenderTypes.hh
include/ignition/rendering/base/BaseDistortionPass.hh
ogre/include/ignition/rendering/ogre/OgreDistortionPass.hh
ogre/src/OgreDistortionPass.cc
ogre/src/media/materials/programs/camera_distortion_map_fs.glsl
ogre/src/media/materials/programs/camera_distortion_map_vs.glsl
ogre/src/media/materials/scripts/distortion.compositor
ogre/src/media/materials/scripts/distortion.material
ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
ogre2/src/Ogre2DepthCamera.cc
ogre2/src/Ogre2GpuRays.cc
ogre2/src/Ogre2Material.cc
ogre2/src/Ogre2Mesh.cc
ogre2/src/Ogre2RenderTarget.cc
ogre2/src/Ogre2SelectionBuffer.cc
ogre2/src/Ogre2ThermalCamera.cc
ogre2/src/media/materials/programs/GLSL/depth_camera_fs.glsl
ogre2/src/media/materials/programs/Metal/depth_camera_fs.metal
src/DistortionPass.cc
src/ShaderParam.cc
test/integration/gpu_rays.cc
test/integration/render_pass.cc

Port ign-renderng6 to main
Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/main...ign-rendering6

Merge 6 -> main

---

Migration.md

Update Migration update with info on deprecated function, see https://github.com/ignitionrobotics/ign-rendering/pull/534/files#r781598375

Update Migration guide

---

CMakeLists.txt
Changelog.md

Preparation for 6.2.0~pre1 prerelease.
Comparison to 6.1.0: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering6_6.1.0...ign-rendering6
Needed by https://github.com/ignitionrobotics/ign-sensors/pull/192

Prepare for 6.2.0~pre1 prerelease

---

CMakeLists.txt
Changelog.md

Preparation for 6.2.0 release.
Comparison to 6.1.0: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering6_6.1.0...prep_6.2.0
Needed by
* https://github.com/ignitionrobotics/ign-sensors/pull/192
* https://github.com/ignitionrobotics/ign-gazebo/pull/1275
* https://github.com/ignitionrobotics/ign-gazebo/pull/1310

Prepare for 6.2.0 release

---

include/ignition/rendering/BoundingBox.hh
include/ignition/rendering/HeightmapDescriptor.hh
include/ignition/rendering/Image.hh
include/ignition/rendering/MeshDescriptor.hh
include/ignition/rendering/MoveToHelper.hh
include/ignition/rendering/OrbitViewController.hh
include/ignition/rendering/OrthoViewController.hh
include/ignition/rendering/RayQuery.hh
include/ignition/rendering/RenderEngineManager.hh
include/ignition/rendering/RenderEnginePlugin.hh
include/ignition/rendering/RenderPassSystem.hh
include/ignition/rendering/ShaderParam.hh
include/ignition/rendering/TransformController.hh
include/ignition/rendering/base/BaseCamera.hh
include/ignition/rendering/base/BaseGizmoVisual.hh
include/ignition/rendering/base/BaseMarker.hh
include/ignition/rendering/base/BaseObject.hh
include/ignition/rendering/base/BaseRenderEngine.hh
include/ignition/rendering/base/BaseScene.hh
include/ignition/rendering/base/BaseStorage.hh
ogre/include/ignition/rendering/ogre/OgreDistortionPass.hh
ogre/include/ignition/rendering/ogre/OgreGaussianNoisePass.hh
ogre/include/ignition/rendering/ogre/OgreGeometry.hh
ogre/include/ignition/rendering/ogre/OgreGpuRays.hh
ogre/include/ignition/rendering/ogre/OgreMaterial.hh
ogre/include/ignition/rendering/ogre/OgreMaterialSwitcher.hh
ogre/include/ignition/rendering/ogre/OgreNode.hh
ogre/include/ignition/rendering/ogre/OgreObject.hh
ogre/src/OgreDistortionPass.cc

Signed-off-by: Michael Carroll [michael@openrobotics.org](mailto:michael@openrobotics.org)[](https://github.com/mjcarroll)

Change to use SuppressWarning from ign-utils

---

CMakeLists.txt
Changelog.md

Preparation for 6.2.1 release.
Comparison to <x.y.z>: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering6_6.2.0...prep_6.2.1

Prepare for 6.2.1 release

---

CMakeLists.txt
Changelog.md

Preparation for 6.3.0 release.
Comparison to 6.2.1: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering6_6.2.1...prep_6.3.0
Needed by
https://github.com/ignitionrobotics/ign-gazebo/pull/1415

Prepare for 6.3.0 release

---

Changelog.md
Migration.md
examples/heightmap/Main.cc
ogre/src/OgreHeightmap.cc
ogre2/src/Ogre2Heightmap.cc

Port `ign-rendering6` to `main`
Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/main...ign-rendering6

6 ➡️ 7 (main)

---

examples/hello_world_plugin/CMakeLists.txt

Fixes version numbers in anticipation of the next round of version bumps.
Use `*_VERSION_MAJOR` variables to aid search/replace scripts.

hello_world_plugin: fix find version variables

---

CMakeLists.txt
Changelog.md

Preparation for 6.3.1 release.
Comparison to  6.3.0: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering6_6.3.0...ign-rendering6?expand=1
Needed to get jammy packages out.

Prepare 6.3.1

---

.github/ci/packages.apt
CMakeLists.txt
examples/simple_demo_qml/CMakeLists.txt
tutorials/02_install.md

See https://github.com/ignition-tooling/release-tools/issues/685

Bumps in garden : ign-rendering7

---

.github/CODEOWNERS

Port `ign-rendering3 ` ➡️  `ign-rendering6`
Branch comparision: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering6...ign-rendering3

Merge ign-rendering3 ➡️  ign-rendering6

---

ogre/src/OgreMaterial.cc
ogre2/src/Ogre2Material.cc
src/Heightmap_TEST.cc
src/ShaderParams_TEST.cc

Signed-off-by: Michael Carroll <michael@openrobotics.org>

Suppress new Jammy warnings

---

.github/CODEOWNERS

Removed @WilliamLewww from Codeowners.

Removed WilliamLewww from Codeowners

---

include/ignition/rendering/BoundingBox.hh

Fixes #649 
Fix adds missing include for `<utility>` which contains `std::exchange` functionality.

add missing utility include for std::exchange

---

CMakeLists.txt
include/gz/rendering/CMakeLists.txt
include/gz/rendering/base/CMakeLists.txt
ogre/include/gz/rendering/CMakeLists.txt
ogre/src/CMakeLists.txt
ogre2/include/gz/rendering/CMakeLists.txt
ogre2/src/CMakeLists.txt
optix/include/gz/rendering/CMakeLists.txt
optix/src/CMakeLists.txt
src/CMakeLists.txt
test/integration/CMakeLists.txt
test/performance/CMakeLists.txt
test/regression/CMakeLists.txt

* Part of https://github.com/gazebo-tooling/release-tools/issues/719

[ign -> gz] CMake functions

---

ogre2/src/Ogre2SelectionBuffer.cc
src/RayQuery_TEST.cc

Ensure one texture per selection buffer per camera.

---

CMakeLists.txt
api.md.in
test/integration/all_symbols_have_version.bash.in
tutorials.md.in

Signed-off-by: Nate Koenig <nate@openrobotics.org>
I ran `find . -name "*" -exec -i 's/IGN_DESIGNATION/GZ_DESIGNATION/g' {} \;` in order to make this repository compliant with https://github.com/gazebosim/gz-cmake/pull/282

Change IGN_DESIGNATION to GZ_DESIGNATION

---

CMakeLists.txt
api.md.in
test/integration/all_symbols_have_version.bash.in
tutorials.md.in

This merges forward GZ_DESIGNATION updates from v1 to v2.

1 2 GZ_DESIGNATION

---

api.md.in
test/integration/all_symbols_have_version.bash.in
tutorials.md.in

Port `ign-rendering2 ` ➡️  `ign-rendering3`
Branch comparision: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering3...ign-rendering2

Merge ign-rendering2 ➡️  ign-rendering3

---

tutorials/14_camera_tracking_tutorial.md

updated links to point to gz-rendering7 APIs

Update Camera tracking tutorial links

---

Changelog.md

Preparation for 7.1.0 release.
Comparison to 7.0.0: https://github.com/gazebosim/gz-rendering/compare/gz-rendering7_7.0.0...gz-rendering7

Prepare for 7.1.0 Release

---

examples/boundingbox_camera/GlutWindow.cc
examples/boundingbox_camera/Main.cc
ogre2/src/Ogre2RayQuery.cc
src/OrbitViewController.cc
test/common_test/Mesh_TEST.cc

these got introduced likely from forward ports.

More ign to gz changes

---

src/CameraLens.cc

Follow up to #853 to fix Windows.

Fix missing header

---

ogre/src/OgreLightVisual.cc

Related with this issue https://github.com/gazebosim/gz-sim/issues/1948 and backport #862

[backport fortress] Fixed light visual in OGRE (#862)

---

include/gz/rendering/Capsule.hh
include/gz/rendering/GraphicsAPI.hh
ogre/src/OgreNode.cc
ogre/src/OgreProjector.cc
ogre/src/OgreRenderEngine.cc
ogre2/src/Ogre2GzHlmsSharedPrivate.cc
ogre2/src/Ogre2Node.cc
ogre2/src/terrain/Terra/src/Terra.cpp

Port `gz-rendering7 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/main...gz-rendering7

Merge gz-rendering7 ➡️  main

---

include/gz/rendering/Camera.hh
include/gz/rendering/LidarVisual.hh
include/gz/rendering/RenderEngine.hh

Fix doxygen warnings in Harmonic

---

.github/ci/packages-bionic.apt
.github/ci/packages-focal.apt

Harmonic is not supported on bionic and focal

Remove bionic and focal apt packages for harmonic

---

tutorials/24_boundingbox_camera_tutorial.md

Fix typo in bounding box camera tutorial

---

CMakeLists.txt

Preparation for 8.0.0-pre2 release.
Comparison to 8.0.0-pre1: https://github.com/gazebosim/gz-rendering/compare/gz-rendering8_8.0.0-pre1...prep_8.0.0pre2

Prepare for 8.0.0 pre2 prerelease

---

tutorials/02_install.md

https://github.com/gazebosim/gazebo_test_cases/issues/155
* Replaced `ign` with `gz`
* Updated windows instructions
* Updated ogre-next lib name

Update installation instructions

---

examples/actor_animation/Main.cc
examples/boundingbox_camera/Main.cc
examples/camera_tracking/Main.cc
examples/custom_scene_viewer/ManualSceneDemo.cc
examples/custom_shaders_uniforms/Main.cc
examples/depth_camera/Main.cc
examples/heightmap/Main.cc
examples/lidar_visual/Main.cc
examples/mesh_viewer/Main.cc
examples/mouse_picking/Main.cc
examples/ogre2_demo/Main.cc
examples/particles_demo/Main.cc
examples/projector/Main.cc
examples/render_pass/Main.cc
examples/segmentation_camera/Main.cc
examples/simple_demo/Main.cc
examples/simple_demo_qml/ThreadRenderer.cpp
examples/thermal_camera/Main.cc
examples/transform_control/Main.cc
examples/view_control/Main.cc
examples/visualization_demo/Main.cc
examples/waves/Main.cc
examples/wide_angle_camera/Main.cc
include/gz/rendering/Utils.hh
ogre2/src/terrain/Terra/CMakeLists.txt
src/Utils.cc

Port gz-rendering7 to gz-rendering8
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/gz-rendering8...gz-rendering7

Merge 7 -> 8

---

Changelog.md

Update 6.6.3 changelog

---

.github/workflows/ci.yml

Updates GitHub CI workflow missed from the last forward port.

Update github ci workflow

---

ogre2/src/Ogre2GpuRays.cc

backport #973
The Ogre2GpuRays implementation has quite a bit of changes between `ign-rendering6` and `gz-rendering8` so the commit could not be applied directly. So I created a new commit to backport the changes

Backport lidar particle detection optimization

---

include/gz/rendering/GraphicsAPI.hh
src/ArrowVisual_TEST.cc
src/AxisVisual_TEST.cc
src/Camera_TEST.cc
src/Grid_TEST.cc
src/Light_TEST.cc
src/Marker_TEST.cc
src/Material_TEST.cc
src/Mesh_TEST.cc
src/MoveToHelper_TEST.cc
src/Node_TEST.cc
src/OrbitViewController_TEST.cc
src/RayQuery_TEST.cc
src/RenderTarget_TEST.cc
src/RenderingIface_TEST.cc
src/Scene_TEST.cc
src/ThermalCamera_TEST.cc
src/TransformController_TEST.cc
src/Visual_TEST.cc
test/integration/CMakeLists.txt

Port ign-renderin3 to ign-rendering6
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/ign-rendering6...ign-rendering3

3 :arrow_right: 6

---

ogre2/src/Ogre2RenderEngine.cc

Updated to point to the Ionic troubleshooting page

Update troubleshooting link

---

README.md

Part of https://github.com/gazebo-tooling/release-tools/issues/1092

Update badges to point to gz-rendering9

---

CMakeLists.txt

Preparation for 9.0.0~pre2 release.
Comparison to 9.0.0~pre1: https://github.com/gazebosim/gz-rendering/compare/gz-rendering9_9.0.0-pre1...prep_9.0.0pre2

Prepare for gz-rendeirng9.0.0~pre2 release

---

tutorials/23_depth_camera_tutorial.md

Fix prerequisites for 23_depth_camera_tutorial.md
Preparation for <X.Y.Z> release.
Comparison to <x.y.z>: https://github.com/gazebosim/<REPO>/compare/<LATEST_TAG_BRANCH>...<RELEASE_BRANCH>

fix prerequisites

---

tutorials/18_simple_demo_tutorial.md

Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1473
Add Windows instructions to the tutorial.
I've tested it to work with these instructions.

18_simple_demo_tutorial: Add Windows instructions

---

CMakeLists.txt
Changelog.md
README.md

Port gz-rendering9 to main
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/main...gz-rendering9

Merge 9 -> main

---

.codespell-ignore
Changelog.md
Migration.md
tutorials/13_custom_scene_viewer.md

This pull request corrects minor spelling errors in the documentation (.md and .md.in files).
Before making the corrections, I analyzed the project and found some words that could cause problems when trying to find actual spelling errors, so I created an ignore file.

Fix spelling errors in documentation

---

CMakeLists.txt
Changelog.md

Preparation for 10.0.0 release.
Comparison to 10.0.0-pre2: https://github.com/gazebosim/gz-rendering/compare/gz-rendering10_10.0.0-pre2...gz-rendering10

Prepare for 10.0.0 release

---

.github/ci/packages.apt
CMakeLists.txt
Changelog.md
include/gz/rendering/base/BaseMesh.hh
test/common_test/Mesh_TEST.cc
tutorials/02_install.md
tutorials/10_actor_animation_tutorial.md
tutorials/12_mesh_viewer_tutorial.md
tutorials/13_custom_scene_viewer.md
tutorials/14_camera_tracking_tutorial.md
tutorials/15_custom_shaders_tutorial.md
tutorials/17_render_pass_tutorial.md
tutorials/18_simple_demo_tutorial.md
tutorials/19_text_geom_tutorial.md
tutorials/20_particles_tutorial.md
tutorials/21_heightmap.md
tutorials/22_environment_map.md
tutorials/24_boundingbox_camera_tutorial.md

Done by cherry-picking commits
Port gz-rendering10 to main
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/main...gz-rendering10

Merge 10 -> main
