gazebosim/gz-rendering

ogre/src/OgreGrid.cc, ogre2/src/Ogre2Grid.cc
This PR introduces a better and more intuitive approach to odd horizontal and vertical cell count.  Previously, odd vertical cell count would change the grid to be about the origin, and odd horizontal cell count would readjust the grid as well.  This PR will simply append a row and column to the grid in cases of odd horizontal cell count instead of moving the grid over.  Similarly, an odd vertical cell count will add a grid layer above the current grid rather than moving the grid to center itself around the origin.  I also found a bug in the vertical bar generation of the 3D grids and fixed it in this PR.
Before:
After
Before:
After:
Fixes [ign-rendering#70](https://github.com/ignitionrobotics/ign-rendering/issues/70)
Signed-off-by: John Shepherd <john@openrobotics.org>
=> Add odd grid offset and fix vertical bars

.github/CODEOWNERS, .github/workflows/ci-bionic.yml, .github/workflows/pr-collection-labeler.yml, .github/workflows/triage.yml, README.md
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update codecov badge
* Port `CODEOWNERS`
=> [ign-rendering3] Workflow updates

Changelog.md, examples/simple_demo/GlutWindow.cc, examples/simple_demo/Main.cc, ogre2/include/ignition/rendering/ogre2/Ogre2ArrowVisual.hh, ogre2/include/ignition/rendering/ogre2/Ogre2AxisVisual.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh, ogre2/src/Ogre2ArrowVisual.cc, ogre2/src/Ogre2AxisVisual.cc, ogre2/src/Ogre2Scene.cc, src/ArrowVisual_TEST.cc, src/AxisVisual_TEST.cc, tutorials/18_simple_demo_tutorial.md
Implementation was already done in the base classes ([BaseAxisVisual](https://github.com/ignitionrobotics/ign-rendering/blob/master/include/ignition/rendering/base/BaseAxisVisual.hh) and [BaseArrowVisual](https://github.com/ignitionrobotics/ign-rendering/blob/master/include/ignition/rendering/base/BaseArrowVisual.hh)). This PR closes the loop by filling in the `Create*Visual` functions in `Ogre2Scene` class.
Added tests and updated `simple_demo` to include an axis visual
=> Add ogre2 AxisVisual and ArrowVisual

include/ignition/rendering/base/BaseArrowVisual.hh, src/ArrowVisual_TEST.cc
Complete Shaft and Head methods in BaseArrowVisual
=> Complete Shaft and Head methods in BaseArrowVisual

Changelog.md, ogre2/src/Ogre2DepthCamera.cc, test/integration/depth_camera.cc, test/integration/gpu_rays.cc, test/test_config.h.in
see  ignitionrobotics/ign-gazebo#14
May need to fix CI...
=> Update test configuration to use ogre2

BUILD.bazel, ogre2/BUILD.bazel, ogre2/src/Ogre2RenderEngine.cc
We need to produce shared libraries in Bazel in order for plugins to be properly loaded in the later portion of the dependency chain.
Signed-off-by: Michael Carroll <michael@openrobotics.org>
=> Restructure rendering build to account for gui interactions

ogre/src/OgreRenderEngine.cc, ogre2/src/Ogre2RenderEngine.cc, src/RenderEngineManager.cc
I just copied how this was done in Ignition GUI
=> Add environment variable to locate plugins

ogre2/include/ignition/rendering/ogre2/Ogre2DepthCamera.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2GaussianNoisePass.cc, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/media/materials/programs/depth_camera_final_fs.glsl, ogre2/src/media/materials/programs/depth_camera_final_vs.glsl, ogre2/src/media/materials/programs/depth_camera_fs.glsl, ogre2/src/media/materials/programs/gaussian_noise_depth_fs.glsl, ogre2/src/media/materials/scripts/depth_camera.material, ogre2/src/media/materials/scripts/gaussian_noise.material, test/integration/render_pass.cc
Depth cameras in ign-rendering generates both depth and color data using custom shader scripts so we can not apply regular image based Gaussian noise pass to its output. Instead, I updated Ogre2DepthCamera class to support its own render pass chain, and wrote a separate fragment shader that works with the depth camera data format. 
The Gaussian noise is applied individually to each component in the point cloud data, i.e. x, y, z, and r, g, b. 
Here's a [depth_noise.sdf](https://gist.github.com/iche033/898d7888462b2cdf264a0808942660b0) for testing in ign-gazebo (requires ignitionrobotics/ign-sensors#35). To launch:
```
ign gazebo -v 4 depth_noise.sdf
```
Select the `/camera/image` topic in the ImageDisplay plugin to see the following image output:
As for the depth image, the effect is not …
=> Add support for Gaussian noise render pass in Ogre2DepthCamera 

include/ignition/rendering/LidarVisual.hh, include/ignition/rendering/base/BaseLidarVisual.hh, ogre/include/ignition/rendering/ogre/OgreLidarVisual.hh, ogre/src/OgreLidarVisual.cc, ogre/src/media/materials/programs/point_fs.glsl, ogre/src/media/materials/programs/point_vs.glsl, ogre/src/media/materials/scripts/point_cloud_point.material
@iche033  Please refer to this PR for point color material and implementation, Thanks
EDIT:- adding image
To use this you can do the following :-
`lidarPointer->SetPoints(points_vector, colors_vector);`
=> Add LidarVisual point colors for Ogre1

ogre/src/OgreLidarVisual.cc, ogre2/src/Ogre2LidarVisual.cc
This PR attempts to fix the case when the data given to the sensor happens to contain a range value which is greater than, or exactly equal to the sensor range.
For rays when the sensor does not hit anything in the range, it returns `inf` for the ray. However, when we add adding noise to the measurements defaults the `inf` reading exactly equal to  `maxRange` of the sensor. This causes the lidar visual to display the rays, although they are not hitting any object.
Additionally, if a point is a finite value (even if it is greater than the maxRange), the LidarVisual showed it since the only criteria of determining if the sensor ray was hitting or not was if the value returned by the sensor was `inf`.
=> minor change in LidarVisual for the case when sensor data is more than sensor range

ogre/include/ignition/rendering/ogre/OgreLidarVisual.hh, ogre/src/OgreLidarVisual.cc, ogre2/include/ignition/rendering/ogre2/Ogre2LidarVisual.hh, ogre2/src/Ogre2LidarVisual.cc
@iche033  Please see this PR to solve the issue in [ign-gazebo/#301](https://github.com/ignitionrobotics/ign-gazebo/pull/301)
I have added to the API to set and get the visible state of the visual. I could not access the existing visibility status of the ogre node as they have not provided API's for the same. [[link]](https://forums.ogre3d.org/viewtopic.php?t=23694)
=> Adding option for visibility

Changelog.md, ogre2/include/ignition/rendering/ogre2/Ogre2DepthCamera.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2GaussianNoisePass.cc, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/media/materials/programs/depth_camera_final_fs.glsl, ogre2/src/media/materials/programs/depth_camera_final_vs.glsl, ogre2/src/media/materials/programs/depth_camera_fs.glsl, ogre2/src/media/materials/programs/gaussian_noise_depth_fs.glsl, ogre2/src/media/materials/scripts/depth_camera.material, ogre2/src/media/materials/scripts/gaussian_noise.material, test/integration/depth_camera.cc, test/integration/render_pass.cc
Merging forward 2 to 3 so we can run ogre2 tests with the latest depth camera noise changes on jenkins
=> Merge ign-rendering2 to ign-rendering3 

ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh, ogre2/include/ignition/rendering/ogre2/Ogre2GaussianNoisePass.hh, ogre2/include/ignition/rendering/ogre2/Ogre2Light.hh, ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh, ogre2/include/ignition/rendering/ogre2/Ogre2MeshFactory.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderPass.hh, ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh, ogre2/include/ignition/rendering/ogre2/Ogre2Visual.hh, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2GaussianNoisePass.cc, ogre2/src/Ogre2Light.cc, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2MeshFactory.cc, ogre2/src/Ogre2RenderPass.cc, ogre2/src/Ogre2Scene.cc, ogre2/src/Ogre2Visual.cc
Updated several ogre2 classes to use pimpl. Most of the private classes are currently empty.
=> Pimpl'ize ogre2 classes

CMakeLists.txt, Migration.md, examples/gazebo_scene_viewer/SceneManager.cc, examples/gazebo_scene_viewer/SceneManagerPrivate.hh, examples/ogre2_demo/GlutWindow.cc, include/ignition/rendering/Scene.hh, include/ignition/rendering/base/BaseScene.hh, src/Scene_TEST.cc, src/base/BaseScene.cc, test/integration/gpu_rays.cc
This PR is part of this issue https://github.com/ignitionrobotics/ign-common/issues/61. The idea it's to deprecate the class `common::Time` in favor of `std::chrono`.
Depends on:
- https://github.com/ignitionrobotics/ign-math/pull/150
=> Replace common::Time with std::chrono

tutorials/11_gazebo_scene_viewer_tutorial.md, tutorials/12_mesh_viewer_tutorial.md, tutorials/13_custom_scene_viewer.md, tutorials/14_camera_tracking_tutorial.md, tutorials/15_custom_shaders_tutorial.md, tutorials/17_render_pass_tutorial.md, tutorials/18_simple_demo_tutorial.md, tutorials/19_text_geom_tutorial.md, tutorials/20_particles_tutorial.md
* Instruct user to clone this repository: users landing in https://ignitionrobotics.org/api/rendering/4.0/tutorials.html don't know where to start from otherwise
* Split command from command results, so it's clearer to the user what they need to do
* Fix the custom shaders tutorial - it was telling the user to compile the camera tracking
I updated many tutorials, but I only walked through these ones:
* custom shaders
* particles
* text geometry
* render pass
There may be more things to fix on the other ones.
=> Updates to tutorials

ogre2/src/Ogre2DepthCamera.cc
backport changes from pull request #130 to fix #129 
ign-rendering2 does not run ogre2 test on jenkins so there shouldn't be a change in the CI build results. However, ign-sensors2 and ign-gazebo2 both run rendering tests with ogre2, so this change should fix their depth and rgb camera test failures on ubuntu CI builds
=> Backport ogre2 depth camera fix

examples/camera_tracking/GlutWindow.cc, tutorials/14_camera_tracking_tutorial.md
* updated description
* use references to code snippets in example instead of writing out the whole function signature
* removed the `SetWorld*` functions. They are useful but not particularly specific to camera tracking. Maybe it'll suit better in a separate tutorial on node transforms in ign-rendering
=> Update camera tracking tutorial

tutorials/17_render_pass_tutorial.md
=> Update render pass tutorial

tutorials/13_custom_scene_viewer.md
Minor tweaks to clarify what's features are not supported in ogre
=> Update custom scene viewer tutorial

CMakeLists.txt, ogre/src/CMakeLists.txt, ogre2/src/CMakeLists.txt, optix/src/CMakeLists.txt
Another step towards getting full support for custom render engines from command line.  This PR symlinks binaries that don't contain the version number (same as how physics is doing for `dartsim` and `tpe`) so the user will not have to specify the version of ignition-rendering they are currently using when specifying an engine binary name.  More progress towards getting https://github.com/ignitionrobotics/ign-rendering/issues/100 resolved
Signed-off-by: John Shepherd <john@openrobotics.org>
=> Add unversioned symlinks for engine plugins

src/RenderEngineManager.cc
The tests are still unloading the render engines using the engine name (`ogre2`) as opposed to the library name (`ign-rendering-ogre2`). The changes add an additional logic to translate the engine name to lib name before unloading the engines.
=> Fix unloading render engines

include/ignition/rendering/base/BaseNode.hh, include/ignition/rendering/base/BaseVisual.hh, src/Node_TEST.cc
ogre 1 and 2 crashes if given nan pose values. This PR catches nan and inf values before passing them to the underlying render engine.
=> Fix crash due to NaN pose values

ogre/src/OgreRenderEngine.cc, ogre2/src/Ogre2RenderEngine.cc
This PR is meant to resolve new codecheck issues introduced by ignitionrobotics/ign-cmake#117.
From my understanding, the plan is to forward port the fixes here to all other ignition versions once ignitionrobotics/ign-cmake#117 is merged.
=> Resolve updated codecheck issues

test/integration/camera.cc
This test has been flaky for a while, see history:
https://build.osrfoundation.org/job/ignition_rendering-ci-ign-rendering3-bionic-amd64/lastBuild/testReport/(root)/Camera_CameraTest/VisualAt_ogre2/history/
I can't reproduce the failure locally even running the test hundreds of times. So in this PR, I'm changing some conditions so the next time the test flakes, we should at least have more information about how it fails.
=> 👩‍🌾 Make flaky VisualAt test more verbose

include/ignition/rendering/MeshDescriptor.hh
This PR is related with this other PR https://github.com/ignitionrobotics/ign-sensors/pull/58
There are some Windows warning comming from this package. https://build.osrfoundation.org/job/ign_sensors-pr-win/508/msbuild/new/
=> Remove some windows warnings

ogre2/include/ignition/rendering/ogre2/Ogre2ParticleEmitter.hh, ogre2/src/Ogre2Material.cc
When `SetAlphaFromTexture(true)` is invoked on a material with texture that does not have an alpha channel, it causes the visual with the assigned material to be completely transparent. The fix is to do a check to make sure the texture does have an alpha channel, and if not we disable using alpha from the texture.
These changes were included in pull request #182 for ign-rendering5, which are necessary for displaying the `Indoor Lighting` model. 
Another test: launch ign-gazebo and insert the [DronePlatformX1](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/DronePlatformX1) model. Without these changes, the model is transparent.
=> Fix transparency issue for textures without alpha channel

CMakeLists.txt, include/ignition/rendering/Material.hh, include/ignition/rendering/base/BaseMaterial.hh, ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh, ogre2/include/ignition/rendering/ogre2/Ogre2ParticleEmitter.hh, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2MeshFactory.cc, src/Material_TEST.cc
depends on ignitionrobotics/ign-common#132
main changes:
* updated mesh factory to create mesh with multiple texture coordinate sets
* added lightmap APIs to Material - users can choose which texture coordinate set to use for the lightmap
* To keep things simple, lightmap is currently blended with the base albedo map using the Overlay bend mode (here's a [description](https://helpx.adobe.com/photoshop/using/blending-modes.html) of the different blend modes).
* fixed a transparency issue that happens when a grayscale albedo map is used.
=> Add support for lightmaps in ogre2

Changelog.md, README.md, tutorials/02_install.md
=> 3 to 4 20210122

ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2ThermalCamera.cc, ogre2/src/media/materials/programs/heat_signature_fs.glsl, ogre2/src/media/materials/programs/thermal_camera_fs.glsl
The thermal camera class has functions to set heat source and ambient temperature range. This was simulated by varying an object's temperature based on its depth value (distance from the camera). This PR provides an alternative way to vary an object's temperature based on its color value.
Non-heat source objects, i.e visuals without a uniform temperature or heat signature, will now have variations in their thermal readings as a function of color - the darker the object the warmer the object. See https://github.com/ignitionrobotics/ign-gazebo/pull/578 for an example output
Note: This is not how a physical thermal camera works. The goal is to provide automated way of simulating enough temperature differences so that thermal data processing algorithms are able to segment out different …
=> Add temperature variations to thermal camera readings based on color

ogre/src/CMakeLists.txt
This was introduced in https://github.com/ignitionrobotics/ign-rendering/pull/206, and now trying to compile `ign-gui3` against it I get:
```
CMake Error at src/plugins/CMakeLists.txt:29 (add_library):
Target "Grid3D" links to target "IgnOGRE::IgnOGRE" but the target was not               
found.  Perhaps a find_package() call is missing for an IMPORTED target, or
an ALIAS target is missing?       
Call Stack (most recent call first): 
src/plugins/CMakeLists.txt:77 (ign_gui_add_library)
src/plugins/grid_3d/CMakeLists.txt:1 (ign_gui_add_plugin)
CMake Error at src/plugins/CMakeLists.txt:29 (add_library):
Target "Scene3D" links to target "IgnOGRE::IgnOGRE" but the target was not
found.  Perhaps a find_package() call is missing for an IMPORTED target, or
an ALIAS target is missing? …
```
=> Revert IgnOGRE Windows fix, it breaks downstream libraries

examples/gazebo_scene_viewer/SceneManager.hh, include/ignition/rendering/ArrowVisual.hh, include/ignition/rendering/AxisVisual.hh, include/ignition/rendering/Camera.hh, include/ignition/rendering/CompositeVisual.hh, include/ignition/rendering/Geometry.hh, include/ignition/rendering/Image.hh, include/ignition/rendering/Light.hh, include/ignition/rendering/Material.hh, include/ignition/rendering/Mesh.hh, include/ignition/rendering/Node.hh, include/ignition/rendering/OrbitViewController.hh, include/ignition/rendering/RenderEngine.hh, include/ignition/rendering/RenderEngineManager.hh, include/ignition/rendering/RenderTarget.hh, include/ignition/rendering/Scene.hh, include/ignition/rendering/Storage.hh, include/ignition/rendering/ViewController.hh, include/ignition/rendering/Visual.hh
A simple fix in the documentation
=> Fixed spelling Desconstructor -> Destructor

ogre2/include/ignition/rendering/ogre2/Ogre2GpuRays.hh, ogre2/src/Ogre2GpuRays.cc, ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl, ogre2/src/media/materials/programs/gpu_rays_2nd_pass_fs.glsl, ogre2/src/media/materials/scripts/gpu_rays.material, test/integration/gpu_rays.cc
As discussed here https://github.com/ignitionrobotics/ign-rendering/issues/181 and suggested by @iche033 . Taking huge inspiration and copypasting from Ogre2ThermalCamera (not sure I get the full shader logic). The implementation here is similar as the temperature tag from the Ogre2ThermalCamera.
laser retro values are valid on the range 0.0 to 2000.0 as it was, I believe, on Gazebo Classic. It can be an opportunity to discuss and change this behavior if needed.
There seem to be a loss of precision of around 5 retro value (see the test), don't know if it is due to some noise added in the pipeline or some shader witchery, but it works well for my use case (simulating lidar reflective tape).
With this PR, a pending PR in sdformat (https://github.com/osrf/sdformat/pull/454) and one in …
=> Add laser retro support in Ogre2

ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2ThermalCamera.cc
Thermal camera uses unlit material for background objects. When visualizing thermal camera output in a more complex environment, I noticed that the textures are not correct copied over from Pbs to Unlit datablock. The changes here make sure we set the correct texture file to the unlit material.
=> Fix converting Pbs to Unlit material conversion

include/ignition/rendering/base/BaseLightVisual.hh, ogre/include/ignition/rendering/ogre/OgreHeightmap.hh, ogre/include/ignition/rendering/ogre/OgreLightVisual.hh, ogre/include/ignition/rendering/ogre/OgreScene.hh, ogre/src/OgreLightVisual.cc, ogre2/include/ignition/rendering/ogre2/Ogre2LightVisual.hh
Related with this regression issue https://github.com/ignitionrobotics/ign-rendering/issues/226
=> Fix Windows regresion on OgreLightVisual

Changelog.md, ogre2/src/Ogre2ThermalCamera.cc, ogre2/src/media/materials/programs/heat_signature_fs.glsl, ogre2/src/media/materials/programs/thermal_camera_fs.glsl, test/integration/thermal_camera.cc
The existing thermal camera implementation produces image output in 16 bit format and that's being hard coded in various places including the shaders. This PR makes the implementation slightly more generic to support generating 8 bit data.
There are a few workarounds that had to be done so that this change does not break ABI. For example, the new thermal image event's function callback is hard coded to `uint16_t` and that can not be changed so unfortunately I had to workaround this by packing 8 bit data into 16 bit array. 
---
=> Add support for 8 bit thermal camera image format

CMakeLists.txt, Changelog.md, ogre/include/ignition/rendering/ogre/OgreMaterialSwitcher.hh, ogre/include/ignition/rendering/ogre/OgreRenderTargetMaterial.hh, ogre2/src/Ogre2GpuRays.cc
Prepares for 4.4.0 release and merges ign-rendering3 forward.
https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering4_4.3.1...ign-rendering4
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+archived%3Afalse+)
to support the maintainers
=> 4 4 0 prep

src/RenderEngineManager.cc
I'm working on this as part of https://github.com/ignitionrobotics/ign-sensors/issues/18, but the current state of this PR applies even outside that context.
This is making error messages more verbose when loading a render engine:
* If no render engine interface was found, but other interfaces were, print the names of the other interfaces.
* If multiple render engines were found, warn the user that there were others, and keep choosing a random one (note that `pluginNames` is an `unordered_set`, so getting `begin` is "random").
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+archived%3Afalse+)
to support the maintainers
=> More verbose messages when failing to load render engine

ogre2/src/Ogre2Material.cc
Resolves issue https://github.com/ignitionrobotics/ign-rendering/issues/139 for OBJ files only
The Ogre 2 plugin uses a texture's filename to uniquely identify each texture, so any textures named `texture.png` are treated the same, even if they're in different directories. The new change checks to see if the mesh has an OBJ file (`model.obj`), if it does it sets `baseName` to be the full path (instead of `texture.png`).
For example, load this world on `ign-gazebo`:
<details><summary>world.sdf</summary>
<p>
```
<?xml version="1.0" ?>
<sdf version="1.6">
<world name="shapes">
<plugin
filename="ignition-gazebo-physics-system"
name="ignition::gazebo::systems::Physics">
</plugin>
<plugin
filename="ignition-gazebo-scene-broadcaster-system"
name="ignition::gazebo::systems::SceneBroadcaster"> …
```
=> Fixed OBJ textures

ogre2/src/Ogre2GpuRays.cc, ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl, ogre2/src/media/materials/programs/gpu_rays_2nd_pass_fs.glsl, ogre2/src/media/materials/scripts/gpu_rays.material, test/integration/gpu_rays.cc
depends on #251
Lidars detect particles as large blocky squares due to the way particles are rendered in ogre (2d sprites / billboard). This PR applies scattering effect in a similar way as it's done for the depth camera in pull request #251. Whenever a ray in the lidar intersects with a particle, there is a chance that it'll miss or become scattered (by adding Gaussian noise). 
* Launch ign-gazebo with this [sensor_particles.sdf](https://gist.github.com/iche033/26888ed86b27f824e5979c385ea393f1) world. 
* Open the Visualize Lidar gui plugin (open top right menu and select `Visualize Lidar`
* Hit refresh button next to the topic drop down list in the Visualize Lidar plugin to see the `/lidar` topic
* Hit Play to see lidar visualization.
**Note to maintainers**: Remember to use …
=> Apply particle scattering effect to lidars

.github/ci/after_make.sh, ogre2/src/Ogre2RenderEngine.cc, test/integration/camera.cc
Our tests on `ign-rendering` and `ign-gui` occasionally fail on GitHub actions because they can't open the display, see more info on https://github.com/ignitionrobotics/ign-gui/issues/58.
This is an attempt of making the display tests more robust (with the new arguments passed to `Xvfb`) and failures more verbose (with the updated error messages on `Ogre2RenderEngine`).
Unfortunately, the failure is so rare that I haven't been able to get a failure message with this branch yet. It should come with time, unless the changes to the `Xvfb` invocation really fix it.
---
https://github.com/osrf/buildfarmer/issues/161
=> 👩‍🌾 Make GitHub actions tests that are flaky due to display more verbose

examples/custom_scene_viewer/DemoWindow.cc, examples/custom_scene_viewer/ManualSceneDemo.cc
No issue raised but related to #185
The example `custom_scene_viewer` does not display a window on macOS. The example will build  and run, the console will display the usage, however the GLUT window does not open.
- OS: macOS Catalina 10.15.7
- Machine: Mac Pro (2019)
- Config: ignition-rendering4 
The issue was that the OpenGL context was not managed for macOS. The fix is to add the conditional compilation flags and variables used in the `simple_demo` and adapt them for this example. It was also necessary to move the glutInit() to 
main() as it seems that this is required before the rendering engine is initialised during the scene building.
1. Add OpenGL context settings for macOS to the DemoWindow.
2. Move glutInit to main
3. Add command line option to set the ogre engine.
Because of …
=> Fix custom_scene_viewer for macOS

ogre2/src/Ogre2RenderEngine.cc
This change raises system requirements as it uses GLX 1.3 API and a GLX extension. Modern systems like Ubuntu bionic and focal satisfies these without issue.
Tested on bionic without GPU (QEMU) and focal with GPU.
Fixes issue #128 and similar issues.
Newer GLX APIs are used to explicitly request core profile GL context that Ogre2 uses. 
Reference:
https://www.khronos.org/opengl/wiki/Tutorial:_OpenGL_3.0_Context_Creation_(GLX)
Reproduce:
Run `ign gazebo shapes.sdf` with the default ogre2 renderer on systems with non-AMD (e.g. Intel) mesa GL drivers or in situations where the hardware GPU is not accessible (e.g. QEMU VM).
The original code has a decent chance to fail due to it attempting to create OpenGL context in compatibility profile and the GL version of context created would be below …
=> ogre2: explicitly request OpenGL 3.3 core profile context.

examples/gazebo_scene_viewer/CMakeLists.txt, examples/gazebo_scene_viewer/CameraWindow.cc, examples/gazebo_scene_viewer/GazeboDemo.cc, examples/gazebo_scene_viewer/GazeboWorldDemo.cc, examples/gazebo_scene_viewer/SceneManager.cc, examples/gazebo_scene_viewer/SceneManagerPrivate.hh
This is similar to PR #256. The example `gazebo_scene_viewer` does not display a window on macOS. The example will build and run, the console will display the usage, however the GLUT window does not open. There was also a non-macOS specific issue where the window would segfault on exit when triggered by an ESC keypress in the window.
- OS: macOS Catalina 10.15.7
- Machine: Mac Pro (2019)
- Config: ignition-rendering4
The macOS changes involve setting up and managing the correct OpenGL context. The segfault issue was caused by two things: the first was a potential nullptr dereference in the subscriber callbacks, this is now checked and in any case should not be hit provided the transport is cleaned up before the scene mangers go out of scope. The second issue was the gazebo transport node …
=> Fix gazebo_scene_viewer for macOS and ensure exits cleanly

ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2ParticleEmitter.cc, ogre2/src/Ogre2ParticleNoiseListener.cc, ogre2/src/Ogre2ParticleNoiseListener.hh, ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl, src/ParticleEmitter_TEST.cc, test/integration/depth_camera.cc, test/integration/gpu_rays.cc
used by https://github.com/ignitionrobotics/ign-gazebo/pull/674
This lets users configure the particle scatter ratio parameter that was previously hardcoded in a couple different sensor src files.
The `particleScatterRatio` param determines the amount of scattering effect applied to sensors (depth camera and lidars). The higher the value, the more "scattering" (noise) is added to the depth readings.  This value was fixed and now it's configuration though the `ParticleEmitter`'s `UserAny` object
see https://github.com/ignitionrobotics/ign-gazebo/pull/674
=> Expose particle scatter ratio parameter

include/ignition/rendering/base/BaseMaterial.hh, ogre2/src/Ogre2Material.cc
Fixes https://github.com/ignitionrobotics/ign-gazebo/issues/496
Fixes issue with ign-gazebo's TransformControl tool being occluded by models.
The ogre2 transparency blend mode setting was being override when copying a material due to the order of the calls.
-> `SetTransparency` -> sets blend mode
-> `SetAlphaFromTexture`- > overrides the blend mode set in the previous call if arg is `false`
The PR reverses the order to make sure we keep the blend mode if visual is semi-transparent
Also made sure that if `SetAlphaFromTexture(false)` is called any time afterwards, we don't change the existing blend mode.
=> Fix overriding ogre2 transparency blend mode

test/integration/render_pass.cc
Fixes one of the test Gaussian noise test failures mentioned in #175
While the difference between data with noise and data without noise should be within 3 sigma, the difference between 2 noisy values should be within 2 * 3 sigma, i.e. full span of the Gaussian noise distribution
=> Fix DepthGaussianNoise test

ogre2/src/Ogre2ThermalCamera.cc, ogre2/src/media/materials/programs/thermal_camera_fs.glsl
Related to https://github.com/ignitionrobotics/ign-gazebo/pull/621. This handles temperatures that are <= 0 kelvin for the thermal camea.
=> Handle non-positive object temperatures

include/ignition/rendering/Capsule.hh, include/ignition/rendering/base/BaseCapsule.hh, ogre/include/ignition/rendering/ogre/OgreCapsule.hh, ogre/src/OgreCapsule.cc, ogre/src/OgreMarker.cc, ogre2/include/ignition/rendering/ogre2/Ogre2Capsule.hh, ogre2/src/Ogre2Capsule.cc, ogre2/src/Ogre2Marker.cc, src/Capsule_TEST.cc, src/Marker_TEST.cc
* Change `Create` to `Update` to reflect better what the function is used for
* Made `ogre1` and `ogre2` code very similar - the only difference are the `2`s
* Changed the `Update` function so that the existing mesh is updated even when a new mesh doesn't need to be created (in case we add other properties that make `capsuleDirty` without altering the mesh's name)
* Got the markers to work with `ign-gazebo`, opening a PR soon.
=> Suggestions to #200

include/ignition/rendering/ParticleEmitter.hh, include/ignition/rendering/base/BaseParticleEmitter.hh, ogre2/src/Ogre2ParticleNoiseListener.cc, ogre2/src/Ogre2ParticleNoiseListener.hh, src/ParticleEmitter_TEST.cc, test/integration/depth_camera.cc, test/integration/gpu_rays.cc
Addresses a missing API that was mentioned [here](https://github.com/ignitionrobotics/ign-rendering/pull/264#discussion_r596898756). This breaks ABI, so this is targeting Edifice before release.
=> Add API for particle emitter scatter ratio

ogre2/src/Ogre2Node.cc
Ignition Gazebo has been crashing on shutdown whenever there are models in an `ogre2` world.
This is a quick fix for the crash just so this is fixed by the release, but I haven't spent time looking into whether this is happening on Dome or tracking down when the problem started.
=> Fix crash on shutdown

test/integration/gpu_rays.cc, test/integration/lidar_visual.cc
=> Test fixes to Ogre2.2 branch

ogre2/src/Ogre2Light.cc, src/Light_TEST.cc
The light intensity has to be scaled by PI before applying it as the  power scale for Ogre2 lights. Without this change, the default sun light brightness is different between ign-gazebo4 and ign-gazebo5
Left: ign-gazebo4, Right: ign-gazebo5
=> Scale light intensity by PI for Ogre2

examples/actor_animation/Main.cc, examples/camera_tracking/Main.cc, examples/custom_scene_viewer/ManualSceneDemo.cc, examples/gazebo_scene_viewer/GazeboDemo.cc, examples/gazebo_scene_viewer/GazeboWorldDemo.cc, examples/lidar_visual/Main.cc, examples/mesh_viewer/Main.cc, examples/mouse_picking/Main.cc, examples/particles_demo/Main.cc, examples/render_pass/Main.cc, examples/simple_demo/Main.cc, examples/thermal_camera/Main.cc, examples/transform_control/Main.cc, examples/view_control/Main.cc
Updated the following examples to use a command line argument to determine which version of Ogre to use (Ogre1 vs. Ogre2):
- actor_animation
- camera_tracking
- custom_scene_viewer
- gazebo_scene_viewer
- lidar_visual
- mesh_viewer
- mouse_picking
- particles_demo
- render_pass
- simple_demo
- thermal_camera
- transform_control
- view_control
=> Added command line argument for examples to pick version of Ogre

src/base/BaseScene.cc
This was brought up during the tutorial party. This warning is always printed when using `ogre1`, even when the user is not trying to enable the sky. This change makes it so the error is only printed for users trying to enable sky.
Keeping this as draft until the stable release, it's not a critical bugfix.
CC @ammaar8
=> Silence noisy sky error

ogre/src/OgreMeshFactory.cc, ogre2/src/Ogre2MeshFactory.cc
Certain meshes can produce significant amount of output, such as:
```
[GUI] [Wrn] [SubMesh.cc:478] Multiple texture coordinate sets exist in submesh: WoodBeamRound. Checking first set with index: 0
[GUI] [Wrn] [SubMesh.cc:302] Multiple texture coordinate sets exist in submesh: CeilingRocky. Checking first set with index: 0
```
If you have subt installed, run:
```
ign launch -v 4 cloudsim_sim.ign circuit:=tunnel worldName:=niosh_sr_config_a levels:=false
```
=> Prevent texture spam

include/ignition/rendering/base/BaseLightVisual.hh
Port spot light visual size fix from https://github.com/osrf/gazebo/pull/2947 by @peci1
=> Update spot light visual size

CMakeLists.txt, examples/ogre2_demo/CMakeLists.txt, ogre2/include/ignition/rendering/ogre2/Ogre2Conversions.hh, ogre2/include/ignition/rendering/ogre2/Ogre2MaterialSwitcher.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderTargetMaterial.hh, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2DynamicRenderable.cc, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2RenderTargetMaterial.cc, ogre2/src/Ogre2Scene.cc, ogre2/src/Ogre2SelectionBuffer.cc
Signed-off-by: Michael Carroll <michael@openrobotics.org>
=> Local updates for Ogre2.2 against main branch

test/integration/depth_camera.cc, test/integration/render_pass.cc
Fixes #315 
Fixes tests that check the alpha value of pixels returned by the Depth Camera. As explained in #315, the internal texture format does not have an alpha channel so the graphics card driver is free to fill any value it wants. I've updated the test to check for either `255` or `0` which we have seen on the CI machines and also on a computer with AMD card with mesa driver. I'm also open to just removing this check in the test.
I also re-enabled the test on macOS :crossed_fingers: 
=> Fix depth alpha

include/ignition/rendering/RenderingIface.hh, ogre/src/OgreRenderEngine.cc, src/RenderingIface.cc, src/RenderingIface_TEST.cc
Most applications will only have one rendering engine loaded at a time, and only one scene within that. This helper function gets the first scene that can be found in any rendering engine.
This pattern is being repeated on several `ign-gui` and `ign-gazebo` plugins, so it would be nice to reduce duplication. For example:
* [Screenshot](https://github.com/ignitionrobotics/ign-gui/blob/ffbdb26ce519f85b273d57527a11470dae3838e1/src/plugins/screenshot/Screenshot.cc#L184-L229)
* [Grid3D](https://github.com/ignitionrobotics/ign-gazebo/blob/f795b657683f629133e7de056771959786a150fd/src/gui/plugins/grid_config/GridConfig.cc#L152-L187)
* [VisualizeLidar](https://github.com/ignitionrobotics/ign-gazebo/blob/a41cf80049c07977079d0b215398dc4225b63038/src/gui/plugins/visualize_lidar/VisualizeLidar.cc#L151- …
=> Helper function to get a scene

ogre2/src/media/materials/programs/depth_camera_final_fs.glsl, ogre2/src/media/materials/scripts/depth_camera.material, test/integration/depth_camera.cc
Fixes #332
Fixes #108
Details are in ticket #332
It's slightly possible this bug could come back in the future.
=> Fix floating point precision bug handling alpha channel (#332)

src/Image.cc
Using a custom deallocator to avoid breaking ABI
Alternatively C++17 supports the following syntax, which was not used:
`typedef std::shared_ptr<unsigned char[]> DataPtr;`
Another self-explanatory bugfix. Pointers allocated with new [] must be deallocated with delete []; not with "delete"
I thought I could not avoid breaking ABI but turns out it was easy. Thus there is no ABI breakage in this fix.
It may be possibly to backport this fix to older versions
Found by Valgrind. Also detected by ASAN. To use ASAN, just add to ign-rendering/ogre2/src/CMakeLists.txt:
```
set( CMAKE_C_FLAGS_DEBUG
"${CMAKE_C_FLAGS_DEBUG} -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address" )
set( CMAKE_CXX_FLAGS_DEBUG …
```
=> Fix new [] / delete mismatch

ogre2/src/Ogre2SelectionBuffer.cc
PF_RGB is 3 bytes. But later on Ogre2SelectionBuffer::OnSelectionClick
will try to read 4 bytes from it.
Fixed by ensuring it's always at least 4 bytes and zero-initializing
those 4 bytes.
This is too simple of a fix and self explanatory. We were allocating 3 bytes of data and then reading 4 bytes in `Ogre2SelectionBuffer::OnSelectionClick`.
It may be possible to backport to older versions.
Detected by ASAN, just add to ign-rendering/ogre2/src/CMakeLists.txt:
```
set( CMAKE_C_FLAGS_DEBUG
"${CMAKE_C_FLAGS_DEBUG} -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address" )
set( CMAKE_CXX_FLAGS_DEBUG
"${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address" )
set( …
```
=> Fix heap overflow when reading

ogre2/src/media/materials/programs/depth_camera_final_fs.glsl, ogre2/src/media/materials/scripts/depth_camera.material, test/integration/depth_camera.cc, test/integration/render_pass.cc
Backport macOS depth camera fixes from #316, #333, #335
=> Backport mac camera floating fix

ogre2/src/Ogre2RenderTarget.cc
Fixes #341 
When a render pass is added but not enabled, it was found that ogre2 compositor nodes are being unnecessarily recreated every frame, see this comment: https://github.com/ignitionrobotics/ign-rendering/pull/313#issuecomment-861073829
I've updated the check to take into account the enabled state of the render pass so that we only recreate the nodes if the ogre compositor node is not found but render pass is enabled.
To test: 
1. build and run `ogre2_demo`
2. GPU usage should be lower after the fix. I use `nividia-smi` to check this.
=> Fix ogre2 render pass high GPU usage

examples/custom_shaders_uniforms/CMakeLists.txt
Fixed package version number that was missed when the changes were forward ported from `ign-rendering4`. 
We'll need to change it to `ign-rendering6` when forward porting to `main` 
=> Fix custom shaders uniforms ign-rendering package version number

src/GaussianNoisePass_TEST.cc
The GaussianNoisePass unit test occasionally fails because the value generated is outside of the 3-sigma. I've relaxed the tol check to be 4-sigma which is something we also did in the integration test, [see here](https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering5/test/integration/render_pass.cc#L313)
=> Relax Gaussian noise test tolerance to fix flaky test

ogre2/src/Ogre2RenderEngine.cc
Fixes UNIT_RenderingIface_TEST failure.
It's too simple. Check for Nullptr. Also I noticed gazebo could crash if it tried to destroy a texture already scheduled for destruction.
=> Small crash fix on shutdown

include/ignition/rendering/base/BaseCamera.hh
The test has been failing on github CI. It's likely due to uninitialized variable. 
=> Fixing camera projection type test

include/ignition/rendering/Node.hh, include/ignition/rendering/Visual.hh, include/ignition/rendering/base/BaseNode.hh, include/ignition/rendering/base/BaseVisual.hh, src/base/BaseScene.cc
Fixes https://github.com/ignitionrobotics/ign-rendering/issues/58
This PR is part of the effort to consolidate `ign-gui` and `ign-gazebo` (related to this conversation https://github.com/ignitionrobotics/ign-gui/pull/231#discussion_r662702693) and it also targets this issue https://github.com/ignitionrobotics/ign-rendering/issues/58. 
The idea is to move the `UserData` and `SetUserData` methods to the Node class. I'm not sure how to proceed about the change in the API if I should tick-tock the methods in the Visual class, this change should not affect the API because `Node` is a parent class of `Visual`, it will break ABI but this PR is targeting `main`.
=> UserData methods moved from Visual to Node

ogre/src/OgreNode.cc, ogre2/src/Ogre2Node.cc
This is motivated by a crash I had on `ign-gazebo` with this backtrace:
<details><summary>full backtrace</summary>
<p>
```
/home/chapulina/dev_bionic/ws_edifice/install/lib/ign-rendering-5/engine-plugins/libignition-rendering-ogre.so(_ZN8ignition9rendering2v58Ogr
eNode11DetachChildESt10shared_ptrINS1_4NodeEE+0x74) [0x7efb8e273984] /home/chapulina/dev_bionic/ws_edifice/src/ign-rendering/ogre/src/OgreNo
de.cc:161
/home/chapulina/dev_bionic/ws_edifice/install/lib/ign-rendering-5/engine-plugins/libignition-rendering-ogre.so(_ZN8ignition9rendering2v58Bas
eNodeINS1_10OgreObjectEE11RemoveChildESt10shared_ptrINS1_4NodeEE+0xcb) [0x7efb8e20a91b] /home/chapulina/dev_bionic/ws_edifice/src/ign-render
ing/include/ignition/rendering/base/BaseNode.hh:239 …
```
=> More nullptr checking on Node classes

Changelog.md, Migration.md, include/ignition/rendering/Camera.hh, include/ignition/rendering/Scene.hh, include/ignition/rendering/base/BaseCamera.hh, include/ignition/rendering/base/BaseScene.hh, ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/Ogre2Scene.cc, ogre2/src/Ogre2SelectionBuffer.cc, ogre2/src/Ogre2Sensor.cc, ogre2/src/Ogre2ThermalCamera.cc, src/base/BaseScene.cc
Implements #323 for ign-rendering
Explanation is in the [ticket](https://github.com/ignitionrobotics/ign-rendering/issues/323)
The ticket shouldn't be closed until all modules are merged.
This PR is currently defaulting `SetCameraPassCountPerGpuFlush` to 0 avoid breaking ign-sensors.
In order to fully test it, checkout:
1. https://github.com/darksylinc/ign-rendering/tree/matias-PostFrame5
2. https://github.com/darksylinc/ign-gazebo/tree/matias-PostFrame5
3. https://github.com/darksylinc/ign-sensors/tree/matias-PostFrame5
And set `SetCameraPassCountPerGpuFlush` to non-0 (e.g. set `Ogre2ScenePrivate::cameraPassCountPerGpuFlush` to 6)
This change is mostly a performance one; but it also affects particle FXs (and possibly some postprocessing FXs) because without this PR, Ogre2GpuRays …
=> Replace renderOneFrame for per-workspace update calls

include/ignition/rendering/Scene.hh, ogre2/src/Ogre2Scene.cc
Temporarily switching `Ogre2Scene::cameraPassCountPerGpuFlush` back to 0 (old behavior) in ogre2 until all related PRs are merged:
* https://github.com/ignitionrobotics/ign-sensors/pull/145
* https://github.com/ignitionrobotics/ign-gazebo/pull/921
Also applied style fixes as mentioned in #353
=> Temporarily set number of camera pass count per flush to 0 in ogre2 to prevent downstream build failures

include/ignition/rendering/RayQuery.hh, include/ignition/rendering/Utils.hh, src/Utils.cc, src/Utils_TEST.cc
Moved ScreenToPlane and ScreenToScene from ign-gui to ign-rendering. Some of the small plugins that I'm creating to consolidate the Scene3D use these methods. 
@scpeters do you need to retarget this PR to another branch ?
=> Moved ScreenToPlane and ScreenToScene from ign-gui to ign-rendering

include/ignition/rendering/Utils.hh, src/Utils.cc, src/Utils_TEST.cc
Related to this comment https://github.com/ignitionrobotics/ign-rendering/pull/363#discussion_r673489281
=> Fixed screento functions names

Migration.md, include/ignition/rendering/Node.hh, src/Visual_TEST.cc
This is a follow-up to #370 (see that PR for a description of the bug fix). Since #370 breaks ABI and we cannot make this change in released versions without changing behavior and potentially breaking downstream users (relevant discussion: https://github.com/ignitionrobotics/ign-rendering/pull/370#discussion_r677021521), this fix is targeted for the next unreleased version, which is Fortress.
I also added some missing test coverage/updated documentation related to #358.
=> Prevent default-constructed variants from holding a type

ogre2/src/media/Hlms/Pbs/GLSL/BRDFs_piece_ps.glsl
This PR addresses an issue with models using PBS with the ogre2 render engine on systems that do not support OpenGL 4.2 or higher (i.e. macOS).  
The fix is a one line change to one of the ogre2 GLSL shader templates. The issue is that OpenGL < 4.2 does not support swizzling of scalars (e.g. float) and this feature is used in part of the Fresnel calculation.
(See: [Data_Type (GLSL) : Swizzling](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Swizzling))
Without this change the ignition rendering example `ogre2_demo` will fail (crash because of an unhandled exception when the shader fails to compile).
With the change (and other changes specific to macOS not included in this PR) the `ogre2_demo` and other models that require PBS in ignition gazebo will work.
**Before Fix**
```console
$ …
```
=> Support OpenGL < 4.2 in PBS shader

examples/visualization_demo/Main.cc, include/ignition/rendering/ArrowVisual.hh, include/ignition/rendering/AxisVisual.hh, include/ignition/rendering/JointVisual.hh, include/ignition/rendering/Node.hh, include/ignition/rendering/Scene.hh, include/ignition/rendering/base/BaseArrowVisual.hh, include/ignition/rendering/base/BaseAxisVisual.hh, include/ignition/rendering/base/BaseJointVisual.hh, include/ignition/rendering/base/BaseNode.hh, include/ignition/rendering/base/BaseScene.hh, ogre/include/ignition/rendering/ogre/OgreJointVisual.hh, ogre/include/ignition/rendering/ogre/OgreScene.hh, ogre/src/OgreJointVisual.cc, ogre/src/OgreScene.cc, ogre2/include/ignition/rendering/ogre2/Ogre2JointVisual.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh, ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh, ogre2/src/Ogre2JointVisual.cc, ogre2/src/Ogre2Scene.cc, src/ArrowVisual_TEST.cc, src/AxisVisual_TEST.cc, src/JointVisual_TEST.cc, src/base/BaseScene.cc
Adds joint visual consisting of an axis and an arrow visual.
Gazebo Classic's implementation can be found here - https://github.com/osrf/gazebo/blob/gazebo11/gazebo/rendering/JointVisual.cc
I have added an example in the `visualization_demo` folder. 
To test it with Ignition Gazebo use the [`visualize_joints`](https://github.com/atharva-18/ign-gazebo/tree/visualize_joints) branch.
=> Joint visual

include/ignition/rendering/base/BaseJointVisual.hh
Signed-off-by: Atharva Pusalkar <atharvapusalkar18@gmail.com>
Fixes a bug in the joint child axis visual whenever the parent arrow visual is updated, as mentioned in https://github.com/ignitionrobotics/ign-gazebo/pull/961#issuecomment-904791304
=> Fix JointVisual axis head visibility

ogre/src/OgreMeshFactory.cc, ogre2/src/Ogre2MeshFactory.cc
Currently if a ign-gazebo user specifies a non-existent submesh through the `<submesh>` SDF element, an empty mesh with no submeshes will be created. The newly added warning msg is useful to help catch issues / typos with incorrectly specified submesh name.
To test:
you can change a submesh name in one of the ign-gazebo example worlds to see the warning msg printed in the console, e.g. edit [tunnel.sdf and change this submesh](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/examples/worlds/tunnel.sdf#L1106) from `BodyFront` to `FrontBody` then launch the tunnel world.
```
ign gazebo -v 4 tunnel.sdf
```
and you should see this warning msg:
```
[GUI] [Wrn] [Ogre2MeshFactory.cc:478] Unable to load mesh: 'https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/EXPLORER_R2_SEN …
```
=> Output warning message if a mesh with zero submeshes is created 

ogre2/src/Ogre2GpuRays.cc, test/integration/gpu_rays.cc
Fixes https://github.com/osrf/subt/issues/1001
Single ray gpu lidar are often created by setting `<min_angle>` == `<max_angle>` in sdf. Here's is an example taken from one of the robots from subt:
```
<lidar>
<scan>
<horizontal>
<samples>1</samples>
<resolution>1</resolution>
<min_angle>3.141592654</min_angle>
<max_angle>3.141592654</max_angle>
</horizontal>
</scan>
<range>
<min>0.05</min>
<max>40</max>
<resolution>0.01</resolution>
</range>
</lidar>
```
This generates a a lidar with 0 horizontal FOV. It sort of works but the range values produced has high precision error. The fix is to set a min allowed angle in the 1st pass when sampling depth data.
=> Fix single ray gpu lidar 

test/integration/depth_camera.cc, test/integration/thermal_camera.cc
Related to #369 and #253
These tests have been failing from time to time on macOs. 
There was a [pull request]( https://github.com/ignitionrobotics/ign-rendering/pull/333) to address #369 but I think the test still fails on certain graphics card, e.g. Intel HD Graphics 4000 as described in #369
Disabling the tests until we have time to fix them.
=> Disable flaky tests on mac

ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2ThermalCamera.cc, test/test_config.h.in
tests started failing after updating our ign-rendering6 homebrew formula to depend on ogre 2.2:
https://github.com/osrf/homebrew-simulation/pull/1574
There should be some GL3+ support for ogre 2.2 on macOS as seen in:
https://github.com/OGRECave/ogre-next/pull/209
But updated to run ogre 1.x tests until we have time to investigate the cause of failing tests on macOS.
I also fixed some clang warnings.
=> Update test config to run ogre 1.x tests in ign-rendering6 on macOS

include/ignition/rendering/Marker.hh, include/ignition/rendering/base/BaseMarker.hh, ogre/src/OgreMarker.cc, ogre2/src/Ogre2LidarVisual.cc, ogre2/src/Ogre2Marker.cc, ogre2/src/media/materials/programs/point_fs.glsl, ogre2/src/media/materials/scripts/point_cloud_point.material, src/Marker_TEST.cc
Similar to #392, this PR add new function for setting size of a marker with `MT_POINTS` points
It may be worth considering adding a marker example demo in the future for demo'ing the marker feature and it's also easier for testing.
For now, I test with the the [marker](https://github.com/ignitionrobotics/ign-gui/tree/main/examples/standalone/marker) standable example in ign-gui, and then manually modifying the marker size in ign-gazebo's `MarkerManager`
1. Build the ign-gui [marker](https://github.com/ignitionrobotics/ign-gui/tree/main/examples/standalone/marker) example
1.  We currently don't have a gui plugin or msg field for changing marker size. So manually test different marker size by applying this patch to ign-gazebo.
```cpp
diff --git a/src/rendering/MarkerManager.cc …
```
=> Add SetSize API for Marker point size

CMakeLists.txt, Changelog.md
Preparation for 4.9.0 release.
Comparison to 4.8.0: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering4_4.8.0...bump_4.9.0
=> Prepare for 4.9.0 release

CMakeLists.txt
Fixes #400
After #376, the check for Ogre-1.10 is generating warnings during the configuration of the software. The PR changes the behavior to do a fake check with `QUIET` to avoid warnings and a real check afterwards if the unofficial ogre version is used.
=> Avoid configure warning when checking ogre-1.10

ogre/src/OgreGpuRays.cc, ogre/src/OgreMesh.cc, ogre/src/OgreNode.cc, src/Utils_TEST.cc, test/integration/gpu_rays.cc
homebrew builds are now running ogre 1.x tests in ign-rendering6, and there are currently a few test failures.
This PR fixes the failing tests.   
=> Fix ogre 1.x tests

Changelog.md
Preparation for 6.0.0-pre1 release.
Comparison to ign-rendering5: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering5...prep_6.0.0-pre1
=> Prepare for 6.0.0 pre1 release

ogre2/src/Ogre2SegmentationCamera.cc
When we updated the segmentation sensor (#329) to ogre2.2, it looks like inconsistencies were introduced in what pixel channels were considered RGB.
In `Ogre2SegmentationCamera::LabelMapFromColoredBuffer`, the notation is GBR: https://github.com/ignitionrobotics/ign-rendering/blob/7aade51f83171f2ada47089e6f8594fc3ccdddc5/ogre2/src/Ogre2SegmentationCamera.cc#L371-L373
But, in the material switcher, RGB is used:
https://github.com/ignitionrobotics/ign-rendering/blob/7aade51f83171f2ada47089e6f8594fc3ccdddc5/ogre2/src/Ogre2SegmentationMaterialSwitcher.cc#L233-L234
https://github.com/ignitionrobotics/ign-rendering/blob/7aade51f83171f2ada47089e6f8594fc3ccdddc5/ogre2/src/Ogre2SegmentationMaterialSwitcher.cc#L280-L281
This PR updates the …
=> Be consistent in RGB channel notation for ogre2 segmentation camera

include/ignition/rendering/Mesh.hh, include/ignition/rendering/base/BaseMesh.hh, ogre/src/OgreMeshFactory.cc, ogre/src/OgreScene.cc, ogre2/src/Ogre2MeshFactory.cc, ogre2/src/Ogre2Scene.cc, src/Mesh_TEST.cc
Made a few minor tweaks to API and documentation
=> Minor tweaks to visual cloning 

.github/ci/packages.apt, CMakeLists.txt, include/ignition/rendering/BoundingBox.hh, include/ignition/rendering/BoundingBoxCamera.hh, include/ignition/rendering/PixelFormat.hh, include/ignition/rendering/RenderTypes.hh, include/ignition/rendering/Scene.hh, include/ignition/rendering/base/BaseBoundingBoxCamera.hh, include/ignition/rendering/base/BaseScene.hh, src/BoundingBox.cc, src/BoundingBox_TEST.cc, src/PixelFormat.cc, src/PixelFormat_TEST.cc, src/base/BaseScene.cc
I've added the public API for a bounding box sensor. Most of this is copy/pasted from #334, with a few changes:
1. There's only one constructor for the `rendering::BoundingBox` struct, which takes a type and label argument
2. The `rendering::BoundingBoxCamera::DrawBoundingBox` method takes the box color as an argument instead of defaulting to green
This PR just covers the breaking changes that are needed for the bounding box sensor so that we can add #334 to Fortress in a minor release. Some of the things I added here may not be breaking, but I wasn't sure, so I added whatever I thought could be ABI breaking. See #334 for an ogre2 implementation.
No tests have been added here because tests are written for this in #334
=> add bounding box sensor API stubs

CMakeLists.txt, Changelog.md
Preparation for 6.0.0-pre2 release.
Comparison to pre1: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering6_6.0.0-pre1...main
Preemptively opening the PR, but I'd like to get #420 in before triggering the release.
=> 🎈 6.0.0~pre2

CMakeLists.txt, Changelog.md
Spelling fix https://github.com/ignitionrobotics/ign-rendering/pull/376#issuecomment-921135875
=> Fix the spelling of USE_UNOFFICIAL_OGRE_VERSIONS flag

tutorials/02_install.md
Update installation instruciton. Ign-rendering6 now depends on ogre 2.2
=> Update Installation instruction to install ogre 2.2

CMakeLists.txt, Changelog.md, ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RayQuery.hh, ogre2/include/ignition/rendering/ogre2/Ogre2SelectionBuffer.hh, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2ParticleNoiseListener.cc, ogre2/src/Ogre2RayQuery.cc, ogre2/src/Ogre2SelectionBuffer.cc, ogre2/src/media/materials/programs/depth_camera_fs.glsl, ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl, ogre2/src/media/materials/programs/selection_buffer_fs.glsl, ogre2/src/media/materials/scripts/selection_buffer.material, test/integration/camera.cc, test/integration/scene.cc
Port ign-rendering4 to ign-rendering4
Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering5...ign-rendering4
=> Merge 4 -> 5

include/ignition/rendering/base/BaseVisual.hh
Follow-up to #397 
If cloning a visual fails, we should destroy the top-level cloned visual recursively in order to ensure that all cloned child visuals are also destroyed. I also added a check to make sure that the child visual to clone isn't `nullptr`.
=> Visual cloning: check for null children and recursively delete cloned visuals if failure occurs

ogre2/src/Ogre2RayQuery.cc, src/Utils_TEST.cc
bug was introduced in https://github.com/ignitionrobotics/ign-rendering/pull/383 when the ray query code was converted to use selection buffer.
The distance result given was from the world origin to the intersection point. This PR fixes it so that it's from the camera to the intersection point.
The bug was not caught by the test as it was not testing ray queries using the selection buffer. This PR also turns it on in `UNIT_Utils_TEST` and fixes a few tol checks.
* **Update**: argh! selection buffer related tests fail on CI: #170, and now this affects `UNIT_Utils_TEST` so disabled test in e13c1cd
=> Fix ray query distance calculation

ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2RenderTarget.cc
When both skybox and shadows are enabled in a complex scene (with lots of textures), there seem to be a weird "flickering" issue of objects. Turns out the problem is due to the skybox being rendered out of order. The skybox texture just gets rendered over the scene - so objects look like they are flickering.
Note this doesn't happen all the time. It's easier to reproduce on some machines than others.
The updated compositor setup follows the same setup in ogre samples:
https://github.com/OGRECave/ogre-next/blob/v2-2/Samples/Media/2.0/scripts/Compositors/TutorialSky_Postprocess.compositor#L8-L32
=> Fix occasional flickering issue when skybox and directional light shadows are enabled.

CMakeLists.txt
Add the missing dependency on `Paging` Ogre component for the `ogre` renderer. See https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering5/ogre/include/ignition/rendering/ogre/OgreIncludes.hh#L66 for a Paging-related include that is required. 
I noticed this missing component while working on https://github.com/conda-forge/libignition-rendering4-feedstock/pull/19#issuecomment-933532319 . Not sure if that failure was just related to this fix, but given that this fix seems to be correct in any case, I tought it could make sense to submit it.
=> ogre: Add missing required Paging component

ogre2/src/Ogre2Camera.cc, src/Utils_TEST.cc
Updates the click center pos used in the test. This should fix `ogre` test on macOs. This patch is part of #446.
There is a check added to skip `ogre2` tests because they are failing. That's fixed in #446.
=> Fix Utils unit test

include/ignition/rendering/Camera.hh, include/ignition/rendering/RenderTarget.hh, include/ignition/rendering/base/BaseCamera.hh, include/ignition/rendering/base/BaseRenderTarget.hh, ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2RenderTarget.cc
Replaces #477 which targeted the wrong branch.
Relates to: https://github.com/ignitionrobotics/ign-rendering/issues/461 and discussions in https://github.com/ignitionrobotics/ign-rendering/issues/422. It accompanies PR https://github.com/ignitionrobotics/ign-rendering/pull/463 but does not depend upon it.
This PR provides access to the underlying Metal texture object. The functions `MetalId()` and `RenderTextureMetalId()`
provide the Metal equivalent of `GLId()` and `RenderTextureGLId()` for OpenGL.
The functions expect a parameter `void* _texturePtr` which is the *address* of a pointer to `void*` as the object required for Metal is an Objective-C type `id<MTLTexture>` which we do not want exposed in the interface (the type is the id for an object
that implements the `MTLTexture` …
=> Add a method to render targets and cameras to retrieve a Metal texture

ogre2/src/Ogre2GpuRays.cc
Metal does not support `RGB32_FLOAT` format, see https://github.com/ignitionrobotics/ign-rendering/issues/461#issuecomment-940938065.
So switching to use supported texture formats:
* `cubeUVTexture`: `RGB32_FLOAT` -> `RGBA32_FLOAT`
* `firstPassTextures`: `RGB32_FLOAT` -> `RG32_FLOAT`
* `secondPassTexture`: `RGB32_FLOAT` -> `RGBA32_FLOAT` 
* note: this can also be `RG32_FLOAT` to save some memory
=> Update internal texture formats used by gpu lidar

ogre2/src/media/materials/scripts/depth_camera.material, ogre2/src/media/materials/scripts/gpu_rays.material
The `time` param declared in the ogre2 material scripts are no longer used in the shaders.
Here are the corresponding shaders. You can see that there are no uniforms called `time`:
[gpu_ray_1st_pass_fs.glsl](https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering4/ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl) - `time` removed in #388
[depth_camera_fs.glsl](https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering4/ogre2/src/media/materials/programs/depth_camera_fs.glsl) - `time` was probably never used.
=> Remove unused time var in material scripts

include/ignition/rendering/base/BaseAxisVisual.hh, ogre/src/OgreVisual.cc, ogre2/src/Ogre2Visual.cc
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/1105/
A couple of these nullptr checks were needed by https://github.com/ignitionrobotics/ign-gazebo/pull/1105/. While at it, I also went over `Ogre2Visual` and `OgreVisual`, added more nullptr checks, and reduced the diff between them.
=> More nullptr checking on visuals and base axis

examples/segmentation_camera/GlutWindow.cc, examples/thermal_camera/GlutWindow.cc, ogre/include/ignition/rendering/ogre/OgreCamera.hh, ogre/include/ignition/rendering/ogre/OgreDepthCamera.hh, ogre/include/ignition/rendering/ogre/OgreObjectInterface.hh, ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh, ogre/include/ignition/rendering/ogre/OgreThermalCamera.hh, ogre/src/OgreCamera.cc, ogre/src/OgreDepthCamera.cc, ogre/src/OgreObjectInterface.cc, ogre/src/OgreRayQuery.cc, ogre/src/OgreThermalCamera.cc, ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh, ogre2/include/ignition/rendering/ogre2/Ogre2DepthCamera.hh, ogre2/include/ignition/rendering/ogre2/Ogre2ObjectInterface.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh, ogre2/include/ignition/rendering/ogre2/Ogre2SegmentationCamera.hh, ogre2/include/ignition/rendering/ogre2/Ogre2ThermalCamera.hh, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2ObjectInterface.cc, ogre2/src/Ogre2RayQuery.cc, ogre2/src/Ogre2SegmentationCamera.cc, ogre2/src/Ogre2ThermalCamera.cc
Fixes #414
This PR enables depth, segmentation and thermal cameras to set a ray query for the `ogre` and `ogre2` render engines.
The approach Introduces mix-in classes to provide access to underlying Ogre objects in the `OgreCamera` / `Ogre2Camera` and related camera classes.
Update the mouse handling in the `segmentation_camera` and `thermal_camera examples`.
=> Enable ray query for depth, segmentation and thermal cameras

include/ignition/rendering/base/BaseCamera.hh, include/ignition/rendering/base/BaseRenderTarget.hh
This should fix a couple of Windows build warnings found by CI:
```
'*/' found outside of comment (compiling source file C:\Jenkins\workspace\ign_rendering-pr-win\ws\ign-rendering\ogre\src\OgreCamera.cc)
```
=> Fix warnings on Windows

ogre2/src/media/materials/programs/Metal/depth_camera_final_fs.metal, ogre2/src/media/materials/programs/Metal/selection_buffer_fs.metal
Apply #446 to Metal shaders
This PR applies #446 to Metal shaders and updates them to use the Metal equivalent of OpenGL's `texelFetch` (which is `texture.read()`). Previously the depth camera and selection buffer Metal shaders were using a standard texture sampler accepting normalised coordinates and ignored the texture resolution uniform parameter.
Currently there are no automated tests for the Metal shaders. Tested manually using the `ogre2demo` and `mouse_picking` examples and also `ign gazebo` (by cherry-picking this change into `main` to build the gui and gazebo libraries). 
=> Update Metal depth camera and selection buffer shaders to match #446

ogre2/src/Ogre2Material.cc
Partial fix for #499 
When porting to ogre 2.2, lightmap and emissive map share the same texture slot. The fix adds a check to make sure we don't accidentally clear the emissive map when clearing out the lightmap texture.
There is still an issue of using grayscale emissive maps, in ogre2.2 it's being treated as RGB and so it's rendered red. This needs to be fixed next.
=> Partial fix for emissive map

include/ignition/rendering/RayQuery.hh, include/ignition/rendering/base/BaseRayQuery.hh, ogre/include/ignition/rendering/ogre/OgreRayQuery.hh, ogre/src/OgreRayQuery.cc, ogre2/include/ignition/rendering/ogre2/Ogre2RayQuery.hh, ogre2/src/Ogre2RayQuery.cc
This bug had been annoying me for months for which I silenced those asserts.
But given that I need to implement `SCENE_STATIC` to get global illumination going, it is dangerous to ignore those asserts so I had to fix this.
ign-rendering would assert (inside a debug build of Ogre2) every time the mouse hovers the GUI.
This PR changes both API and ABI. Technically speaking what ign-rendering was doing was wrong but it didn't seem to matter too much (if at all); which is why I don't care to break API/ABI without backporting.
If this fix makes it into Fortress then great, otherwise it's not a big deal. Ideally ogre2 fork should include [this fix](https://github.com/OGRECave/ogre-next/commit/e7f3d114102e125ab599346aa3dd4b722a9fac07) we added to 2.3 and that I just backported to 2.2; but again …
=> Fix Ogre2 assertions during ray queries

ogre2/include/ignition/rendering/ogre2/Ogre2DynamicRenderable.hh, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2DynamicRenderable.cc, ogre2/src/Ogre2LidarVisual.cc, ogre2/src/Ogre2Marker.cc, ogre2/src/Ogre2RayQuery.cc, ogre2/src/Ogre2SelectionBuffer.cc, ogre2/src/media/materials/programs/GLSL/point_fs.glsl, ogre2/src/media/materials/programs/GLSL/point_vs.glsl, ogre2/src/media/materials/programs/GLSL/selection_buffer_fs.glsl, ogre2/src/media/materials/scripts/selection_buffer.material, src/Utils.cc, src/Utils_TEST.cc, test/integration/camera.cc, test/integration/scene.cc
* Part of https://github.com/ignitionrobotics/ign-gazebo/issues/1156
* Needed by https://github.com/ignitionrobotics/ign-gui/pull/318
We have been populating the `colors` vector in `Ogre2DynamicRenderable`, but not using the colors for anything.
For most dynamic renderables, we fill the vertex buffer with position and normal. But points don't have normals, so we've been leaving half the buffer empty. The implementation on this PR takes advantage of those empty slots to place per-point colors (only RGB, no A).
Thanks @WilliamLewww for helping me out with this!
The marker example on https://github.com/ignitionrobotics/ign-gui/pull/318 uses this:
=> Per-point colors in point clouds

ogre2/src/Ogre2Material.cc, ogre2/src/media/materials/programs/Metal/depth_camera_final_fs.metal, ogre2/src/media/materials/programs/Metal/selection_buffer_fs.metal
Port `ign-rendering6` to `main`
Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/main...ign-rendering6
=> 6 ➡️ 7 (main)

ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2LidarVisual.cc, ogre2/src/Ogre2Marker.cc, ogre2/src/Ogre2ThermalCamera.cc
fixes issue found in this comment: https://github.com/ignitionrobotics/ign-gui/pull/323#issuecomment-989142005
Now that here is support for more than just OpenGL graphics API, we should check that the OpenGL render system is actually in use before making GL calls.
=> Check for OpenGL backend before calling GL APIs

ogre2/src/Ogre2RayQuery.cc, src/Utils_TEST.cc
https://github.com/ignitionrobotics/ign-rendering/pull/446 made a few fixes to selection buffer for mouse picking and got the tests to pass but it didn't remove [the code](https://github.com/ignitionrobotics/ign-rendering/pull/447) that disabled this feature. So currently mouse pickin is still based on the triangle intersection based method.
This PR enables ray queries using selection buffer in ogre2 again. I brought [this commit](https://github.com/ignitionrobotics/ign-rendering/commit/bfb22fb1f9bee5643c4407ae05ec24857c200bbf#) back to fix the Utils test.
run the fortress demo world and mouse orbit control should be smoother.
```
ign gazebo -v 4 -r "https://fuel.ignitionrobotics.org/1.0/OpenRobotics/worlds/Fortress demo"
```
**Note to …
=> Enable selection buffer based ray query (ogre2)

ogre2/src/Ogre2Material.cc
I could not find info online about this problem, so i had to write a
test myself.
The obvious solution is to multiply the depth bias by 100 or so; but I
was wondering what would be the side effects on other geometry.
I.e. what would happen to geometry that is meant to be in front of the
plane? We know a depth bias of 300 works at close range at reverse Z
(where at normal Z a depth bias of 3 was enough), but would the plane
get on top of everything as you move the camera away?
So I made a test: https://www.youtube.com/watch?v=s2XdH3fYUac
We can safely multiply by something like 100 or so, and we will get
better results with reverse Z than we could with normal Z + the usual
depth bias constant scale.
With Normal Z, wven with a depth bias of 3 will eventually be on top of
everything, but …
=> RenderOrder is in different scale in Reverse Z

ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/media/materials/programs/GLSL/depth_camera_fs.glsl, ogre2/src/media/materials/programs/Metal/depth_camera_fs.metal
Updated shaders so that it does not incorrectly assume that the background is just a plain color.
Added a todo note about doing coming up with a better way of doing manual clipping of color values.
To test:
You can test with this world: [sensor_particles.sdf](https://gist.github.com/iche033/26888ed86b27f824e5979c385ea393f1) world file.
```
ign gazebo -v 4 sensor_particles.sdf
```
You should see that the RGBD camera now shows the sky background in the `RGBD: image` Image Display plugin.
=> Fix sky background in RGBD camera

ogre2/src/Ogre2DynamicRenderable.cc
* Follow up to #494 
On #494 I had skipped filling the rest of the buffer for points because that was adding multiple points to the end of the cloud with the color blue. What I didn't notice is that I swapped the "last blue points" for "extra black point at the origin" :upside_down_face: 
* "last blue points" issue: the end of the vertex buffer is filled with points that have a Z normal (0,0,1 : blue) and coincide with the last point
* "extra black point at the origin": if the vertex buffer isn't filled completely with points, it's filled with zeroes (origin position, black color)
The  solution here is to first fill the buffer with blue normals, then override that with the color of the last point. I did this to match the implementation for other markers and reduce the amount of code …
=> Fix color of last / extra marker points

.github/ci/packages.apt, CMakeLists.txt, examples/depth_camera/CMakeLists.txt, include/ignition/rendering/LidarVisual.hh, include/ignition/rendering/Marker.hh, include/ignition/rendering/Scene.hh, include/ignition/rendering/base/BaseCamera.hh, include/ignition/rendering/base/BaseJointVisual.hh, include/ignition/rendering/base/BaseScene.hh, src/OrbitViewController.cc, src/OrthoViewController.cc, src/TransformController.cc, src/base/BaseScene.cc, tutorials/02_install.md, tutorials/23_depth_camera_tutorial.md
See https://github.com/ignition-tooling/release-tools/issues/574
=> Bumps in garden: use ign-common5, ign-math7

examples/custom_shaders_uniforms/GlutWindow.cc, examples/custom_shaders_uniforms/Main.cc, examples/custom_shaders_uniforms/media/fragment_shader.glsl, examples/custom_shaders_uniforms/media/fragment_shader_330.glsl, examples/custom_shaders_uniforms/media/vertex_shader.glsl, examples/custom_shaders_uniforms/media/vertex_shader_330.glsl, ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2Mesh.cc, src/ShaderParam.cc
Implemented code to supported loading custom shader material and updating their uniform variables.
Extended the `custom_shaders_uniforms` to run with ogre2 render engine. Note I made a slight tweak to the shader code in the demo to make the ogre 1.x and ogre 2.x behavior more consistent. When running with `ogre2`, the clip space z pos returned by `gl_Position.z` is different from `ogre` so it was rendering slightly different visual effect.
To test:
build and run the [custom_shaders_uniforms](https://github.com/ignitionrobotics/ign-rendering/tree/dc4e4c1f480e109bd9b15920300d2c9e49796f36/examples/custom_shaders_uniforms) demo:
```
./custom_shaders_uniforms ogre2
```
=> Support using custom shader materials and updating uniform variables (ogre2)

ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2SelectionBuffer.cc
No ticket created
Ignition is pointlessly performing two passes when one is enough, as the
depth buffer data is already filled.
In the case of `Ogre2DepthCamera` we cannot do the same with
colorTexture & depthTexture though; because the way they are filled is different (colorTexture contains particles
and potentially other stuff that might write to depth; depthTexture doesn't)
=> Performance optimization by avoiding unnecessary passes

ogre2/src/Ogre2ThermalCamera.cc
The depth buffer is created but never filled with anything.
As a result it contains uninitialized values (likely 0.0f but it's not
guaranteed)
This bug seems to have been introduced when ported to Ogre 2.2
No ticket created for this
=> Fix Ogre2ThermalCamera using garbage depth data

ogre2/src/Ogre2GpuRays.cc
There were multiple bugs that had to be fixed:
- Objects which had no laser_retro set (or an invalid one) would be
rendered using regular lighting PBS shaders; causing the retro value to
contain garbage instead of the intended default value of 0
- Performance regression in 993bb0bff6792627fe1f0cc19108d7280f369da1:
When ported to Ogre 2.2, ignition would render the scene 4 times instead
of 2 (twice for objects, twice for particles). Depth buffer data was
created through a 2nd redundant pass. This is inefficient as the depth
buffer data is already available from the 1st pass
- Bug regression in 993bb0bff6792627fe1f0cc19108d7280f369da1: In the
pass for normal objects, ignition would first use IGN_VISIBILITY_ALL
flags for colour, but it would use 0x01000000 for depth. This creates
the wrong …
=> Fix various issues with Ogre2GpuRays

ogre2/src/Ogre2GpuRays.cc, test/integration/gpu_rays.cc
A follow up to #522. Retro values for objects that do not have anything set should now return zero. Added a check and remove todo comment.
=> Add test case for zero retro value

CMakeLists.txt
* Fixes #360
Calling `cmake_policy` is complicated in this situation because the `find_package` call is made in a different scope, within `ign_find_package`. Setting the variable directly does the trick though. See https://github.com/ignitionrobotics/ign-rendering/issues/360#issuecomment-1006278927.
This doesn't solve the problem for downstream projects though. I didn't find a way of passing variables to [ignition-component-config.cmake.in](https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/cmake/ignition-component-config.cmake.in).
=> Silence CMake policy CMP0072

examples/custom_shaders_uniforms/GlutWindow.cc, examples/custom_shaders_uniforms/media/vertex_shader_330.glsl, ogre2/src/Ogre2Material.cc
Ogre provides a few constants that are useful when writing shaders:
https://github.com/OGRECave/ogre-next/blob/v2-2/OgreMain/src/OgreGpuProgramParams.cpp#L43-L196
This PR binds these constants to named uniforms so that they can be accessed by the shaders. I also removed the hardcoded uniform that I introduced in #520. 
Updated the `custom_shader_uniforms` demo to show how to bind a uniform to one of these constants.
To test, run the `custom_shader_uniforms` example to make sure nothing is broken.
=> Bind shader uniforms to constants from ogre

ogre2/src/media/materials/scripts/depth_camera.material, ogre2/src/media/materials/scripts/selection_buffer.material
Follow up to #498
This fix adds default parameters to the Metal fragment shader definitions in the depth camera and selection buffer materials.
A depth camera would not render correctly (black screen) on macOS using Metal shaders. This can be reproduced either using the `depth_camera` example or by including a depth_camera sensor in a SDF model and displaying the image in Gazebo.
After the PR the `depth_camera` example and Image display are working correctly.
=> [Metal] Fix depth camera sensor 

ogre2/src/media/Hlms/Terra/GLSL/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.glsl, ogre2/src/media/Hlms/Terra/HLSL/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.hlsl, ogre2/src/media/Hlms/Terra/Metal/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.metal
Hovering the cursor while in the ign gui when heightmap.sdf is opened
would cause a shader compiler error.
The triggering condition was having a directional light without shadow
nodes.
This error is from upstream
https://github.com/OGRECave/ogre-next/commit/e40bc539092ec64fc75153a50033dbb8a7da2857
No ticket was assigned for this bug
=> Fix crash when hovering the cursor in heightmap.sdf

ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2IgnHlmsPbsPrivate.cc, ogre2/src/Ogre2IgnHlmsPbsPrivate.hh, ogre2/src/Ogre2IgnHlmsSphericalClipMinDistance.cc, ogre2/src/Ogre2IgnHlmsSphericalClipMinDistance.hh, ogre2/src/Ogre2IgnHlmsUnlitPrivate.cc, ogre2/src/Ogre2IgnHlmsUnlitPrivate.hh, ogre2/src/Ogre2RenderEngine.cc
This is part of ticket #502
In order to split the amount of changes into maneagable, reviewable changes; the changes are being submitted in 3 PRs.
This is the 2nd PR.
It simply renames Ogre2IgnHlmsCustomizations to Ogre2IgnHlmsSphericalClipMinDistance.
The reason behind this is that customizations are now being managed by Ogre2IgnHlmsPbs & Ogre2IgnHlmsUnlit.
Since Ogre2IgnHlmsCustomizations is doing just one job but has a generic name, it would tend to confusion as to what it does and its role.
The class isn't exposed to the user; however `Ogre2RenderEngine::HlmsCustomizations` did expose a forward declared pointer to the user; which is why the function still exists but has been marked as deprecated.
Affects #502 
**Note to …
=> Rename Ogre2IgnHlmsCustomizations to Ogre2IgnHlmsSphericalClipMinDistance

ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2RenderEngine.cc
No ticket assigned; but it was mentioned in https://github.com/ignitionrobotics/ign-rendering/pull/536#issuecomment-1015813281
Issue was incorrect listener setup due to bad merge.
ign-rendering7 has a more robust system to handle all listeners. For
Fortress this fix will do.
Garden will already have a better fix after PR #545 is merged.
The code that should not be carried over to Garden was surrounded by `#ifdef` macros and an assert was placed. Hopefully that will help reducing merge conflict mistakes.
=> Fix missing terrain shadows casted on objects

ogre2/src/media/materials/programs/Metal/depth_camera_fs.metal
Follow up to #515
This fix updates the `depth_camera_fs.metal` shader to scope the new parameter `hasBackground` correctly.
```bash
ign gazebo depth_camera_sensor.sdf
```
The example provided in #515 is not yet working on Metal due to another issue.  
=> [Metal] Fix sky background in RGBD camera to match #515

ogre2/src/media/materials/programs/GLSL/point_fs.glsl, ogre2/src/media/materials/programs/Metal/point_fs.metal, ogre2/src/media/materials/programs/Metal/point_vs.metal, ogre2/src/media/materials/scripts/point_cloud_point.material
Follow up to #494 
This fix applies changes proposed by @iche033 to update Metal shaders that were missed from the merged PR.
It is a cherry-pick of 5df748eb48cff2fb60b544501da6afcdd5a8ec28
=> [Metal] Fix per-point colors in point clouds to match #494

ogre2/include/ignition/rendering/ogre2/Ogre2IgnOgreRenderingMode.hh, ogre2/include/ignition/rendering/ogre2/Ogre2MaterialSwitcher.hh, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2IgnHlmsPbsPrivate.cc, ogre2/src/Ogre2IgnHlmsTerraPrivate.cc, ogre2/src/Ogre2IgnHlmsTerraPrivate.hh, ogre2/src/Ogre2MaterialSwitcher.cc, ogre2/src/Ogre2RenderEngine.cc, ogre2/src/Ogre2SegmentationCamera.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.hh, ogre2/src/Ogre2ThermalCamera.cc, ogre2/src/media/Hlms/Ignition/SolidColor/800.IgnSolidColor_piece_ps.any, ogre2/src/media/Hlms/Terra/ign/100.ign_CustomVs_piece_vs.any, ogre2/src/media/Hlms/Terra/ign/500.ign_Structs_piece_all.any, ogre2/src/terrain/Terra/include/Terra/Hlms/OgreHlmsTerra.h, ogre2/src/terrain/Terra/include/Terra/Terra.h, ogre2/src/terrain/Terra/src/Terra.cpp
Fixes #504
Fixes #444
The 3rd and final PR to ticket #504 !
After this PR:
- Terra now works with all Cameras (Thermal, SelectionBuffer, Segmentation, Laser) as documented in ticket #444 (backporting this to Fortress w/out breaking ABI could be a ton of work unfortunately)
- Fixes various misc bugs of wrong values used in these cameras by regular objects when their properties weren't set (documented in #521, technically it fixes that one, but the fix can be backported so the ticket can will open until these versions are fixed or EoL)
- Deformation works correctly under these cameras (e.g. skeletal animation and morph target)
- Only exception is Thermal camera when using `heatSignature` texture. This was not ported to Hlms pieces and we remain swapping a regular low level material
- Swaps …
=> Implement Hlms custom pieces swap for Objects & Terrain

examples/custom_shaders_uniforms/Main.cc, examples/custom_shaders_uniforms/media/fragment_shader.metal, examples/custom_shaders_uniforms/media/vertex_shader.metal, ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2RenderEngine.cc
This PR adds metal shaders to the custom_shaders_uniforms example.
Enhances #520
- Metal vertex and fragment shaders are added to the custom_shaders_uniforms example.
- `Ogre2Material` is modified to specify the render system being used when creating the GPU programs.
- Add an accessor for the graphics API to `Ogre2RenderEngine`
Run the example using `ogre2` and specifying `metal` as the graphics API:
```bash
./custom_shaders_uniforms ogre2 metal
```
=> [Metal] update custom_shaders_uniforms example

examples/waves/CMakeLists.txt, examples/waves/GlutWindow.cc, examples/waves/Main.cc, examples/waves/media/GerstnerWaves_fs.metal, examples/waves/media/GerstnerWaves_vs.metal, ogre2/src/Ogre2Material.cc
This PR adds metal shaders to the waves example.
Enhances #541
- Metal vertex and fragment shaders are added to the waves example.
- Depends on `ogre2` render engine changes in #554 
Run the example using ogre2 and specifying metal as the graphics API:
```bash
./waves ogre2 metal
```
For further details on the implementation at see the discussion in #541
=> [Metal] update waves example

examples/waves/GlutWindow.cc, examples/waves/Main.cc
Backport some minor changes from #555:
* removed unused variable
* fixed variable names
* adjusted wave amplitude and camera z pos
=> Backport wave changes

ogre2/src/Ogre2Material.cc, test/integration/camera.cc
Fixes crash when setting a shader parameter that does not exist. Now it prints out a warning msg to let users know what param will not be set.
=> Make sure shader param exists before setting its value

ogre2/src/Ogre2Conversions.cc, ogre2/src/Ogre2RenderTarget.cc
No ticket has been associated with this issue
When ignition moved to Ogre 2.2+; `Ogre2RenderTarget::Copy` lost the ability to convert between src & dst formats. This PR restores it.
It also should be faster because we avoid an unnecessary extra copy.
Additionally, `Ogre2Conversions::ogrePixelFormats` had a missing entry which could trigger bugs if the not-so-popular `PF_R8G8B8A8` format is used
=> Restore format conversion in Ogre2RenderTarget::Copy

ogre2/src/Ogre2RenderEngine.cc
Fixes https://github.com/ignitionrobotics/ign-gazebo/issues/1270
Currently, when running headless mode, an error `[Err] [Ogre2RenderEngine.cc:394] Unable to open display: ` is emitted in `ign-gazebo` even though rendering continues to work as expected. I think this is a false alarm and can be removed.
Also, currently, when a display is not found in non-headless mode, there is an error emitted saying "Unable to open display". I changed this to a warning since rendering continues to work if headless mode succeeds.
=> Remove unnecessary error message when headless rendering is enabled

include/ignition/rendering/RenderEngine.hh, include/ignition/rendering/base/BaseRenderEngine.hh, ogre/include/ignition/rendering/ogre/OgreRenderEngine.hh, ogre/src/OgreRenderEngine.cc, ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2RenderEngine.cc
There's no ticket assigned to this issue.
The current GraphicsAPI is only available at Ogre2RenderEngine level, which is problematic when we want to be aware of it for multiple means.
ign-gui needs this information so it can decide on how to interface the API with Qt.
In some cases initialization may need additional steps if different APIs are used; so this info is needed.
=> Expose GraphicsAPI

ogre/src/OgreRTShaderSystem.cc
Signed-off-by: William Lew <WilliamMilesLew@gmail.com>
This backports a OgreRTShaderSystem segfault fix main to ign-rendering6.
=> Backport #563

ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2RenderTarget.cc
Fixes  https://github.com/ignitionrobotics/ign-rendering/issues/568
When sky is enabled, we are clearing the existing scene with objects in render queue 0, 1. We didn't notice any issue because, as pointed out, we don't have any objects that occupy those render queue. This PR implements the fix suggested in Implemented suggested fix from https://github.com/ignitionrobotics/ign-rendering/issues/568.
The bug was introduced in https://github.com/ignitionrobotics/ign-rendering/pull/440, which was done to fix flickering issues. It is difficult to add a test for this PR since we don't have features in ign-rendering that are in those render queues. One way to test this is to launch ign gazebo Fortress Demo world and make sure that this does not …
=> Fix sky background compositor setup

include/ignition/rendering/base/BaseCamera.hh, include/ignition/rendering/base/BaseJointVisual.hh, include/ignition/rendering/base/BaseNode.hh
Part of https://github.com/ignitionrobotics/ign-math/issues/60
The ign-math Pose addition operator is going to be deprecated, so use the multiplication operator instead. It works in the opposite order, matching the behavior of coordinate transform multiplication. The deprecation is planned for ignition-math7, which will not affect Fortress, but I've targeted this branch to reduce the chance of conflicts when merging forward.
=> Use pose multiplication instead of addition

ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2RenderEngine.cc
This should fix the `waves` demo on macOS using ogre2 + metal. See https://github.com/ignitionrobotics/ign-rendering/pull/558#issuecomment-1056889775
I also had to backport the `GraphicsAPI` accessor function from https://github.com/ignitionrobotics/ign-rendering/pull/554
Waves demo now working again on macOS:
=> Do not set shader constants for textures on non-OpenGL graphics API

ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2MaterialSwitcher.cc, test/integration/camera.cc
The gpu ray sensor sets up generates retro values by switching materials. The probably is that it incorrectly restores shader materials causing objects using custom shaders to render incorrectly after first update.
Applied a similar fix as as https://github.com/ignitionrobotics/ign-rendering/pull/533. Updated integration test should which fail without this fix.
On way to reproduce the issue is to run this [shader_param_gpu_lidar.sdf](https://gist.github.com/iche033/e74b66edcf4a95554b6a015c72cba2b7) world with ign-gazebo:
```
ign gazebo -v 4 -r shader_param_gpu_lidar.sdf
```
Without this fix, the red sphere and waves (which use custom shaders) will appear black in the `Image Display` plugin.
**Note to maintainers**: Remember to use …
=> Fix objects using shaders when there is a lidar in the scene (ogre2)

examples/render_pass/Main.cc
Running the [render_pass](https://github.com/ignitionrobotics/ign-rendering/tree/ign-rendering6/examples/render_pass) example with `ogre2` currently results in a crash because it tries to load the distortion render pass which has not been ported to ogre2 implementation yet.
This PR adds a check to make sure the render pass is not null before adding it to the render pass system.
to test, build and run the `render_pass` example:
```
./render_pass ogre2
```
=> Fix render pass example on ogre2

ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2MaterialSwitcher.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.cc, ogre2/src/Ogre2ThermalCamera.cc
Fixes #544 
It implements the first option (clone the material with same VS but different PS).
However I could NOT test this PR because I had no test nor sample to test it.
That is the reason this PR is marked as draft. I would appreciate a way to play with this (i.e. a low level material entity being drawn in all sensors).
The lack of tests is tracked by #543
=> Respect vertex shader from low level materials in sensor passes (#544)

ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2MaterialSwitcher.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.hh, ogre2/src/Ogre2ThermalCamera.cc, test/integration/camera.cc
Follow-up to #https://github.com/ignitionrobotics/ign-rendering/pull/575 and [these comments](https://github.com/ignitionrobotics/ign-rendering/commit/dd8b465384315eb8ed198446c8aeeb37ded60125#comments)
This PR fixes objects with shader material when there is a thermal camera or a segmentation camera in the scene. These sensor all perform material switching during a render update, and the shader materials should now be correctly restored. Also updated test.
Here is a [shader_param_sensors.sdf]( https://gist.github.com/iche033/01ef166ed150d0b0046daa8176de5640) for testing with ign-gazebo. The cameras should produce correct output and the waves and deformable sphere should be render correctly in the GUI and camera and depth sensors. 
Note …
=> Fix shaders for other sensors that require material switching (ogre2)

examples/heightmap/Main.cc, include/ignition/rendering/HeightmapDescriptor.hh, ogre2/src/Ogre2Heightmap.cc
* Closes #508 
* Builds on top of #560 
The Ogre 2 implementation was incorrectly multiplying the final size by the height difference for Z, which resulted on extremely tall heightmaps. According to the [SDF spec](http://sdformat.org/spec?ver=1.9&elem=geometry#heightmap_size), the size is meant to represent the final size of the heightmap; it's not a scaling factor. Gazebo [passes](https://github.com/ignitionrobotics/ign-gazebo/blob/f5bb284884de9c5d4d7fa5614e53b528654b6611/src/rendering/SceneManager.cc#L705) the SDF's size straight to the `HeightmapDescriptor`'s size.
With this change, the DEMs introduced in #560 have the same size across Ogre 1 and 2. I also verified that the image-based heightmaps aren't affected.
Ogre | Ogre 2
-- | --
**Note to maintainers**: Remember to use …
=> [ogre2] Fix heightmap height and update docs

ogre2/src/Ogre2Material.cc
Fix issue for macOS / Metal introduced in #578
#578 introduced an error on macOS / Metal for a number of examples where the parameters for the pixel shader
could not be set because the reflection pair hint was not available. This PR moves the block of code causing the issue to after the vertex shader has been created and reflection pair hint has been set.
See comment here: 
- https://github.com/ignitionrobotics/ign-rendering/pull/578#issuecomment-1069391532
Test outcome here:
- https://github.com/ignitionrobotics/ign-rendering/pull/578#issuecomment-1069652246
=> Fix for #578 on macOS / Metal

.github/ci/packages-bionic.apt, .github/ci/packages-focal.apt, .github/ci/packages-jammy.apt, .github/ci/packages.apt, .github/workflows/ci.yml, CMakeLists.txt, ogre2/src/CMakeLists.txt, ogre2/src/terrain/Terra/CMakeLists.txt
Part of https://github.com/ignition-tooling/release-tools/issues/566
Enable CI for Ubuntu 22.04 (Jammy)
=> Add Ubuntu Jammy CI

include/ignition/rendering/base/BaseCamera.hh, include/ignition/rendering/base/BaseJointVisual.hh, include/ignition/rendering/base/BaseNode.hh, ogre2/src/Ogre2Material.cc
Port ign-rendering6 as of https://github.com/ignitionrobotics/ign-rendering/commit/996c58da0cc115d8691e7ac46a4df367d1e5bcc4 to main
I tried merging the tip of `ign-rendering6`, but there are significant conflicts with main when merging forward #575 and #579, so I would request that @iche033 handle that merge.
Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/main...996c58da0cc115d8691e7ac46a4df367d1e5bcc4
=> Merge part of 6 -> main

ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2MaterialSwitcher.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.cc, ogre2/src/Ogre2ThermalCamera.cc, ogre2/src/media/materials/programs/GLSL/point_vs.glsl, ogre2/src/media/materials/scripts/picker.material, ogre2/src/media/materials/scripts/picker.program, ogre2/src/media/materials/scripts/point_cloud_point.material
No ticket was issued for this problem
This PR supersedes #586
The problem has been described in #586
This PR replaces it as it is applied to more sensors and comments explain why there can be nullptrs.
=> Don't crash if directly set low level materials are used in sensors

ogre2/src/Ogre2Scene.cc
No ticket is associated.
But there is a relevant discussion in https://github.com/ignitionrobotics/ign-rendering/issues/323#issuecomment-865413892
I thought `cameraPassCountPerGpuFlush` was already at default 6.
[ign-gazebo/src/gui/plugins/scene3d/Scene3D.cc](https://github.com/ignitionrobotics/ign-gazebo/blob/39a0ce3712580e855838cf7557013a262d42e1a1/src/gui/plugins/scene3d/Scene3D.cc#L2126) should already be setting this value on the GUI side.
Same goes for [ign-gazebo/src/systems/sensors/Sensors.cc](https://github.com/ignitionrobotics/ign-gazebo/blob/39a0ce3712580e855838cf7557013a262d42e1a1/src/systems/sensors/Sensors.cc#L239)
I don't want to think of the implications of setting this value to 6 on already released versions. It's probably harmless. But anyway, the API was introduced in …
=> Default cameraPassCountPerGpuFlush to 6

Migration.md, ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh, ogre2/src/Ogre2Scene.cc, src/Scene_TEST.cc, src/base/BaseScene.cc, test/integration/camera.cc, test/integration/depth_camera.cc, test/integration/gpu_rays.cc
Fixes #556
This fixes Particle FXs not respecting simulation time.
After researching Ogre behavior, turns out we already had the functionality to use custom simulation (deterministic) time. We just had to use it. Turned out to be much easier than I expected (I actually started writing more code until I realized it... :( )
**Note:** This is a draft because I was unsure _where to pull gazebo's simulation time from_. Therefore it is currently hardcoded with:
```cpp
static const Ogre::Real kSimulationTime = Ogre::Real(1.0 / 60.0);
```
and obviously needs to be changed to use gazebo's.
But other than that, once that's implemented (I'm asking for pointers here....!) it should just work.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull …
=> Use custom simulation time variants for Ogre

ogre/src/OgreHeightmap.cc
From gazebo-classic
* https://github.com/osrf/gazebo Separate cache files for each heightmap LOD/pull/3200
To prevent gazebo from loading the wrong cache files, each heightmap LOD will have its own set of cache files.
The LOD is appended to the cache files' names (_5_ in the example):
```
[Msg] Loading heightmap cache data: /root/.gazebo/paging/heightmap_bowl_2/gazebo_terrain_5_00000000.dat
[Msg] Loading heightmap cache data: /root/.gazebo/paging/heightmap_bowl_2/gazebo_terrain_5_00010000.dat
[Msg] Loading heightmap cache data: /root/.gazebo/paging/heightmap_bowl_2/gazebo_terrain_5_00000001.dat
[Msg] Loading heightmap cache data: /root/.gazebo/paging/heightmap_bowl_2/gazebo_terrain_5_00010001.dat
```
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to …
=> Separate cache files for each heightmap LOD

ogre/src/OgreMeshFactory.cc, ogre2/src/Ogre2MeshFactory.cc, optix/src/OptixMeshFactory.cc
Signed-off-by: Ashton Larkin <42042756+adlarkin@users.noreply.github.com>
This PR replaces deprecated calls to `ignition::common::SubMesh::MaterialIndex()` with the new `GetMaterialIndex()` method that was introduced in https://github.com/ignitionrobotics/ign-common/pull/319.
=> Replace deprecated common::SubMesh::MaterialIndex() with GetMaterialIndex()

ogre/include/ignition/rendering/ogre/OgreIncludes.hh, ogre/include/ignition/rendering/ogre/OgreMaterialSwitcher.hh, ogre/src/OgreRenderTarget.cc, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2RenderEngine.cc, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/Ogre2Scene.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.cc, ogre2/src/Ogre2ThermalCamera.cc
Fixes windows build warnings, #621
For the ogre1.x windows warnings, the pragma: `#pragma warning(push, 0)`  does not seem to suppress the warnings any more so I added more pragmas that explicitly disables the specific warnings
=> Fix Windows warnings

ogre2/src/Ogre2DepthCamera.cc
A follow up to https://github.com/gazebosim/gz-rendering/pull/617 - now that we are actually destroying sensors properly, I noticed a crash when running the  depth camera integration test in ign-sensors. This should fix the crash (fix is similar to the changes done in #617)
=> Cleanup depth camera resources on destroy

src/Heightmap_TEST.cc
* Part of https://github.com/gazebosim/gz-cmake/issues/171
The utilities from `gz-cmake` are deprecated.
=> Use gz-utils test macros

Migration.md, ogre2/include/gz/rendering/ogre2/Ogre2GzOgreRenderingMode.hh, ogre2/include/gz/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2GzHlmsPbsPrivate.cc, ogre2/src/Ogre2GzHlmsPbsPrivate.hh, ogre2/src/Ogre2GzHlmsSharedPrivate.cc, ogre2/src/Ogre2GzHlmsSharedPrivate.hh, ogre2/src/Ogre2GzHlmsSphericalClipMinDistance.cc, ogre2/src/Ogre2GzHlmsSphericalClipMinDistance.hh, ogre2/src/Ogre2GzHlmsTerraPrivate.cc, ogre2/src/Ogre2GzHlmsTerraPrivate.hh, ogre2/src/Ogre2GzHlmsUnlitPrivate.cc, ogre2/src/Ogre2GzHlmsUnlitPrivate.hh, ogre2/src/Ogre2RenderEngine.cc, ogre2/src/media/Hlms/Ignition/Pbs/500.IgnPbsStructs_piece_all.any
See: https://github.com/gazebo-tooling/release-tools/issues/711
=> ign -> gz File Move for IgnHlms

ogre/include/ignition/rendering/ogre/OgreCamera.hh, ogre/src/OgreCamera.cc, ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh, ogre2/src/Ogre2Camera.cc, src/Camera_TEST.cc
Signed-off-by: youhy <haoyuan2019@outlook.com>
Original Issue: #500
`Camera::HFOV()` only returned a fixed value previously. Now it should change as we resize the window and change FOV at runtime. 
My VM can only run Ogre so I need someone to help me test this on Ogre2.
Draft because it fails too many tests
=> Camera::HFOV override for Ogre and Ogre2

include/gz/rendering/base/BaseNode.hh
Part of [gz-math#60](https://github.com/gazebosim/gz-math/issues/60).
As noted in [gz-math#60](https://github.com/gazebosim/gz-math/issues/60), there are concerns about the pose subtraction operator. Given that it is equivalent to multiplying by an inverse (albeit with reversed order), the subtraction operator will be deprecated. This PR replaces usage of the soon-to-be-deprecated operator with the equivalent multiplication by inverse.
Build against https://github.com/gazebosim/gz-math/pull/438 and confirm that tests still pass and that there are no deprecation warnings.
=> Use pose multiplication instead of subtraction

Migration.md, examples/hello_world_plugin/README.md, ogre/src/OgreDepthCamera.cc, ogre/src/OgreMaterial.cc, ogre/src/OgreRTShaderSystem.cc, ogre/src/OgreRenderEngine.cc, ogre2/src/Ogre2RenderEngine.cc, optix/src/OptixRenderEngine.cc, src/base/BaseScene.cc, tutorials/03_rendering_plugins.md
See: https://github.com/gazebo-tooling/release-tools/issues/734
Actually no environment variables need to be migrated (though how it's been implemented means there isn't really a way to emit warnings...)
They were implemented like so in the namespace migration:
```
const char *env = std::getenv("GZ_RENDERING_RESOURCE_PATH");
env = (env) ? env : std::getenv("IGN_RENDERING_RESOURCE_PATH");
```
=> ign -> gz Environment Variable Migration : gz-rendering

include/ignition/rendering/base/BaseCamera.hh, ogre/src/OgreCamera.cc, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2ThermalCamera.cc, src/Camera_TEST.cc
Fixes ignition crash bug introduced in [gz-sim#1499](https://github.com/gazebosim/gz-sim/pull/1499)
gz-sim#1499 adds a feature to change the FOV of the user camera at runtime. But if we scale the window after changing the FOV, Gazebo has a chance to crash. (Always crash on Ogre, sometimes crash on Ogre2)
Changing `aspect` to `AspectRatio()` in `OgreCamera::SetHFOV()` solves the bug. 
Also add comment to warn users not to use `aspect` in `BaseCamera` but to use `OrgeCamera::AspectRatio()` instead.
[Resizing the window](https://github.com/gazebosim/gz-gui/blob/5c096882eb2e7a3bd120983a627cf80da66064b6/src/plugins/minimal_scene/MinimalScene.cc#L292) needs the correct aspect ratio value. There are 2 aspect ratio values available: one in Ogre library (`AspectRatio()`), and the other is in …
=> Change aspect to AspectRatio()

src/Utils.cc
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
Fixes #170 (on Citadel)
Forces scale factor to be 1.0, partial backport of #446
=> Force scaling factor to be 1.0

include/ignition/rendering/base/BaseNode.hh, ogre2/src/Ogre2RayQuery.cc, src/OrbitViewController.cc
While debugging https://github.com/gazebosim/gz-sim/pull/1499#pullrequestreview-1009122496, I noticed that GUI and Sim are often providing non-finite values to Rendering, which often results in crashes. This PR adds some guards for situations that I ran into. 
I'm going to keep investigating why downstream libraries are setting NaNs, but having the guards in place helps in any case.
=> Protect against non-finite inputs on Node and OrbitViewController

examples/waves/CMakeLists.txt
Waves example depends on `ign-common4` but it was not included.
=> Fixed waves example CMakeLists.txt

src/GraphicsAPI_TEST.cc, src/RenderPassSystem_TEST.cc, src/ShaderType_TEST.cc
Added unit tests for ShaderType, GraphicsAPI, and DistortionPass, which currently have zero or very low test coverage.
=> Add tests for ShaderType, GraphicsAPI, and DistortionPass

ogre2/include/ignition/rendering/ogre2/Ogre2Heightmap.hh, ogre2/src/Ogre2Heightmap.cc, src/Heightmap_TEST.cc
Run `Heightmap_test` with `ogre2` now that it is supported
This unfortunately reduces the overall test coverage % because various ogre1.x code is not run any more.
=> Enable ogre2 heightmap test

src/TransformController_TEST.cc
Increase test coverage to ~90%
=> Increase TransformControl test converage

examples/actor_animation/CMakeLists.txt, examples/boundingbox_camera/CMakeLists.txt, examples/camera_tracking/CMakeLists.txt, examples/custom_scene_viewer/CMakeLists.txt, examples/custom_shaders_uniforms/CMakeLists.txt, examples/depth_camera/CMakeLists.txt, examples/gazebo_scene_viewer/CMakeLists.txt, examples/heightmap/CMakeLists.txt, examples/lidar_visual/CMakeLists.txt, examples/mesh_viewer/CMakeLists.txt, examples/mouse_picking/CMakeLists.txt, examples/ogre2_demo/CMakeLists.txt, examples/particles_demo/CMakeLists.txt, examples/render_pass/CMakeLists.txt, examples/segmentation_camera/CMakeLists.txt, examples/simple_demo/CMakeLists.txt, examples/simple_demo_qml/CMakeLists.txt, examples/text_geom/CMakeLists.txt, examples/thermal_camera/CMakeLists.txt, examples/transform_control/CMakeLists.txt, examples/view_control/CMakeLists.txt, examples/visualization_demo/CMakeLists.txt, examples/waves/CMakeLists.txt
Related PR https://github.com/gazebosim/gz-rendering/pull/678 and this comment https://github.com/gazebosim/gz-rendering/pull/678#issuecomment-1190911950
Fixed CMakeLists.txt in examples. Include `ign-common4`
=> Fixed CMakeLists.txt in examples

ogre2/src/Ogre2SelectionBuffer.cc, src/RayQuery_TEST.cc
Signed-off-by: Michel Hidalgo <michel@ekumenlabs.com>
Backport #665 by cherry picking commit 8d7e008bc1170c8f3f0cca0af0eb51177860d206
Fixes issue with using ray queries from multiple cameras.
=> Backport multiple ray queries fix (#665)

CMakeLists.txt, Changelog.md
Preparation for 6.5.1 release.
Comparison to 6.5.0: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering6_6.5.0...prep_6.5.1
=> Prepare for 6.5.1 release

test/integration/depth_camera.cc, test/integration/thermal_camera.cc
Backports #405 
Reference build (Thermal Camera and Depth Camera test regressions on Citadel): https://build.osrfoundation.org/job/ignition_rendering-ci-ign-rendering3-homebrew-amd64/74/
Signed-off-by: Cristóbal Arroyo <cristobal.arroyo@ekumenlabs.com>
Port `ign-rendering5` to `ign-rendering3`
FYI: @Blast545
=> Backport 5 :arrow_right: 3 Disabling flaky depth and thermal camera tests on mac (#405)

ogre2/src/Ogre2GpuRays.cc
Destroy camera on exit in Ogre2GpuRay class, which is also done in gz-rendering6 [here](https://github.com/gazebosim/gz-rendering/blob/ign-rendering6/ogre2/src/Ogre2GpuRays.cc#L498). This also ensures the `Destroy` function can be called multiple times.
This should fix the gpu lidar test in gz-sensors.
=> Destroy GpuRay camera on exit

ogre/include/ignition/rendering/ogre/OgreIncludes.hh, ogre/src/OgreRenderTarget.cc, ogre2/src/Ogre2RenderEngine.cc, ogre2/src/Ogre2RenderTarget.cc
Backports #617 
Reference issue: https://github.com/gazebosim/gz-rendering/issues/621
Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>
Port 6 to 3
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/ign-rendering3...Crola1702:Crola1702/6_to_3-2022_08_16
=> Backport from 6 :arrow_right: 3 - Disable C4275 warnings on Windows from OgreUTFString (#621)

ogre2/include/ignition/rendering/ogre2/Ogre2BoundingBoxCamera.hh
Signed-off-by: methylDragon <methylDragon@gmail.com>
**Boundin** :no_mouth:
=> Hotfix typo in ogre2 include statement

test/integration/camera.cc, test/media/materials/programs/simple_color_fs.metal, test/media/materials/programs/simple_color_vs.metal
Partially addresses #695
This was a test that was disabled on macOS after metal porting, but now it can be re-enabled.
=> Fix INTEGRATION_camera/shader_selection on macOS

ogre/src/OgreCamera.cc, ogre/src/OgreDepthCamera.cc, ogre/src/OgreGpuRays.cc, ogre/src/OgreRenderTarget.cc, ogre/src/OgreThermalCamera.cc, ogre/src/OgreWideAngleCamera.cc, test/common_test/CommonRenderingTest.hh, test/common_test/Material_TEST.cc, test/regression/CMakeLists.txt, test/regression/reload_engine.cc
Similar to previous crashes we have had, we weren't appropriately cleaning up resources in our rendering objects.
I uncovered this while testing `gz-sensors7`, as it wasn't revealed by tests here.
As a result, I have added a regression test that will attempt to load and unload a rendering engine multiple times while also instantiating sensors.  If everything is cleaned up correctly, this test runs without any segfaults.
A have also included fixes for the DepthCamera and GpuRays sensor that were detected via this test.
=> Add regression test for multiple engine reloads

ogre2/src/Ogre2Material.cc
It was incorrectly setting the emissive map with the metalness map texture.
=> Fix setting emissive map

test/integration/camera.cc
Improves error reporting for failing test
A test was re-enabled for macOS in https://github.com/gazebosim/gz-rendering/pull/703, but it seems to still fail on certain machines (see comments below https://github.com/gazebosim/gz-rendering/pull/703#issuecomment-1245856857).
The test currently seg-faults after an `EXPECT_*` statement is used to check for a nullptr and the pointer is later dereferenced. Wrap the subsequent check in an if statement to allow the rest of the test to continue instead of using `ASSERT_*`. This doesn't fix the underlying issue but it should allow the test to proceed a bit farther and provide more useful failure reporting.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining …
=> Camera ShaderSelection: avoid seg-fault

ogre2/src/media/materials/programs/GLSL/point_fs.glsl, ogre2/src/media/materials/scripts/point_cloud_point.material
Fixes https://github.com/gazebosim/gz-rendering/issues/719
We're not longer using the `color` uniform in the shaders so removing it to prevent a warning from popping up in the ogre2.log on macOS
=> Remove unused point cloud color uniform variable

CMakeLists.txt
Trying to build Garden on Windows via conda results in a state where ogre is not found (conda provides 1.13, but gz-rendering wants 1.9). Due to the badly written `if()`, if ogre is not found, the whole build fails with:
```
--- stderr: gz-rendering7
CMake Warning at D:/programovani/ign5-ws/install/share/cmake/gz-cmake3/cmake3/FindGzOGRE.cmake:173 (find_package):
Could not find a configuration file for package "OGRE" that is compatible
with requested version "1.9".
The following configuration files were considered but not accepted:
D:/Programy/Conda/envs/ign5-ws/Library/CMake/OGREConfig.cmake, version: 13.4.4
Call Stack (most recent call first):
D:/programovani/ign5-ws/install/share/cmake/gz-cmake3/cmake3/GzUtils.cmake:231 (find_package)
CMakeLists.txt:78 (gz_find_package)
CMake Error at …
```
=> Fix build in case no suitable OGRE is found

CMakeLists.txt, Changelog.md
Preparation for 7.0.0 release.
Comparison to 6.5.1: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering6_6.5.1...changelog_7
=> Update Changelog for 7.0.0

examples/hello_world_plugin/HelloWorldPlugin.cc, include/gz/rendering/RenderEngineManager.hh, ogre/include/gz/rendering/ogre/OgreRTShaderSystem.hh, ogre/include/gz/rendering/ogre/OgreRenderEngine.hh, ogre/src/OgreRTShaderSystem.cc, ogre/src/OgreRenderEngine.cc, ogre2/include/gz/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/src/Ogre2RenderEngine.cc, optix/include/gz/rendering/optix/OptixRenderEngine.hh, optix/src/OptixRenderEngine.cc, src/RenderEngineManager.cc
Signed-off-by: Ian Chen <ichen@openrobotics.org>
Similar to the fix done in https://github.com/gazebosim/gz-common/pull/451, the changes here aim to prevent multiple copies of a singleton from being instantiated in the plugins. 
=> Prevent multiple singletons from being instantiated

ogre/src/OgreWideAngleCamera.cc, test/integration/wide_angle_camera.cc
In response to bug reported in https://github.com/gazebosim/gz-rendering/issues/729#issuecomment-1272381346
Initializes wide angle camera's env map pixel format to the same format that is set to the wide angle camera. I also updated other parts in the code that has use the hardcoded `R8G8B8` type.
=> Initialize wide angle camera pixel format

include/ignition/rendering/base/BaseArrowVisual.hh, ogre/src/OgreMaterial.cc, ogre2/include/ignition/rendering/ogre2/Ogre2ArrowVisual.hh, ogre2/include/ignition/rendering/ogre2/Ogre2AxisVisual.hh, ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh, ogre2/src/Ogre2ArrowVisual.cc, ogre2/src/Ogre2AxisVisual.cc, ogre2/src/Ogre2Scene.cc, src/ArrowVisual_TEST.cc, src/AxisVisual_TEST.cc, src/ShaderParams_TEST.cc
Related with https://github.com/gazebosim/gz-sim/issues/1575
Improved coverage Arrow and Axis visuals and fixed some warnings
=> Improved coverage Arrow and Axis visuals and fixed some warnings

src/Grid_TEST.cc
Related with https://github.com/gazebosim/gz-sim/issues/1575
Improved grid coverage
=> Improved grid coverage

src/Marker_TEST.cc
=> Increased Marker coverage

src/TransformController_TEST.cc
Related with https://github.com/gazebosim/gz-sim/issues/1575
Backport https://github.com/gazebosim/gz-rendering/pull/668/files
=> [Backport Citadel] Increase TransformControl test converage (#668)

.github/ci/packages-jammy.apt, include/gz/rendering/Camera.hh, include/gz/rendering/RenderEngineVulkanExternalDeviceStructs.hh, include/gz/rendering/RenderTarget.hh, include/gz/rendering/base/BaseCamera.hh, include/gz/rendering/base/BaseRenderTarget.hh, ogre2/include/gz/rendering/ogre2/Ogre2Camera.hh, ogre2/include/gz/rendering/ogre2/Ogre2RenderTarget.hh, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2RenderEngine.cc, ogre2/src/Ogre2RenderTarget.cc
No ticket is associated with this feature.
1. This PR.
2. gazebosim/gz-gui#357
- or optionally, merge this one as part of the next one aka PR 467, which includes it
3. gazebosim/gz-gui#467
4. gazebosim/gz-sim#1735
The GUI component needs to send the Vulkan device to Rendering component, which in turns sends it to OgreNext. There were various possible solutions:
1. gz-gui gets linked against OgreNext
2. gz-rendering gets linked against Qt
3. The solution in this PR, where a few structs are added to get passed around and perform Qt -> OgreNext conversions while both components are reasonably isolated from each other.
This PR adds the following structs:
- `GzVulkanExternalInstance` (mirrors `Ogre::VulkanExternalInstance` without depending on OgreNext)
- `GzVulkanExternalDevice` (mirrors …
=> Add necessary headers for Vulkan QML GUI backend

ogre/include/ignition/rendering/ogre/OgreIncludes.hh, ogre/src/OgreRenderTarget.cc, ogre2/include/ignition/rendering/ogre2/Ogre2Includes.hh, ogre2/src/Ogre2DynamicRenderable.cc, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2MaterialSwitcher.cc, ogre2/src/Ogre2Mesh.cc, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/Ogre2SelectionBuffer.cc, ogre2/src/Ogre2ThermalCamera.cc
Cleans up Windows warnings from OGRE headers.
=> Suppress Windows warnings

ogre/src/OgreWideAngleCamera.cc
There is no ticket assigned to this bug
The matrix returned by Ogre::Camera::getProjectionMatrix has Z in range [-1; 1], not range [0; 1]
This means we can't do pos.z > 0. We must do pos.z / pos.w > -1 Additionally, we must check against against z < 1; otherwise the point may get picked by the wrong face (and fail tests).
I found this bug while porting OgreWideAngleCamera to ogre2
=> Fix wrong Z check in OgreWideAngleCamera::Project3d

ogre2/include/gz/rendering/ogre2/Ogre2RenderTarget.hh, ogre2/include/gz/rendering/ogre2/Ogre2RenderTypes.hh, ogre2/include/gz/rendering/ogre2/Ogre2Scene.hh, ogre2/include/gz/rendering/ogre2/Ogre2WideAngleCamera.hh, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/Ogre2Scene.cc, ogre2/src/Ogre2WideAngleCamera.cc, ogre2/src/media/materials/programs/GLSL/wide_lens_map_fp.glsl, ogre2/src/media/materials/programs/GLSL/wide_lens_map_vs.glsl, ogre2/src/media/materials/programs/Metal/wide_lens_map_fp.metal, ogre2/src/media/materials/programs/Metal/wide_lens_map_vs.metal, ogre2/src/media/materials/scripts/wide_angle_camera.compositor, ogre2/src/media/materials/scripts/wide_angle_camera.material, test/integration/wide_angle_camera.cc
Closes #729 
This PR ports OgreWideAngleCamera to Ogre2 engine.
Includes Vulkan, OpenGL & Metal shaders (Metal support not tested)
Edit `wide_angle_camera.sdf` so that:
```
<plugin
filename="gz-sim-sensors-system"
name="gz::sim::systems::Sensors">
<render_engine>ogre</render_engine>
</plugin>
```
No longer says ogre and run:
`gz sim wide_angle_camera.sdf`
The only major/blocking issue I see is that `Ogre2Scene::CreateWideAngleCameraImpl` was added (and is obviously necessary) but adding it breaks the ABI.
=> Add Support for wide-angle cameras in ogre2

examples/text_geom/CMakeLists.txt, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2Grid.cc, ogre2/src/Ogre2Marker.cc, ogre2/src/Ogre2RenderEngine.cc, ogre2/src/Ogre2Scene.cc, src/Marker_TEST.cc, src/MeshDescriptor_TEST.cc, src/Mesh_TEST.cc, src/MoveToHelper_TEST.cc, src/OrbitViewController.cc, src/OrbitViewController_TEST.cc, src/PixelFormat_TEST.cc, src/RenderEngineManager_TEST.cc, src/RenderEngine_TEST.cc, src/Scene_TEST.cc, src/ShaderParams_TEST.cc
Improved coverage: MeshDescriptor, Mesh, MoveToHelper, OrbitViewController, PixelFormat and ShadersParams
=> Improved coverage: MeshDescriptor, Mesh, MoveToHelper, OrbitViewController, PixelFormat and ShadersParams

CMakeLists.txt, Changelog.md
Preparation for 3.6.1 release.
Comparison to 3.6.0: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering3_3.6.0...prepare_3.6.1
=> 3.6.1 release

ogre2/src/Ogre2RayQuery.cc
Enable GPU based ray queries on macOS since we now have the metal shaders in place, see https://github.com/gazebosim/gz-rendering/issues/747. 
I tested locally on my mac and mouse picking, camera control, and transform control are working.
=> Enable GPU based ray queries on mac

ogre2/src/Ogre2GpuRays.cc, test/integration/gpu_rays.cc
Fixes https://github.com/gazebosim/gz-rendering/issues/712
Fixes lidar heightmap detection which was broken when visibility mask / flags were added. It seems to only have affected `ogre2` implementation. The new integration test passes with ogre 1.x locally for me without making any changes to the `ogre` implementation.
=> Fix lidar heightmap detection

ogre2/src/Ogre2Scene.cc
No ticket was created for this issue.
OgreNext 2.2+ has a feature where all textures are asynchronously loaded by default; and a blank texture will be shown until it's ready.
This is great for low latency interactions & most games; but terrible if we want all our simulated frames to be perfect & deterministic results
We don't want placeholder textures to be used; thus wait until all textures being loaded are done.
I found this bug while working on the Heightmap Integration tests for Fortress. The test required to load some PNGs and it failed spectacularly as the first frames rendered used the placeholder textures instead of the final ones.
`waitForStreamingCompletion` doesn't have any performance impact if there are no textures waiting to finish loading; and it will obviously affect …
=> Fix non-deterministic rendering due to background texture loading

ogre2/src/media/Hlms/Terra/GLSL/VertexShader_vs.glsl, test/common_test/Heightmap_TEST.cc
There is no ticket for this bug
I'm in the process of writing integration tests for Heightmap (ogre2).
In the meantime I noticed:
- Heightmap's UNIT test can be enabled for ogre2
- GpuRays camera will crash if a Heightmap is used in it (the integration code I'm writing found this, but it's not ready for pushing it).
Since these changes are simple enough I'm submitting them as their own PR.
=> Enable Heightmap Test for ogre2 & fix crash when using GpuRays camera

ogre2/src/media/materials/programs/GLSL/depth_camera_fs.glsl, ogre2/src/media/materials/programs/Metal/depth_camera_fs.metal
No ticket was filed for this issue
Depth Camera uses an approximation for sRGB conversion.
This causes regular Camera to slightly _**but visibly**_ differ in their RGB output compared to the one done by Depth Camera (stored encoded as RGBA8888 in the A channel of the DepthCamera).
This fix causes cameras to identically match 100% both outputs (possibly some GPUs may have a margin of error of up to 1/255 due to precision issues with floating points. DepthCamera already suffers a few problems due to assembly code not understanding that we store a binary encoded value in a F32 value; and sometimes denormals or NaNs get flushed).
Without this patch, here's a an output of a Regular Camera (Note these pictures were taking using Garden while this PR is targeting Fortress):
And here's an output …
=> Use proper sRGB conversion in DepthCamera

test/integration/scene.cc
Disable `Scene.VisualAt` test as it's flaky on macOS, see https://github.com/gazebosim/gz-rendering/pull/758#issuecomment-1329246890
=> Disable flaky VisualAt test on mac

CMakeLists.txt
Preparation for 3.7.0 prerelease.
Comparison to 3.6.1: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering3_3.6.1...ign-rendering3
Needed by https://github.com/gazebosim/gz-sensors/pull/260
=> 3.7.0 prerelease

CMakeLists.txt, Changelog.md
Preparation for 3.7.0 release.
Comparison to 3.6.1: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering3_3.6.1...ign-rendering3
Needed by https://github.com/gazebosim/gz-sensors/pull/260
=> 3.7.0 release

include/gz/rendering/Camera.hh, include/gz/rendering/base/BaseCamera.hh, ogre/include/gz/rendering/ogre/OgreCamera.hh, ogre/src/OgreCamera.cc, ogre/src/OgreDepthCamera.cc, ogre/src/OgreThermalCamera.cc, ogre2/include/gz/rendering/ogre2/Ogre2Camera.hh, ogre2/src/Ogre2BoundingBoxCamera.cc, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2SegmentationCamera.cc, ogre2/src/Ogre2ThermalCamera.cc, test/common_test/Camera_TEST.cc, test/integration/camera.cc
Fixes #763
The old default Aspect Ratio would be 1.3333
Now it is 0.0 which indicates Gazebo should autocalculate the Aspect Ratio.
This results in a nice backwards-compatible behavior while fixing various bugs mentioned in gazebosim/gz-rendering#763
Fixes gazebosim/gz-rendering#763
=> Implement consistent Auto Aspect Ratio

src/base/BaseRenderEngine.cc
No ticket submitted for this bug.
A very silly Copy/Paste mistake: when a duplicate scene name is found, the error log will complain it has the same ID; instead of saying it has the same name.
=> Wrong error log message

ogre/include/ignition/rendering/ogre/OgreCamera.hh, ogre/include/ignition/rendering/ogre/OgreDepthCamera.hh, ogre/include/ignition/rendering/ogre/OgreThermalCamera.hh, ogre/src/OgreCamera.cc, ogre/src/OgreDepthCamera.cc, ogre/src/OgreRenderTarget.cc, ogre/src/OgreThermalCamera.cc, ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2RenderTarget.cc
No ticket was filed for this bug.
During PR #775 I discovered this bug.
That PR will fix that bug in main, this is a backport for Fortress.
A tiny difference is that in `main` changes were done so that RenderPasses are destroyed cleanly, while in Fortress' backport I can't do that without breaking the ABI.
=> Fix RenderTarget::destroy not getting called in both ogre1 & ogre2

ogre2/src/Ogre2GpuRays.cc
Order of destruction was inverted
No ticket was filed for this bug.
This bug was discovered thanks to CI and Valgrind in PR #785
This is a backport to Fortress.
=> Fix memory corruption in Ogre2GpuRays (Fortress)

ogre2/src/Ogre2GpuRays.cc
No ticket was filed for this bug.
Same as PR #787 
Garden flavour.
=>  Fix memory corruption in Ogre2GpuRays (Garden)

ogre2/src/media/Hlms/Terra/Metal/VertexShader_vs.metal
No ticket filed for this bug report.
Trying to use the heightmap in GpuRays (Lidar) in macOS / Metal will result in a shader compiler error.
This is a backport from PR #785 which includes this fix alongside the integration test that discovered this bug.
=> Fix Metal shader compiler error in GpuRays (Lidar)

ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/Ogre2SelectionBuffer.cc, ogre2/src/Ogre2ThermalCamera.cc
No particular ticket issued for this bug.
This is the same as PR #783 but targeting Garden, which needs additional changes (Ogre2GpuRays) that could be easily missed when merging Fortress into Garden.
=>  Do not overwrite reserved visibility flags in ogre2 (Garden)

CMakeLists.txt, Migration.md, include/gz/rendering/config.hh.in, src/RenderEngineManager.cc, test/common_test/RenderingIface_TEST.cc, test/gz_rendering_test.cmake
Further addresses https://github.com/gazebosim/gz-rendering/pull/790#issuecomment-1350763951
The config.hh file with these `HAVE_` macros can be indirectly included and used by downstream projects and potentially collide with their own private macros so a `GZ_RENDERING_` prefix is added to these macros. 
I also removed macros that are not used
Not sure if there is an elegant way to print out a deprecation msg. I added deprecation notes in `Migration.md` guide
=> Cleanup config.hh.in and deprecate public HAVE_ macros

ogre2/src/Ogre2RenderEngine.cc
Instructs the user to visit https://gazebosim.org/docs/fortress/troubleshooting when render engine fails to initialize. There is already some information on the page about issues creating the render window. I plan to add a little more info that page.
We'll need to update the url when merging forward.
=> Add message to see troubleshooting page when render engine fails to initialize

ogre2/src/Ogre2RenderEngine.cc
Fixes #526 and maybe https://github.com/gazebosim/gz-sim/issues/1746 .
Restore GLX context after loading the OGRE plugin. It is possible the loading process changes the current GLX context.
=> Fix OGRE 2 with VirtualGL

ogre2/src/Ogre2DepthCamera.cc, ogre2/src/media/materials/programs/GLSL/depth_camera_final_fs.glsl, ogre2/src/media/materials/programs/GLSL/depth_camera_fs.glsl, ogre2/src/media/materials/programs/Metal/depth_camera_final_fs.metal, ogre2/src/media/materials/programs/Metal/depth_camera_fs.metal, test/integration/depth_camera.cc
Fixes #332 (again) for macOS and possibly any OS/HW/Driver combination.
Fixes #369 
For a very long time macOS (and possibly other OS/HW/Driver combination) would fail the tests because the shader code was doing (simplified, in C to convey the explanation):
```cpp
uint32_t valueToStore = r << 24 | g << 16 | b << 8 | a;
float output;
output = (float*)&valueToStore;
return output;
```
In ticket #332 I made a deep analysis and found out that given the wrong conditions, the bit pattern would result in either a denormal or a NaN in floating point; which risks being flushed to 0 (or set all types of NaN to the same type bit pattern of NaN).
Although the ticket was closed and tagged as "fixed", on some OS/HW/Driver combinations (e.g. macOS + Metal) this error would reappear.
This isn't just a …
=> Fix Ogre2DepthCamera on macOS (Fortress)

examples/global_illumination/Main.cc, ogre2/src/Ogre2Scene.cc, test/common_test/GlobalIllumination_TEST.cc
As observed in https://github.com/gazebosim/gz-rendering/pull/675#issuecomment-1363311005, Global Illumination (GI) CI CVT method current crashes when run with OpenGL. It is [recommended](https://github.com/gazebosim/gz-rendering/pull/675#issuecomment-1363412495) to run it with Vulkan backend.
This PR adds a check for backend api and only creates GI CI VCT if backend is vulkan
To test:
Make sure to build gz-rendering with vulkan support. You'll need to install `libvulkan-dev`
Go to the `examples/global_illumination` demo:
Change the [GI_METHOD](https://github.com/gazebosim/gz-rendering/blob/a6a94794b925b5fcd745b900eb3b434e3949ccaf/examples/global_illumination/GiConfig.hh#L17)  to a value other than `1` to force GI to use the CI VCT method. Then build and run:
```sh
./global_illumination …
```
=> Limit Global Illumination CI CVT method to vulkan backend

ogre2/src/Ogre2SelectionBuffer.cc, src/base/BaseScene.cc
Another fix for https://github.com/gazebosim/gz-sim/issues/147, specifically the issue shown in the video in https://github.com/gazebosim/gz-sim/issues/147#issuecomment-1156973396
The problem is that when clicking on semi-transparent visuals with nothing in the background, the ogre2 selection buffer returns `nan` point values. This causes entity selection to think that nothing is pressed by the mouse. Similarly when using the transform control tool, the user will not be able to click on the semi-transparent arrow visual if there is nothing in the background. For the entity selection and transform control functionality, we don't really need the point / distance results from the selection buffer ray query, so the workaround is to just make …
=> Fix selecting semi-transparent visuals

ogre2/src/Ogre2GzHlmsSharedPrivate.cc, ogre2/src/Ogre2GzHlmsSharedPrivate.hh
Fixes https://github.com/gazebosim/gz-sensors/issues/197
memory leak was due to internal buffers were being continuously created. Implemented the fix as suggested in https://github.com/gazebosim/gz-sensors/issues/197#issuecomment-1371438636 to prevent growing the buffers if not needed
To test:
Launch gz sim with `gpu_lidar_sensor.sdf` world:
```sh
gz sim -v 4 -r gpu_lidar_sensor.sdf
```
Subscribe to lidar data which will force lidar to start rendering
```sh
gz topic -e -t /lidar/points > /dev/null
```
Run `htop` or your favorite process / memory monitoring tool and see that the memory usage should now remain steady.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while …
=> Fix gpu lidar memory leak [ogre2]

ogre2/src/Ogre2Mesh.cc, src/Mesh_TEST.cc
Fixes #805 
The code snippet in #805 identified a case in which a mesh is not properly destroyed when it goes out of scope, see code and comment below
```cpp
ignition::rendering::MeshPtr mesh_geom = scene.CreateMesh(descriptor);
// the line below leaves the original `mesh_geom` dangling and we are not cleaning it up properly
mesh_geom = scene.CreateMesh(descriptor);
```
This PR makes sure the `Destroy` function is called in the mesh destructor.
The mesh unit test is updated to cover the use case shown in #805
=> Mesh cleanup on destruction

CMakeLists.txt, Changelog.md
Preparation for 6.5.2 release.
Comparison to 6.5.1: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering6_6.5.1...prep_6.5.2
No new features were added so just a patch release.
=> Prepare for 6.5.2 release

ogre/include/gz/rendering/ogre/OgreVisual.hh, ogre/src/OgreDepthCamera.cc, ogre2/include/gz/rendering/ogre2/Ogre2Camera.hh, src/Scene_TEST.cc
Changes to get CI to be green again
=> Fix tests and warnings for 3 -> 6 forward port

include/ignition/rendering/base/BaseArrowVisual.hh, include/ignition/rendering/base/BaseAxisVisual.hh, include/ignition/rendering/base/BaseJointVisual.hh
Fixes #814 
backport fix from #816 that ensures composite visuals are destroyed properly
=> Backport Composite BaseVisual destroy fix to 6

CMakeLists.txt, Changelog.md
Preparation for 6.6.0 release.
Comparison to 6.5.2: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering6_6.5.2...prep_6.6.0
Needed by
* https://github.com/gazebosim/gz-sensors/pull/313
I also fixed the changelog version from previous 6.5.2 release pointed out in https://github.com/gazebosim/gz-rendering/pull/808#discussion_r1086264362
=> 6.6.0 release

CMakeLists.txt, Changelog.md
Signed-off-by: Nate Koenig <nate@openrobotics.org>
Preparation for 3.7.1 release.
Comparison to 3.7.0: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering3_3.7.0...ign-rendering3
Needed by https://github.com/gazebosim/gz-sim/pull/1646
=> 3.7.1 release

ogre/src/OgreNode.cc, ogre2/src/Ogre2Node.cc
Fixes https://github.com/gazebosim/gz-rendering/issues/710
Currently rendering crashes with ogre assertion error when the camera position is a really large value. This PR places a limit on the max length of of the node position vector that can be set to prevent the crash. Note that the max limit is different between `ogre` and `ogre2` render engines
launch gazebo and use view angle plugin to set the pose of the camera to a large number:
1. `ign gazebo -v 4 shapes.sdf`
2. Go to top right menu, open `View Angle` plugin
3. Scroll down to `Camera Pose` section and enter 100000000000 in the `X` field -> gazebo should no longer crash
=> Limit max camera node position values

ogre2/src/Ogre2Node.cc
Tweak the max camera position value that's set in https://github.com/gazebosim/gz-rendering/pull/824.
I've been testing https://github.com/gazebosim/gz-sim/pull/1807 (specifically addressing https://github.com/gazebosim/gz-sim/pull/1807#issuecomment-1428646045) and it seems like a camera pos length of 1e10 is still too large and crashes can still happen. With this change and the latest changes in https://github.com/gazebosim/gz-sim/pull/1807, I can no longer get gz-sim to crash.
=> Tweak max camera position limit

ogre2/src/Ogre2RenderEngine.cc
The same message was added in https://github.com/gazebosim/gz-rendering/pull/793. The render engine can actual fail before that when it tries to create the dummy render window. So added another message when that fails.
Related PR: https://github.com/gazebosim/docs/pull/347
=> Add message to see troubleshooting page when render engine fails to create dummy window

Migration.md, include/gz/rendering/base/BaseStorage.hh, test/common_test/Scene_TEST.cc
Fix `UNIT_Scene_TEST` - index is now different due to change from map to vector
Added doc on the APIs with note mentioning iterators can change
Added note in migration guide
=> Add doc on iterators in BaseStore

Migration.md, include/gz/rendering/base/BaseStorage.hh, include/gz/rendering/base/BaseVisual.hh, ogre/src/OgreVisual.cc, ogre2/src/Ogre2Visual.cc, test/common_test/Scene_TEST.cc
Most of the time the `store` std::map inside BaseStorage is iterated over, which is not as efficient as a std::vector.
=> Use std::vector instead of std::map in BaseStorage

CMakeLists.txt, ogre2/src/CMakeLists.txt, ogre2/src/Ogre2RenderEngine.cc, test/integration/CMakeLists.txt, test/integration/load_unload.cc
I ran into a crash in gz-sim on exit after unloading the ogre2 render engine. It was found that it only happens if ogre-next is built with EGL support **and** the engine is created / deleted in a thread. The fix is to make sure EGL returns to its original state, specifically by calling `eglReleaseThread()` after deleting ogre root.
The fix this PR make EGL calls which requires including and linking against the EGL library, hence the extra cmake code. The proper fix may be to do this inside ogre.
To Test:
Run the `INTEGRATION_load_unload` test
=>  Fix deleting ogre2 when created (and deleted) in a thread

ogre2/src/Ogre2RenderEngine.cc, test/integration/load_unload.cc
Follow up to https://github.com/gazebosim/gz-rendering/pull/840. Fixes crash on macOS as mentioned in https://github.com/gazebosim/gz-rendering/pull/840#issuecomment-1500721820
This PR fixes the test failures by:
* Calling `eglReleaseThread` only when necessary
* Removing `window->destroy()`, this should be handled when ogre is deleted so we're just calling it twice.
* Disabling the `load_unload` test on mac - creating/deleting the render engine in a separate thread causes an issue on mac (but works on linux and win) - this needs to be further investigated. 
=> Limit eglReleaseThread call to GL render system

CMakeLists.txt
Related: https://github.com/osrf/homebrew-simulation/pull/2237#issuecomment-1518890616
https://github.com/gazebosim/gz-rendering/pull/840 explicitly made OpenGL a required component but that broke pkg-config in homebrew. This PR reverts the change for macOS. 
=> Fix requiring OpenGL on macOS.

ogre2/include/gz/rendering/ogre2/Ogre2Projector.hh
Fix visibility decorator of Ogre2Projector class.
`Ogre2Projector` was decorated by `GZ_RENDERING_OGRE_VISIBLE` instead of `GZ_RENDERING_OGRE2_VISIBLE`, probably a copy&paste error.
I noticed this as by building `gz-rendering` with `SKIP_ogre`, the build was failing with:
~~~
In file included from /home/traversaro/gz-ws/src/gz-rendering/ogre2/src/Ogre2Projector.cc:30:
/home/traversaro/gz-ws/src/gz-rendering/ogre2/include/gz/rendering/ogre2/Ogre2Projector.hh:26:10: fatal error: gz/rendering/ogre/Export.hh: No such file or directory
26 | #include "gz/rendering/ogre/Export.hh"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
~~~
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining …
=> Fix visibility decorator of Ogre2Projector

ogre2/src/media/2.0/scripts/materials/Common/GLSL/GaussianBlurBase_cs.glsl, ogre2/src/media/2.0/scripts/materials/Terra/GLSL/TerraShadowGenerator.glsl, ogre2/src/media/Hlms/Common/GLSL/CrossPlatformSettings_piece_all.glsl
Fixes part of https://github.com/gazebosim/gz-sim/issues/920 and of https://github.com/gazebosim/gz-rendering/issues/852 .
Old GPUs and systems with incomplete GL implementations like WSLg would trigger shader compiler errors for several reasons:
* because C++ saw that GL_ARB_shader_storage_buffer_object was supported but we didn't request it in the shader.
* because C++ required the use of GLSL 4.30 (not supported by d3d12 as of 2023/05), even if GLSL 4.20 plus some extensions would also work fine.
This was tested on both mesa 22.2.5 and 23.1.0 .
The fix is actually from @darksylinc, see https://github.com/OGRECave/ogre-next/commit/5b6d444ece12a32ed8115c22650c2c79cb54c8e1 and https://github.com/OGRECave/ogre-next/commit/3d9d380683cdd3fb252d754c4e40d01dfa81a3aa for the original commits. …
=> OgreNext: Fix shaders compilation on d3d12 mesa driver (WSLg)

include/gz/rendering/GraphicsAPI.hh
Same as gazebosim/gz-common#512, build fails on GCC 13.1.1 due to a missing `<cstdint>` header.
Adds missing `<cstdint>` to `GraphicsAPI.hh`
=> Fix missing cstdint header in latest gcc build

ogre/src/OgreProjector.cc, ogre/src/OgreRenderEngine.cc, ogre2/src/Ogre2RayQuery.cc, ogre2/src/terrain/Terra/src/Terra.cpp
- Remove std::move for temporary returned from OgreProjectorListener::FindVisibleMaterials
- Fix namespace for OgreRenderEngine plugin registration
- Fix unused variable in ogre2/src/Ogre2RayQuery.cc
- Add missing header Terra/Hlms/OgreHlmsTerraDatablock.h in ogre2/src/terrain/Terra/src/Terra.cpp
=> Minor cleanup of ogre/ogre2

include/gz/rendering/Capsule.hh
Fixes #856
Expanded the doxygen comments in the Capsule to explain the reason behind the APIs: https://github.com/gazebosim/gz-rendering/pull/200#pullrequestreview-589043823
=> Add more doc mentioning the reason for a Capsule class

ogre/src/OgreGpuRays.cc
Fixes gz-sensors' `INTEGRATION_dvl` test with ogre on Harmonic
The test has been failing (crashing) on homebrew CI which runs test with `ogre`. I was able to reproduce the crash and found that the issue is due to the ogre node being destroyed twice on the rendering side. Added a check to make sure we return from the `Destroy` function if camera is null (indicates resources have been removed already). The same check [exists](https://github.com/gazebosim/gz-rendering/blob/b32cbd37bbfbac9e4c3db3e66171044f4ab14754/ogre2/src/Ogre2GpuRays.cc#L588) in the ogre2 version.
To reproduce the test failure in Harmonic workspace:
```
RENDER_ENGINE_VALUES=ogre ./build/gz-sensors8/bin/INTEGRATION_dvl
```
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the …
=> Fix calling GpuRays::Destroy more than once

ogre/src/OgreCamera.cc, ogre/src/OgreGpuRays.cc, ogre/src/OgreSelectionBuffer.cc, ogre/src/OgreThermalCamera.cc, ogre/src/OgreWideAngleCamera.cc, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2SegmentationCamera.cc, ogre2/src/Ogre2SelectionBuffer.cc, ogre2/src/Ogre2ThermalCamera.cc
Cleanup minor memory leaks when a sensor is destroyed:
* Adds a call to `Base*::Destroy` when a sensor is destroyed - this eventually calls `BaseNode::Destroy` which makes sure the `ogreNode` is [destroyed](https://github.com/gazebosim/gz-rendering/blob/4a1d9af9b08340955ba40e8e3cf680f5852473e8/ogre2/src/Ogre2Node.cc#L77`)
* Note: some sensor classes already includes the call to `BaseNode::Destroy`, e.g. [Ogre2GpuRays](https://github.com/gazebosim/gz-rendering/blob/4a1d9af9b08340955ba40e8e3cf680f5852473e8/ogre2/src/Ogre2GpuRays.cc#L684). This PR adds the call to all other classes.
* Deletes the selection buffer in Camera sensor
=> Destroy sensor node on exit

ogre2/src/Ogre2Heightmap.cc
Added missing  `Ogre2Heightmap::DestroyImpl` implementation. The changes were added to `ign-rendering6` branch in https://github.com/gazebosim/gz-rendering/pull/670 but looks like they got lost in the 6->7 merge.
=> Restore missing Ogre2Heightmap::DestroyImpl implementation

.github/workflows/ci.yml, include/gz/rendering/Camera.hh, include/gz/rendering/LidarVisual.hh, include/gz/rendering/RenderEngine.hh
Harmonic only supports Jammy so removing Focal CI.
=> Disable Focal on Harmonic

ogre2/include/gz/rendering/ogre2/Ogre2ParticleEmitter.hh, ogre2/src/Ogre2ParticleEmitter.cc
Address todo note about an ABI breaking change in Ogre2ParticleEmitter class. 
=> Address todo in Ogre2ParticleEmitter - override PreRender function

ogre/include/gz/rendering/ogre/OgreRTShaderSystem.hh, ogre/include/gz/rendering/ogre/OgreRenderEngine.hh, ogre/src/OgreRTShaderSystem.cc, ogre/src/OgreRenderEngine.cc, ogre2/include/gz/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/src/Ogre2RenderEngine.cc
Continuing the effort from #874, this PR removes inheritance from `common::Singleton` for all other classes.
=> Remove inheritance from common::Singleton for all classes

ogre/src/OgreDistortionPass.cc, ogre2/include/gz/rendering/ogre2/Ogre2LensFlarePass.hh, ogre2/src/Ogre2LensFlarePass.cc, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2RayQuery.cc, ogre2/src/Ogre2SelectionBuffer.cc
Motivated by https://github.com/gazebosim/gz-sim/issues/2084. 
Went through and clean up resources and pointers when the objects destroyed. This is is to make sure that we don't hold on to any pointers after the engine is destroyed. 
More info:
We have ogre pointers as member variables in different rendering classes. The destructors are called when they go out of scope. If the engine is destroyed before the destructors are called, the destructor may be calling function from pointers that are no longer valid. So this PR tries to clear and reset all pointers when objects are destroyed (before the engine is unloaded).
=> Clean up internal resources on Destroy

.github/workflows/triage.yml, Changelog.md
Port `gz-rendering7 ` ➡️  `gz-rendering8`
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/gz-rendering8...gz-rendering7
=> Merge gz-rendering7 ➡️  gz-rendering8

CMakeLists.txt, Changelog.md
Preparation for 6.6.1 release.
Comparison to 6.6.0: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering6_6.6.0...ign-rendering6
=> Prepare for 6.6.1 Release

examples/camera_tracking/Main.cc, examples/custom_scene_viewer/ManualSceneDemo.cc, examples/gazebo_scene_viewer/GazeboDemo.cc, examples/gazebo_scene_viewer/GazeboWorldDemo.cc, examples/mesh_viewer/Main.cc, examples/mouse_picking/Main.cc, examples/projector/Main.cc, examples/render_pass/Main.cc, examples/simple_demo/Main.cc, examples/text_geom/Main.cc, examples/transform_control/Main.cc, examples/view_control/Main.cc, examples/visualization_demo/Main.cc, examples/wide_angle_camera/Main.cc, tutorials/17_render_pass_tutorial.md, tutorials/18_simple_demo_tutorial.md, tutorials/19_text_geom_tutorial.md
Many examples currently load optix by default (in addition to ogre / ogre2). If optix render engine support is not available (which is often the case), you'll get the error msgs:
```
[Err] [RenderEngineManager.cc:477] Failed to load plugin [optix] : couldn't find shared library.
Engine 'optix' is not supported
```
Given that optix support is not actively being developed, it's best not to load them in the examples. Users can still choose to use optix by passing it as an arg, e.g. `./simple_demo optix`
=> Do not load optix engine in examples

examples/mesh_viewer/Main.cc
Revert background color in the mesh viewer demo from blue back back to gray.
It was accidentally updated to blue in https://github.com/gazebosim/gz-rendering/pull/811 - probably I was testing something and forgot to revert the change. 
Gray color also matches what's shown in the tutorial screenshot:
https://gazebosim.org/api/rendering/8/mesh_viewer.html
=> Revert mesh viewer background color back to gray

Migration.md, include/gz/rendering/base/BaseArrowVisual.hh, include/gz/rendering/base/BaseAxisVisual.hh, test/common_test/ArrowVisual_TEST.cc
Problem: API to change visibility of the ArrowVisual's Head visual was affecting the incorrect child visual's visibility - it updated the Rotation visibility instead. This PR fixes indexing of child nodes in ArrowVisual.
More info:
The index of child nodes have changed after https://github.com/gazebosim/gz-rendering/pull/831 that changed internal data structure from map to vector. With that change, the index number now corresponds to the order in which the child nodes are added. 
Updated test to make sure when we request for ArrowVisual's Head, Shaft, and Rotation child visuals, it returns the visual with the correct geometry.
=> Fix arrow visual indexing

ogre2/src/Ogre2WideAngleCamera.cc
The default visibility flags conflicts with ogre's internal reserved flags which causes heightmaps to be not visible in the camera view. This PR fixes the visibility flags in the same way that's [done for a regular camera](https://github.com/gazebosim/gz-rendering/blob/b16a396d64f0c0a31dcb459b3acd6d719d057ea8/ogre2/src/Ogre2RenderTarget.cc#L65-L66).
See https://github.com/gazebosim/harmonic_demo/pull/7 for screenshot
=> Fix wide angle camera visibility flags

examples/hello_world_plugin/README.md
Updated instructions to launch gz sim with an empty world otherwise the quick start menu will pop up if no world is specified. 
Also added info on what to check when the gui comes up in order to verify that the plugin is successfully loaded.
=> Minor updates to  README file in the hello_world_plugin example

ogre2/src/Ogre2ParticleEmitter.cc, test/common_test/ParticleEmitter_TEST.cc
Related issue: #902 
Setting the particle emitter color range causes particles to appear black instead of actually changing the color of the particles to the range specified. The problem is that is affecting particle emitters that have also a material set (via `SetMaterial`) - the material diffuse color is overriden and results in black particles.
This PR just disables that function for now, see more details in #902
Test with `gz sim -v 4 particle_emitter.sdf`. With these changes, you should now see that the particles on the left side of the scene appears red (the intended color specified in the `<material>` tag) instead of black with flickering red.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining …
=> Disable setting particle emitter color range

include/gz/rendering/GlobalIlluminationBase.hh, include/gz/rendering/GlobalIlluminationCiVct.hh, include/gz/rendering/GlobalIlluminationVct.hh, include/gz/rendering/NativeWindow.hh, include/gz/rendering/base/BaseNativeWindow.hh, ogre2/include/gz/rendering/ogre2/Ogre2GlobalIlluminationCiVct.hh, ogre2/src/CMakeLists.txt, ogre2/src/Ogre2GlobalIlluminationCiVct.cc, ogre2/src/Ogre2RenderEngine.cc, src/GlobalIlluminationBase.cc, src/GlobalIlluminationCiVct.cc, src/GlobalIlluminationVct.cc, src/NativeWindow.cc, src/base/BaseNativeWindow.cc
This was needed for the MSVC build to succeed. @darksylinc got obviously hit again by the poor MSVC linker that is not able to figure out it doesn't need to lookup defaulted constructors/destructors.
The CMake flag was needed to support building with VS2022. VS2019 shouldn't require it.
=> Fixed build on MSVC

ogre2/src/CMakeLists.txt
Related to https://github.com/osrf/homebrew-simulation/pull/2273
I have been adding some RPATH configuration to our homebrew formulae to fix issues with binaries installed to subfolders of `lib` and `libexec` on ARM processors, for which homebrew is installed to `/opt/homebrew` instead of `/usr/local`. In https://github.com/osrf/homebrew-simulation/pull/2404 for example, an additional entry is added to `CMAKE_INSTALL_RPATH` to fix a `gz-plugin` standalone executable. The `CMAKE_INSTALL_RPATH` value provides a default value for the `INSTALL_RPATH` property of all targets. While testing these rpath fixes, but I ran into a problem with just the ogre2 library in gz-rendering not using the paths specified in `CMAKE_INSTALL_RPATH`. After looking at the gz-rendering source code, I see that the …
=> ogre2: retain CMAKE_INSTALL_RPATH values

ogre2/src/Ogre2RenderEngine.cc
=> Include the CGL header on macOS

ogre2/src/CMakeLists.txt
Backport #909 to garden
Sets the ogre2 target INSTALL_RPATH to a copy of
CMAKE_INSTALL_RPATH with OGRE_LIBRARY_DIRS
appended, instead of just the latter path. This
helps with packaging on macOS.
**Note to maintainers**: Remember to use **Rebase-and-Merge**
=> Backport #909: rpath fix for garden

include/gz/rendering/Utils.hh, src/Camera_TEST.cc, src/Utils.cc
[backport fortress] Calculate camera intrinsics : Refactor
Required in this PR https://github.com/gazebosim/gz-sensors/pull/383
=> [backport fortress] Calculate camera intrinsics : Refactor

Changelog.md, examples/mesh_viewer/Main.cc
Port `ign-rendering6 ` ➡️  `gz-rendering7`
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/gz-rendering7...ign-rendering6
=> Merge ign-rendering6 ➡️  gz-rendering7

CMakeLists.txt, Changelog.md
Preparation for 8.0.0~pre3 release.
Comparison to 7.4.2: https://github.com/gazebosim/gz-rendering/compare/gz-rendering7_7.4.2...gz-rendering8
=> Prepare for 8.0.0~pre3 Release

ogre/include/gz/rendering/ogre/OgreDepthCamera.hh, ogre/src/OgreDepthCamera.cc, ogre2/include/gz/rendering/ogre2/Ogre2DepthCamera.hh, ogre2/src/Ogre2DepthCamera.cc
This is required to properly set camera intrinsic parameters from SDF for depth and rgbd camera sensors.
=> Add projection matrix set/get functions to Ogre Depth camera

src/Camera_TEST.cc
Fix compile warnings:
```sh
warning: comparing floating-point with ‘==’ or ‘!=’ is unsafe [-Wfloat-equal]
```
=> Fix float comparison warnings in test

CMakeLists.txt, Changelog.md
Preparation for 6.6.2 release.
Comparison to 6.6.1: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering6_6.6.1...prepare_6.6.2
Needed by https://github.com/gazebosim/gz-sensors/pull/383
=> Prepare for 6.6.2 release

ogre2/src/Ogre2Material.cc
Continuing efforts from https://github.com/gazebosim/gz-common/pull/532 for fixing rendering of glb meshes, this PR fixes the texture formats for textures coming from glb meshes. Previous behavior assumes all PBR textures are in sRGB format as the result the meshes are rendered darker than it should be. Only certain textures, (e.g. diffuse, emissive, and lightmap textures) should be in sRGB.
You can test with this [water_bottle.sdf](https://gist.github.com/iche033/822062dff94db236d2f568706958d39d) world.
Before this change:
After:
=> Fix use of srgb format for texture maps (from glb meshes)

ogre2/src/Ogre2Projector.cc
Fixed check to see if projector is using default or custom visibility flags. If it's using the default flags, we can skip all the extra computation added for visibility toggling. 
The check is not quite correct (so it's currently not skipping the extra computations). The default visibility flags (from SDF) is `0xFFFFFFFF` but the code is checking against `GZ_VISIBILITY_ALL` which is `0x0FFFFFFF`. So updated check to make sure the visibility flags contain all of `GZ_VISIBILITY_ALL` bits instead of exact equality comparison. 
This is more of a performance improvement and does not change projector behavior.
=> Minor fix to checking projector default visibility flags 

include/gz/rendering/GizmoVisual.hh, include/gz/rendering/base/BaseGizmoVisual.hh, src/TransformController.cc, test/common_test/GizmoVisual_TEST.cc
The LookAt function updates the rotation visuals in a GizmoVisual so that they always face the specified position. This is used by TransformController so that the rotation visuals (handles) are always positioned in front of the attached object w.r.t the camera so that they are easy to click on by the mouse.
=> Add LookAt function to GizmoVisual class

Changelog.md, test/common_test/Camera_TEST.cc
Port ign-rendering6 to gz-rendering7
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/gz-rendering7...ign-rendering6
=> Merge: 6 -> 7

.github/ci/packages.apt, CMakeLists.txt, examples/hello_world_plugin/CMakeLists.txt, examples/lux_core_engine/CMakeLists.txt, examples/simple_demo_qml/CMakeLists.txt, tutorials/02_install.md
See https://github.com/gazebo-tooling/release-tools/issues/1027
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-rendering9

examples/actor_animation/Main.cc, examples/boundingbox_camera/Main.cc, examples/camera_tracking/Main.cc, examples/custom_scene_viewer/ManualSceneDemo.cc, examples/custom_shaders_uniforms/Main.cc, examples/depth_camera/Main.cc, examples/heightmap/Main.cc, examples/lidar_visual/Main.cc, examples/mesh_viewer/Main.cc, examples/mouse_picking/Main.cc, examples/ogre2_demo/Main.cc, examples/particles_demo/Main.cc, examples/projector/Main.cc, examples/render_pass/Main.cc, examples/segmentation_camera/Main.cc, examples/simple_demo/Main.cc, examples/simple_demo_qml/ThreadRenderer.cpp, examples/text_geom/Main.cc, examples/thermal_camera/Main.cc, examples/transform_control/Main.cc, examples/view_control/Main.cc, examples/visualization_demo/Main.cc, examples/waves/Main.cc, examples/wide_angle_camera/Main.cc, include/gz/rendering/Utils.hh, ogre2/src/Ogre2Material.cc, src/Utils.cc
https://github.com/gazebosim/gz-rendering/issues/914
Use `metal` as default graphics API on macOs
A couple of other minor fixes:
* Fix `simple_demo_qml` deprecation warnings
* stop loading `optix` engine as one of the default engines 
=> Update examples to use metal as default graphics API on mac

ogre2/src/Ogre2Projector.cc
Fixes #944
Set projector emissive texture to be the same as the diffuse texture in ogre 2.x implementation for a more consistent result with the ogre 1.x implementation
Before (projected texture appears darker):
After (projected texture is now brighter):
Here's the projector in the harmonic demo world. 
Previously I had to use a spot light to illuminate the projected texture because it was too dark. It shouldn't be necessary now with the emissive texture set.
=> Set Projector emissive texture 

test/integration/gpu_rays.cc
Remove code as mentioned in the todo note now that the [OgreHeightmap::Destroy](https://github.com/gazebosim/gz-rendering/blob/93c278546da2152653f01187a910a1a0b97d7373/ogre2/include/gz/rendering/ogre2/Ogre2Heightmap.hh#L99) function is available. The test should not crash.
To run the test in your local colcon workspace:
```bash
GZ_ENGINE_TO_TEST=ogre2 ./build/gz-rendering8/bin/INTEGRATION_gpu_rays
```
=> Remove todo in gpu ray test

CMakeLists.txt, Changelog.md
Preparation for 3.7.2 release.
Comparison to 3.7.1 https://github.com/gazebosim/gz-rendering/compare/ignition-rendering3_3.7.1...prep_3.7.2
=> Prepare for 3.7.2 release

Changelog.md
Port `ign-rendering3 ` ➡️  `ign-rendering6`
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/ign-rendering6...ign-rendering3
=> Merge ign-rendering3 ➡️  ign-rendering6

ogre2/src/Ogre2GpuRays.cc
backport of #955
Note that from `gz-rendering7` onwards, the Ogre2GpuRays' compositor was ported to a script (as seen in #955) from C++. So the changes are not directly backported. Instead, this PR sets the ogre2 compositor parameters via C++ for `ign-rendering6` (fortress).
=> Backport ogre2 lidar performance improvement changes

CMakeLists.txt, Changelog.md
Preparation for 6.6.3 release.
Comparison to 6.6.2: https://github.com/gazebosim/gz-rendering/compare/ignition-rendering6_6.6.2...jrivero_prepare_6_6_3
=> Prepare release 6.6.3

src/RenderEngineManager.cc
Fixes #959
Added an better checks to make sure we return the engine if it was already previously loaded instead of loading the engine again.
To test:
```
gz sim -s -r -v3 --iterations 50 model_photo_shoot.sdf
```
and the following msg should now be only printed once:
```
[Msg] Loading plugin [gz-rendering-ogre2]
```
=> Fix repeatedly loading engine when calling sceneFromFirstEngine

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/ci.yml, .github/workflows/triage.yml, Changelog.md, include/gz/rendering/base/BaseGizmoVisual.hh
Port `gz-rendering7` to `gz-rendering8`
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/gz-rendering8...gz-rendering7
=> Merge 7 ➡️ 8

ogre2/src/Ogre2DepthCamera.cc
Performance optimization - Ogre2DepthCamera is capable of generating color images in addition to depth and the color data are packed into a point cloud buffer. So if there are no point cloud connections, we can skip computations needed to generate the color rgb images.
Also added changes to skip light-related computations in the same way as lidars in https://github.com/gazebosim/gz-rendering/pull/955
More info:
This is done by using ogre2's "execution mask". If the render passes execution mask matches the workspace's execution mask, the passes get executed. So by default, the color target's render passes' execution mask is set to something that does not match the workspace execution mask so we can skip computation for the color passes. When point cloud connections is detected, the passes' …
=> Optimize Ogre2DepthCamera performance by skipping color target passes when there are no connections

ogre2/src/Ogre2DepthCamera.cc
Minor performance optimization to ogre2's depth camera implementation. Similar to https://github.com/gazebosim/gz-rendering/pull/965, I used execution mask to skip rendering the particle passes if there are no particles in the scene. This yields a small speed up, see the time it takes to do 1 render operation (for a 320x240 depth camera) before and after the changes in this PR:
=> Skip particle passes in Ogre2DepthCamera if there are no particles in the scene

ogre2/src/Ogre2GlobalIlluminationCiVct.cc
Updated to use `GZ_RENDERING_OGRE2_HIDDEN` as opposed to `DETAIL_GZ_RENDERING_OGRE2_HIDDEN`. 
We actually could just remove the use of these macros in cc files as they may not be necessary, especially in ionic when symbols are hidden by default.
=> Update ogre2 symbol visibility macro

ogre2/src/Ogre2GpuRays.cc, ogre2/src/media/materials/scripts/GpuRays.compositor
Improve Ogre2GpuRays performance in the same way as done in #971 for `Ogre2DepthCamera`. Added execution mask to skip the particle passes when there are no particles in the scene
The time taken for a lidar (160 degrees FOV and 640 samples) to do a render update is shown below. The speedup is roughly ~1ms (30%). I also included the ogre1.x implementation for comparison. The ogre 1.x implementation is still faster (~5.5x) than the ogre2.x implementation
=> Skip particle passes in Ogre2GpuRays if there are no particles in the scene

ogre2/src/Ogre2MeshFactory.cc, test/integration/CMakeLists.txt, test/integration/mesh.cc
Setting normal map to a a submesh could fail in ogre2 if the mesh contains other submeshes that do not have texture coordinates set. Ogre2 will fail to generate tangents (needed for normal maps) and throw an exception:
```
03:59:05: OGRE EXCEPTION(5:ItemIdentityException): Cannot locate an appropriate 2D texture coordinate set for all the vertex data in this mesh to create tangents from.  in Mesh::suggestTangentVectorBuildParams at ./OgreMain/src/OgreMesh.cpp (line 1913)
```
The fix is to generate texcoords for all submeshes when importing the `common::SubMesh` into ogre even if the `common::SubMesh` does not have any texcoords. 
The alternative (ideal) fix is to update ogre to just skip generating tangents for those submeshes that do not have texcoords instead of throwing an exception. …
=> Fix setting normal map when not all submeshes have texcoords (ogre2)

ogre2/src/Ogre2DepthCamera.cc
Backport #965  and #971: improves perf by skipping color and particle passes when not needed
=> Backport Ogre2DepthCamera performance improvements

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/ci.yml, .github/workflows/triage.yml, Changelog.md, include/gz/rendering/base/BaseGizmoVisual.hh, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2GlobalIlluminationCiVct.cc, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2MeshFactory.cc, ogre2/src/media/materials/scripts/GpuRays.compositor, test/integration/CMakeLists.txt, test/integration/mesh.cc
Port gz-rendering8 to main
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/main...gz-rendering8
=> Merge 8 -> main

examples/actor_animation/Main.cc, examples/boundingbox_camera/Main.cc, examples/depth_camera/Main.cc, examples/global_illumination/Main.cc, examples/lux_core_engine/Main.cc, examples/mesh_viewer/Main.cc, examples/ogre2_demo/Main.cc, examples/particles_demo/Main.cc, examples/segmentation_camera/Main.cc, examples/thermal_camera/Main.cc, examples/waves/Main.cc, ogre/src/OgreMeshFactory.cc, ogre2/src/Ogre2Marker.cc, ogre2/src/Ogre2MeshFactory.cc, src/base/BaseScene.cc, test/common_test/MeshDescriptor_TEST.cc, test/common_test/Mesh_TEST.cc, test/integration/waves.cc
Add some sanity checks and for null pointers returned by `common::MeshManager::Load()`.
Also removed a few `MeshManager` headers that are not used.
=> Handle null mesh pointers in examples

ogre/src/OgreRenderEngine.cc
https://github.com/mjcarroll/pixi_gazebodistro/pull/1#issuecomment-2024068464
=> Work around conda-forge's CDT version of GL

examples/simple_demo_qml/GzRenderer.cc
Fixes compilation of `simple_demo_qml` on Windows.
This is not particularly useful as it is, as it crashes with error:
~~~
D:\src\pixi_gazebodistro\ionic_ws\src\gz-rendering\examples\simple_demo_qml\build>pixi run simple_demo_qml.exe --help
[Msg] Loading plugin [gz-rendering-ogre2]
[Err] [D:\src\pixi_gazebodistro\ionic_ws\src\gz-rendering\ogre2\src\Ogre2RenderEngine.cc:1285]  Unable to create the rendering window: OGRE EXCEPTION(3:RenderingAPIException): wglMakeCurrent failed: The pixel format is invalid.
in Win32Window::create at D:\bld\ogre-next_1712610228408\work\RenderSystems\GL3Plus\src\windowing\win32\OgreWin32Window.cpp (line 624)
[Err] [D:\src\pixi_gazebodistro\ionic_ws\src\gz-rendering\ogre2\src\Ogre2RenderEngine.cc:1285]  Unable to create the rendering window: OGRE …
=> Fix compilation on simple_demo_qml on Windows

include/gz/rendering/base/BaseGlobalIlluminationVct.hh
Warning started as of https://build.osrfoundation.org/view/gz-ionic/job/gz_rendering-ci-main-jammy-amd64/42/, likely because of https://github.com/gazebosim/gz-cmake/pull/418.
=> Fix unused variable warnings

examples/simple_demo/CMakeLists.txt, examples/simple_demo/GlutWindow.cc, examples/simple_demo/Main.cc
Fixes compilation of simple_demo on Windows.
I took the missing Windows logic from `wide_angle_camera` example. Differently from https://github.com/gazebosim/gz-rendering/pull/986, after this fix `simple_demo` works fine on Windows both with ogre and ogre2 plugins.
=> Fix simple_demo on Windows

test/gz_rendering_test.cmake
Part of gazebosim/gz-cmake#350.
I suggested in https://github.com/gazebosim/gz-cmake/issues/350#issuecomment-1907453341 that we find python directly so that `GzPython` can be deprecated, and this is a step towards that goal.
Compile and run tests and verify that the `check_test_ran.py` script still runs.
=> Find python directly instead of using GzPython

ogre2/src/Ogre2RenderEngine.cc
Fixes part of https://github.com/gazebosim/gz-sim/issues/2089 .
Without this fix, ogre-next fails with error:
~~~
wglMakeCurrent failed: The pixel format is invalid.
in Win32Window::create at D:\bld\ogrenext_1684687719477\work\RenderSystems\GL3Plus\src\windowing\win32\OgreWin32Window.cpp (line 624)`
~~~
After this fix, I was able to correctly start `gz sim -g` on Windows:
In theory, the fix can be easily backported to gz-rendering7 and ign-rendering6, but as I am only working on getting Gazebo Harmonic to work well on Windows, I am not sure if there is any benefit of doing that. Anyone interested is welcome to backport the fix to earlier versions of gz-rendering.
The fix requires the Windows ID to be passed down to the rendering engine, but this is already happening in gz-sim and gz-gui …
=> Ogre2RenderEngine: on Windows if useCurrentGLContext is specified, set the externalWindowHandle ogre-next option

ogre/src/OgreDistortionPass.cc
I've noticed the code is prone to underflow because the distorted pixel values can be negative. Practically, the underflow was not a problem because the 4e9 values coming from the underflow never matched the condition to be lower than texture width. But it is an underflow and it deserves to be fixed.
=> Fixed integer underflow in OgreDistortionPass

package.xml
Fix #1004 
The build dependency is broken declaring gz-cmake instead of gz-cmake3. This is probably making colcon to ignore the gz-cmake3 install directory thus there is not gz-cmake3 config file.
=> Fix gz-cmake declaration on package.xml (fix windows CI)

ogre2/src/CMakeLists.txt, ogre2/src/Ogre2RenderEngine.cc
Fixes wrong handling of `OGRE2_RESOURCE_PATH` on Windows. 
It was assume that the `OGRE2_RESOURCE_PATH` was a `:`-delimiter list of paths. However, on Windows `:` is the separator between the drive letter and the path, so `;` should be used instead. 
Everything was working fine as `C:\this\is\a\path` and `\this\is\a\path` are both valid paths if the active drive is `C:\`, but as soon as the current active directory was for example on `D:`, `OGRE2_RESOURCE_PATH` was not read correctly, see https://github.com/conda-forge/gz-sim-feedstock/issues/57 .
=> Parse correctly OGRE2_RESOURCE_PATH on Windows

ogre2/src/media/materials/programs/GLSL/point_vs.glsl
Fixes: #970 
The change is already in gz-rendering7.
=> Fix crash when visualizing Lidars with points

include/gz/rendering/Marker.hh, include/gz/rendering/ParticleEmitter.hh, ogre/src/OgreMarker.cc, ogre2/src/Ogre2Marker.cc, ogre2/src/Ogre2ParticleEmitter.cc
This helps add the missing cone geometry for primitive/basic parametric shapes:
And is also valuable for visualizations of emitters/source that typically have conic-based spread as seen in this acoustic attack on an IMU by showing the affected area:
Associated PRs:
- https://github.com/gazebosim/gz-gui/pull/621
- https://github.com/gazebosim/gz-math/pull/594
- https://github.com/gazebosim/gz-msgs/pull/442
- https://github.com/gazebosim/gz-physics/pull/639
- https://github.com/gazebosim/gz-rendering/pull/1003
- https://github.com/gazebosim/gz-sim/pull/2410
- https://github.com/gazebosim/sdformat/pull/1418
=> Adding cone primitives.

src/ShaderParam.cc
Fixes deleter passed to the std::shared_ptr<void>: the c++ standard says that
the the  wrapped tye should be implicitely convertible to the type accepted by
the provided deleter. This is not the case for void* to float*.
=> Fixes deleter passed to the std::shared_ptr<void>

include/gz/rendering/Marker.hh, include/gz/rendering/ParticleEmitter.hh, ogre/src/OgreMarker.cc, ogre2/src/Ogre2Marker.cc
This helps add the missing cone geometry for primitive/basic parametric shapes:
And is also valuable for visualizations of emitters/source that typically have conic-based spread as seen in this acoustic attack on an IMU by showing the affected area:
Associated PRs:
- https://github.com/gazebosim/gz-gui/pull/620
- https://github.com/gazebosim/gz-math/pull/593
- https://github.com/gazebosim/gz-msgs/pull/441
- https://github.com/gazebosim/gz-physics/pull/638
- https://github.com/gazebosim/gz-rendering/pull/1001
- https://github.com/gazebosim/gz-sim/pull/2404
- https://github.com/gazebosim/sdformat/pull/1415
=> Add Cone as a primitive parametric shape.

ogre2/src/Ogre2GpuRays.cc
Minor resource optimization in lidars. Cameras can use quite a bite of memory. Originally lidars may use up to 6 cubemap cameras (depending on FOV) for sampling depth data. This PR reduces it to just one single cube camera that just changes its orientation to face the 6 different faces of the cubemap for sampling depth data. This is similar to how lidars in the ogre 1.x implementation sample data.
=> Use single cubemap camera in lidar

ogre2/src/Ogre2GpuRays.cc, test/integration/gpu_rays.cc
There is a calculation error for 1st pass texture size when the lidar FOV is lower than 90 degrees. It ended up using a texture resolution larger than it needed (and almost always got clamped to max size of 1024). This PR fixes the calculation. Now with a single point lidar, it should get clamped to the min texture size of 128 instead of 1024. 
=> Fix lidar 1st pass texture resolution calculation for FOV < 90 degrees

ogre2/src/CMakeLists.txt
The ogre2 plugin fails to load in gz-sim when gz-rendering is built in Debug mode. The following error message is emitted:
```
Error while loading the library [....lib/gz-rendering-8/engine-plugins/libgz-rendering-ogre2.so]: ....lib/gz-rendering-8/engine-plugins/libgz-rendering-ogre2.so: undefined symbol: _ZThn1008_N4Ogre7HlmsPbs19_changeRenderSystemEPNS_12RenderSystemE
```
This is because we set `DEBUG=1` and `_DEBUG=1` on the ogre2 target which seem to change the ABI of the generated library. These defines should really be set if Ogre2 itself is built in debug mode, so this PR simply comments out the CMake command that adds those defines.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining …
=> Fix debug builds of gz-rendering-ogre2 plugin

ogre/src/OgreWideAngleCamera.cc, ogre2/src/Ogre2WideAngleCamera.cc
Fixes #988
Limit ogre's FOV to 180 in the 2nd pass otherwise ogre crashes when building the frustum. This should be fine to do in the second pass since it is mainly for stitching images together and a correct camera FOV is likely not necessary.
=> Fix crash when wide angle camera FOV is > 180

include/gz/rendering/GraphicsAPI.hh
I was attempting to build Fortress on Jammy, and rand into:
```
GraphicsAPI.hh:31:10: warning: elaborated-type-specifier for a scoped enum must not use the ‘class’ keyword
```
followed by:
```
GraphicsAPI.hh:31:55: error: found ‘:’ in nested-name-specifier, expected ‘::’
31 |     enum class IGNITION_RENDERING_VISIBLE GraphicsAPI : uint16_t
```
The fix was to include the header file where uint16_t is defined.
I'm using gcc 13.2.0.
=> Fix build fortress + jammy

ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2GpuRays.cc
In `Ogre2GpuRays` and `Ogre2DepthCamera`, the raw data from ogre2 is copied into an local intermediate data buffer first before being copied again to separate outgoing data buffer(s) which are to be consumed by gz-sensors. This is not really necessary because gz-sensors also does its own copy when new data are available. This PR removes the local intermediate data buffer in `Ogre2GpuRays` and `Ogre2DepthCamera` classes and just copy the ogre2 raw data directly to the outgoing buffer
Tested by running relevant integration tests:
* gz-rendering: `INTEGRATION_gpu_rays`, `INTEGRATION_depth_camera` tests
* e.g. `GZ_ENGINE_TO_TEST=ogre2 ./build/gz-rendering8/bin/INTEGRATION_depth_camera`
* gz-sensors: `INTEGRATION_gpu_lidar_sensor`, `INTEGRATION_rgbd_camera`,  `INTEGRATION_depth_camera`
**Note …
=> Optimization: remove extra copy of data buffer in Ogre2GpuRays and Ogre2DepthCamera

ogre2/include/gz/rendering/ogre2/Ogre2GzOgreRenderingMode.hh, ogre2/include/gz/rendering/ogre2/Ogre2RenderEngine.hh, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2MaterialSwitcher.cc, ogre2/src/Ogre2RenderEngine.cc, ogre2/src/Ogre2RenderTarget.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.cc, ogre2/src/Ogre2ThermalCamera.cc, src/RenderEngineManager.cc, src/base/BaseScene.cc
=> Remove deprecated functions and enums

ogre2/include/gz/rendering/ogre2/Ogre2BoundingBoxCamera.hh, ogre2/include/gz/rendering/ogre2/Ogre2SegmentationCamera.hh, ogre2/include/gz/rendering/ogre2/Ogre2ThermalCamera.hh, ogre2/src/Ogre2BoundingBoxCamera.cc, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2SegmentationCamera.cc, ogre2/src/Ogre2ThermalCamera.cc
Addresses todos in relevant ogre2 camera classes. The new`SetProjectionMatrix` and `ProjectionMatrix` functions overrides those in the BaseCamera class. The workaround in `PreRender` function is removed - that was done to avoid breaking ABI
=> Override SetProjectionMatrix and ProjectionMatrix functions in derived ogre2 camera classes.

Migration.md, ogre2/include/gz/rendering/ogre2/Ogre2SelectionBuffer.hh, ogre2/src/Ogre2Camera.cc, ogre2/src/Ogre2RayQuery.cc, ogre2/src/Ogre2SelectionBuffer.cc
Addresses one of the todo items. 
Ray query related functions in ogre2 now return `Ogre::MovableObject` instead of `Ogre::Item` (`Ogre::Item` is derived from `Ogre::MovableObject`). This is so that we can include heightmap ogre objects (which are `Ogre::MovableObject` typed objects) in the ray query results.
2 API changes are documented in the Migration guide. One of them (`OnSelectionClick()`) is a change to the return type so it can not be deprecated, i.e. API breaking change. 
=> Update ogre2 ray query related functions to return Ogre::MovableObject instead of Ogre::Item

src/ArrowVisual_TEST.cc, src/AxisVisual_TEST.cc, src/Camera_TEST.cc, src/Grid_TEST.cc, src/Light_TEST.cc, src/Marker_TEST.cc, src/Material_TEST.cc, src/Mesh_TEST.cc, src/MoveToHelper_TEST.cc, src/Node_TEST.cc, src/OrbitViewController_TEST.cc, src/RayQuery_TEST.cc, src/RenderTarget_TEST.cc, src/RenderingIface_TEST.cc, src/Scene_TEST.cc, src/ThermalCamera_TEST.cc, src/TransformController_TEST.cc, src/Visual_TEST.cc, test/integration/CMakeLists.txt
Disable tests from #847 
This PR disables all tests that have segfaults in MacOS
=> Disable Unit test that have segfaults on Mac (rendering3)

ogre/src/OgreDistortionPass.cc
Forward port #994 and ~~#1017~~ from `ign-rendering6` to `gz-rendering7`
There are many conflicts between `ign-rendering6` and `gz-rendering7` due to ogre-next version upgrade and ign -> gz renaming. I manually cherry-picked ~~a couple of~~ one commits in this forward port. 
I did not forward port these changes
* rendering sensor perf optimizations - many conflicts due to ogre-next upgrade. Maybe easier to backport the changes form `gz-rendering8`
* [skipping macOS tests](https://github.com/gazebosim/gz-rendering/pull/1025) - CI is already green in [gz_rendering-ci-gz-rendering7-homebrew-amd64](https://build.osrfoundation.org/job/gz_rendering-ci-gz-rendering7-homebrew-amd64/)
Branch comparison: https://github.com/gazebosim/gz-rendering/compare/gz-rendering7...ign-rendering6
**Note to …
=> Merge 6 -> 7 (Partial merge forward)

src/Camera_TEST.cc, src/Capsule_TEST.cc, src/Heightmap_TEST.cc, src/JointVisual_TEST.cc, src/LidarVisual_TEST.cc, src/LightVisual_TEST.cc, src/Mesh_TEST.cc, src/OrthoViewController_TEST.cc, src/RenderTarget_TEST.cc, src/Scene_TEST.cc, src/Text_TEST.cc, src/Visual_TEST.cc, src/WireBox_TEST.cc, test/integration/CMakeLists.txt
Follow up from https://github.com/gazebosim/gz-rendering/pull/1023
Disable tests from https://github.com/gazebosim/gz-rendering/issues/847
=> Disable tests that have segfaults on Mac (rendering6)

ogre/src/OgreDepthCamera.cc, ogre/src/OgreMaterial.cc, ogre/src/OgreRTShaderSystem.cc, ogre/src/OgreRenderEngine.cc, optix/src/OptixRenderEngine.cc
Related PR: #1020
Remove use of IGN env vars in ogre 1.x
=> Remove more deprecated env vars

CMakeLists.txt
Hide optix and cuda related cmake warnings. Given that we're not actively maintaining the optix plugin, these warnings are distracting and may be misleading to users so hide them. In the future, let's consider archiving / removing the optix plugin.
Hides these warnings if cuda and optix are not available on your system:
```
CUDA_TOOLKIT_ROOT_DIR not found or specified
CMake Warning at /home/iche/code/gz_i_ws/install/share/cmake/gz-cmake4/cmake4/GzConfigureBuild.cmake:59 (message):
CONFIGURATION WARNINGS:
-- Missing dependency [OptiX]
Call Stack (most recent call first):
CMakeLists.txt:219 (gz_configure_build)
```
=> Hide optix related cmake warnings

Migration.md, include/gz/rendering/Camera.hh, include/gz/rendering/GpuRays.hh, include/gz/rendering/Object.hh, include/gz/rendering/ParticleEmitter.hh, include/gz/rendering/RenderPass.hh, include/gz/rendering/RenderTarget.hh, include/gz/rendering/Visual.hh, include/gz/rendering/base/BaseParticleEmitter.hh, include/gz/rendering/base/BaseRenderPass.hh, include/gz/rendering/base/BaseRenderTarget.hh, ogre/include/gz/rendering/ogre/OgreRenderTarget.hh, ogre/src/OgreRenderTarget.cc, ogre2/include/gz/rendering/ogre2/Ogre2GaussianNoisePass.hh, ogre2/include/gz/rendering/ogre2/Ogre2ParticleEmitter.hh, ogre2/src/Ogre2DepthCamera.cc, ogre2/src/Ogre2GaussianNoisePass.cc, ogre2/src/Ogre2ParticleEmitter.cc
These warnings are disabled in https://github.com/gazebosim/gz-rendering/pull/995 for harmonic on noble because fixes would involve ABI breaking changes. These warnings are useful and may help to uncover non-trivial errors. This PR removes most of the changes in https://github.com/gazebosim/gz-rendering/pull/995 and fixes the warnings.
=> Fix overloaded virtual warnings on noble

include/gz/rendering/Light.hh, include/gz/rendering/Scene.hh, include/gz/rendering/base/BaseScene.hh, ogre2/include/gz/rendering/ogre2/Ogre2Scene.hh, ogre2/src/Ogre2Scene.cc, src/base/BaseScene.cc, test/common_test/Scene_TEST.cc
Shadows appear jagged in some scenes. It would be nice for them to look smoother and sharper. Investigated increasing shadow texture size - it seems that as long as there isn't too many lights, it does not have a significant impact on VRAM. 
Thus, added ability to set shadow texture size (currently, only for directional lights) within the `MinimalScene` plugin, and for Ogre2. The default shadow texture size is 2K, but setting it to a higher value (4K, 8K, etc.) allows for sharper shadows.
Currently supporting 1K, 2K, 4K, 8K, and 16K. So in SDF file, the respective values 1024, 2048, 4096, 8192, and 16384. In the future, can look to enable setting shadow texture size for other light types (spot, point lights). 
Also, if using OpenGL, ensured that max shadow texture size can use …
=> Expose shadow texture size for directional lighting in SDF

ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
gz-sensors caught a crash in in its segmentation camera integration test on [github actions](https://github.com/gazebosim/gz-sensors/actions/runs/10461972989/job/28972696100). The error msgs reveal that it related to the new color clamping behavior in `gz::math::Color`:
```
2024-08-19T23:31:54.9495719Z Color values were clamped
2024-08-19T23:31:54.9495817Z Color values were clamped
2024-08-19T23:31:54.9495909Z Color values were clamped
```
The new Color behavior expects the range to be within [0, 1] but we are passing it values of [0, 255].
More info on the crash:  the crash was due to infinite recursion. The function tried to compute (recursively) unique color ids but each new generated color gets clamped to the same value `[1, 1, 1]`.
To test:
Run the gz-sensors segmentation camera …
=> Fix segmentation camera color id computation with new math::Color clamping behavior (ogre2)

CMakeLists.txt
This is no longer necessary now that we require a newer version of CMake, see https://github.com/gazebosim/gz-sensors/pull/457#discussion_r1720402930
=> Remove setting OpenGL_GL_PREFERENCE in cmake

.github/workflows/windows.yaml, ogre2/src/Ogre2Scene.cc
Build failure was reported in https://github.com/gazebosim/gazebo_test_cases/issues/1701#issuecomment-2321951252. It looks like #1034 introduced the regression and since we don't have Ogre2 being tested on CI, we didn't catch it.
The first commit just adds GitHub action for windows as a temporary solution until we fix Jenkins.
Here's the failed Action from the first commit: https://github.com/gazebosim/gz-rendering/actions/runs/10642231243/job/29504381117?pr=1049 
=> Add Github Action for Windows and fix build

ogre2/src/Ogre2Material.cc
To be used by the Ionic demo world.
Currently lightmap is applied through the emissive map slot. This means you can't use emissive map together with lightmap (only one of them can be applied). This was done to workaround an unwanted red hightlight issue found in gz-rendering6 + ogre2.2. This issue seems to be fixed now (as of gz-rendering9 + ogre 2.3). So I restored back to the original way of applying lightmaps through the detail map slot and I don't see the red highlights. Here's a screenshot of the lightmap sdf world with this change:
=> Fix using lightmap and emissive map together

tutorials/02_install.md
Update install documentation
Closes #<NUMBER>
Port <FROM_BRANCH> to <TO_BRANCH>
Branch comparison: https://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>
Preparation for <X.Y.Z> release.
Comparison to <x.y.z>: …
=> fix install tutorial

examples/heightmap/CMakeLists.txt, examples/heightmap/Main.cc, tutorials/21_heightmap.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1482
This PR adds support for building the heightmap example on Windows.
I was able to compile the example and run it using `.\Release\heightmap.exe ogre`.
=> examples/heightmap: Fixed Windows build

tutorials/02_install.md
Related: https://github.com/gazebosim/gazebo_test_cases/issues/1444
Updated instruction for installing homebrew.
The command no longer works as the  URL is incorrect, so updated to just point to homebrew website for installation instructions.
=> Update homebrew install instruction

examples/depth_camera/CMakeLists.txt, examples/depth_camera/Main.cc, tutorials/23_depth_camera_tutorial.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1494
This PR allows building and running depth_camera example on Windows.
I'm not sure about the thing with `RESOURCE_PATH`, but I had to do it on Windows.
=> examples/depth_camera: Fixed windows usage

test/integration/waves.cc
Fixes #https://github.com/osrf/buildfarm-tools/issues/92#issuecomment-2353462714
Reference builds:
* https://build.osrfoundation.org/job/gz_rendering-8-win/85/
* https://build.osrfoundation.org/job/gz_rendering-7-win/77/
Warning:
* Present in [waves.cc:171](https://github.com/gazebosim/gz-rendering/blob/ad30d4e0c2e3fcf845a6805bc64f15ede4383346/test/integration/waves.cc#L170)
Log output:
```
waves.cc
C:\J\workspace\gz_rendering-7-win\ws\gz-rendering\test\integration\waves.cc(170,29): warning C4305: 'initializing': truncation from 'double' to 'float' [C:\J\workspace\gz_rendering-7-win\ws\build\gz-rendering7\test\integration\INTEGRATION_waves.vcxproj]
C:\J\workspace\gz_rendering-7-win\ws\gz-rendering\test\integration\waves.cc(174,28): warning C4305: 'initializing': truncation from 'double' …
```
=> Fix waves 'double' to 'float' truncation warning

tutorials/21_render_order.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1483
Running `simple_demo` as per tutorial on macOS with ogre1 as default render engine doesn't work. Added small comment on running with ogre2 for macOS.
=> Add macOS instructions for render_order tutorial

ogre2/src/Ogre2Material.cc
This reverts commit 6ec0c520f28a61b9505ada49d21adcf92e31b291.
Reverts #1047 because it changed the appearance of visuals with lightmaps.
~~Marked as draft as we are waiting to see if we can find another workaround to make emissive maps work together with lightmaps.~~
=> Revert "Fix using lightmap and emissive map together (#1047)"

CMakeLists.txt
When `GZ_ENABLE_RELOCATABLE_INSTALL` is `ON`, the project that uses `gz_add_get_install_prefix_impl` needs to call `gz_find_package(DL REQUIRED)` . For some reason, this was not added in https://github.com/gazebosim/gz-rendering/pull/804/files, but everything was working fine for some reason. However, I tried to ocmpile gz-rendering9 on conda-forge, and know the build is failing with:
~~~
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at /home/conda/feedstock_root/build_artifacts/gz-rendering9_1727635675214/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/cmake/gz-cmake4/cmake4/GzRelocatableBinaries.cmake:97 (message): …
=> Fix configuration with GZ_ENABLE_RELOCATABLE_INSTALL=ON

src/MoveToHelper.cc
Fixes https://github.com/gazebosim/gz-gui/issues/615
Fixes crash due to zero quaternion.
=> Check for zero quaternion value in MoveToHelper

ogre2/src/Ogre2Material.cc
=> Backport normal / texture map mip map fix

test/gz_rendering_test.cmake
If `GZ_ENABLE_RELOCATABLE_INSTALL` is `ON`, for all tests the environment variable `GZ_RENDERING_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}` need to be defined, to make sure that even if the shared library in the build directory is used instead of the install prefix, the correctly installed engine plugins are loaded. As part of https://github.com/gazebosim/gz-rendering/pull/804 I modified some tests to set `GZ_RENDERING_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}`, but I forgot to do this modification in `gz_configure_rendering_test`, that is actually how most tests in gz-rendering are added.
=> Fix running rendering tests if GZ_ENABLE_RELOCATABLE_INSTALL is ON

src/RenderEngineManager.cc
I am trying to run the Windows test suite on windows with conda-forge dependencies, and the only failures are:
~~~
The following tests FAILED:
25 - INTEGRATION_gpu_rays_ogre2_gl3plus (Failed)
35 - INTEGRATION_mesh_ogre_gl3plus (Failed)
65 - INTEGRATION_thermal_camera_ogre2_gl3plus (Failed)
- RenderingIface_TEST_ogre2_gl3plus (Failed)
~~~
The `RenderingIface_TEST_ogre2_gl3plus` is fixed by removing this old workaround. I opened this to understand if this breaks something.
=> Unload rendering plugin also on Windows

.github/workflows/windows.yaml, README.md
Fix windows github actions workflow. It started failing recently on `gz-rendering9 `and `main`, with the error:
```
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
{build,extension-points,extensions,graph,info,list,metadata,test,test-result,version-check}
...
colcon: error: unrecognized arguments: -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
```
Not sure what has changed but the fixed by putting double quotes around each cmake arg passed to `colcon build`
=> Fix Windows github action workflow

include/gz/rendering/base/BaseCamera.hh, ogre/src/OgreCamera.cc, ogre2/src/Ogre2Camera.cc, test/common_test/Camera_TEST.cc
Fixes https://github.com/gazebosim/gz-sim/issues/2615
Added checks for valid camera clip distances to prevent ogre from throwing an exception
=> Check valid camera near far clip distances

ogre/src/OgreWireBox.cc
Fixes https://github.com/gazebosim/gz-rendering/issues/1000
Prevent creating a wirebox with empty AABB in ogre.
A `gz::math::AxisAlignedBox` initializes the bounds to `MAX_D` and `LOW_D` which results in an `inf` AABB in ogre as it uses floats for AABB instead of doubles. This then leads to a crash when ogre tries to render the scene.
See #1000 for a description on how to reproduce the crash with gz-sim. You can launch gazebo with ogre render engine by running:
```
gz sim -v 4 shapes.sdf  --render-engine ogre
```
Expand the `sun` item in the `Entity Tree` and click on `sunVisual` to see the crash.
The changes in this PR only prevent the crash - it does not actually display the wirebox for the light visual, which is the same as the original behavior.
**Note to maintainers**: Remember to …
=> Do not create wirebox with empty AABB (ogre)

test/test_config.h.in
Instead of hardcoding them by architecture, create the right list of engines from the support found by CMake.
This change will enable ogre1 tests for Windows currently disabled.
=> Fix test_config.h to include real engines found (gz-rendering6)

ogre2/src/Ogre2RenderEngine.cc
Unregister window class on Windows to allow repeated loading / unloading of ogre 2.2 (used by ign-rendering6) in the same process, i.e. our unit and integration tests. A similar patch (https://github.com/OGRECave/ogre-next/pull/327) was already submitted by @mjcarroll  to ogre-next for version 2.3 (used by gz-rendering7 onwards). Adding the change here for ign-rendering6 so we can run ogre2 tests on our new Windows conda CI.
Note that the `gz_rendering-pr-win` jenkins job in the checks below still uses the old vcpkg based builds so we'll still get many test failures. 
Here are the new conda test builds:
* before: 59 test failures - https://build.osrfoundation.org/view/conda/job/_test_gz_rendering-pr-cwin/68/
* after: 8 test failures - …
=> Port Windows fix for unregistering OgreGLWindows class in ogre 2.2

ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2ThermalCamera.cc
Using exception for a flow control is not a very good approach in a different points of view, like from a code structure, from a performance perspective (https://godbolt.org/z/s883vGr9f)
I'd propose to use std::holds_alternative as a more simple way to improve this part of code.
Also improved some typos
=> Better approach to use std::variant

ogre/src/OgreWideAngleCamera.cc, ogre2/src/Ogre2WideAngleCamera.cc, test/integration/wide_angle_camera.cc
Closes https://github.com/gazebosim/gz-sensors/issues/479
Related PR: https://github.com/gazebosim/gz-sensors/pull/494
Added support for wide angle cameras to read image data back in L8 and L16 image formats for ogre and ogre2
Updated `INTEGRATION_wide_angle_camera` test.
From your colcon's gz-rendering's build folder, you can run tests like this:
```
GZ_ENGINE_TO_TEST=ogre2  ./bin/INTEGRATION_wide_angle_camera
GZ_ENGINE_TO_TEST=ogre  ./bin/INTEGRATION_wide_angle_camera
```
=> Extend wide angle cameras to support L8 and L16 image formats

examples/frustum_visual/CMakeLists.txt, examples/frustum_visual/Main.cc, include/gz/rendering/FrustumVisual.hh, include/gz/rendering/Scene.hh, include/gz/rendering/base/BaseScene.hh, ogre/include/gz/rendering/ogre/OgreScene.hh, ogre/src/OgreScene.cc, ogre2/include/gz/rendering/ogre2/Ogre2Scene.hh, ogre2/src/Ogre2FrustumVisual.cc, ogre2/src/Ogre2Scene.cc, src/base/BaseScene.cc, test/common_test/CMakeLists.txt, test/common_test/FrustumVisual_TEST.cc
Implement ABI compatibility changes for the Frustum Visual feature (#1095) so that it can be backported to gz-rendering9. The approach is similar to #845 which uses the `SceneExt` class for creating the visual frustum to prevent overriding virtual functions (which breaks ABI). The official functions for creating `FrustumVisual` classes are commented out (instead of being removed) to keep the diff with `main` minimal.
I also added a unit test for the FrustumVisual class.
=> Frustum Visual ABI compatibility changes

examples/frustum_visual/CMakeLists.txt, examples/frustum_visual/GlutWindow.cc, examples/frustum_visual/GlutWindow.hh, examples/frustum_visual/Main.cc, include/gz/rendering/FrustumVisual.hh, include/gz/rendering/RenderTypes.hh, include/gz/rendering/Scene.hh, include/gz/rendering/base/BaseFrustumVisual.hh, include/gz/rendering/base/BaseScene.hh, ogre/include/gz/rendering/ogre/OgreFrustumVisual.hh, ogre/include/gz/rendering/ogre/OgreRenderTypes.hh, ogre/include/gz/rendering/ogre/OgreScene.hh, ogre/src/OgreFrustumVisual.cc, ogre/src/OgreScene.cc, ogre2/include/gz/rendering/ogre2/Ogre2FrustumVisual.hh, ogre2/include/gz/rendering/ogre2/Ogre2RenderTypes.hh, ogre2/include/gz/rendering/ogre2/Ogre2Scene.hh, ogre2/src/Ogre2FrustumVisual.cc, ogre2/src/Ogre2Scene.cc, src/FrustumVisual.cc, src/base/BaseScene.cc, test/common_test/CMakeLists.txt, test/common_test/FrustumVisual_TEST.cc
Related PR: #1102
Backport of https://github.com/gazebosim/gz-rendering/pull/1095.
~~**Marked as draft**: Please review #1102 first to get the ABI compatibility changes in first.~~
=> Backport Frustum Visual (#1095)

ogre2/include/gz/rendering/ogre2/Ogre2DynamicRenderable.hh, ogre2/include/gz/rendering/ogre2/Ogre2GaussianNoisePass.hh, ogre2/include/gz/rendering/ogre2/Ogre2GlobalIlluminationCiVct.hh, ogre2/include/gz/rendering/ogre2/Ogre2GlobalIlluminationVct.hh, ogre2/include/gz/rendering/ogre2/Ogre2LensFlarePass.hh, ogre2/include/gz/rendering/ogre2/Ogre2Object.hh, ogre2/include/gz/rendering/ogre2/Ogre2RenderPass.hh, ogre2/include/gz/rendering/ogre2/Ogre2RenderTargetMaterial.hh
Fixes https://github.com/gazebosim/gz-rendering/issues/1106
Suppress [C4251](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4251?view=msvc-170#example) warnings on windows.  
Example warning msgs:
```
'gz::rendering::v8::Ogre2DynamicRenderable::dataPtr': class 'std::unique_ptr>' needs to have dll-interface to be used by clients of class 'gz::rendering::v8::Ogre2DynamicRenderable'
```
The warnings are emitted when there are STL typed objects declared in header classes. The reason for this warning is explained [here](https://stackoverflow.com/a/4563701), specifically:
> ...emitted when you use a non-dllexported class X in a dllexported class Y 
This is no longer an issue in [gz-rendering9 windows …
=> Suppress dll-interface warnings (C4251) on windows 

ogre2/include/gz/rendering/ogre2/Ogre2MeshFactory.hh, ogre2/include/gz/rendering/ogre2/Ogre2Scene.hh, ogre2/src/Ogre2Material.cc, ogre2/src/Ogre2MeshFactory.cc
The material cache in `Ogre2MeshFactory` was introduced in #324 to clear material objects when a mesh is removed. Looking at the current state, this call should no longer be needed as we now have logic in `Ogre2Material::Destroy` function to destroy ogre internal material / texture objects (and also unregistering gz-rendering material objects) when they [are not in use](https://github.com/gazebosim/gz-rendering/blob/a48f757d9448e05bdc3e6e73c61ddf4869febac6/ogre2/src/Ogre2Material.cc#L254-L268). So this PR removes the material cache and the the call to `ClearMaterialCache` function.
Note that we ran into an issue with the `ClearMaterialsCache` function. It clears materials by the name of the texture it contains. However, it's possible for multiple materials to use the same texture, and the …
=> Remove ClearMaterialsCache call when a material is destroyed in ogre2

ogre/src/OgreRenderEngine.cc
Removes an unused variable in OgreRenderingEngine.cc
=> Remove unused variable

ogre/src/OgreMeshFactory.cc, ogre2/src/Ogre2MeshFactory.cc
Check that a submesh has valid indices before passing them to the render engines.
This does pretty much the same check as the new function added in `common::SubMesh` in https://github.com/gazebosim/gz-common/pull/667. We can switch to use that function when a new gz-common release is made.
=> Add sanity check for valid submesh indices

include/gz/rendering/NativeWindow.hh
Fixes https://github.com/gazebosim/gz-rendering/issues/1127
=> Added missing includes

ogre/src/OgreThermalCamera.cc, ogre2/src/Ogre2BoundingBoxMaterialSwitcher.cc, ogre2/src/Ogre2GpuRays.cc, ogre2/src/Ogre2SegmentationMaterialSwitcher.cc, ogre2/src/Ogre2ThermalCamera.cc
Fixes https://github.com/gazebosim/gz-rendering/issues/516
Use of std::get for gz::rendering::Variant throws exceptions whenever it is interpreted as the wrong type. Non-critical exceptions when working Gazebo can cause lead to cumbersome debugging. So the code has been changed to use std::get_if for a softer error handling when encountering wrong Variant type.
Two things have been changed
- Code using `try` `catch` with `std::get` changed to `std::get_if` in `ogre/src/OgreThermalCamera.cc`, `ogre2/src/Ogre2BoundingBoxMaterialSwitcher.cc` and `ogre2/src/Ogre2SegmentationMaterialSwitcher.cc`
- `std::holds_alternative` nested with `std::get` changed to use only `std::get_if` for simpler value access in `ogre2/src/Ogre2GpuRays.cc` and `ogre2/src/Ogre2ThermalCamera.cc`
The following tests …
=> Change to std::get_if for gz::rendering::Variant for throwless behaviour

ogre/src/media/materials/programs/thermal_camera_fs.glsl, ogre2/src/media/materials/programs/GLSL/thermal_camera_fs.glsl, ogre2/src/media/materials/programs/Metal/thermal_camera_fs.metal, test/integration/thermal_camera.cc
The minimum and maximum temperature of the thermal camera were not applied properly. clamp was called in the shader without using the result. This also adds simple test cases that allow easily reproducing the bug before this change. 
=> Fix clamp of temperature in thermal camera output

ogre/src/OgreRenderEngine.cc, ogre2/src/Ogre2RenderEngine.cc
Hides Ogre and Ogre2 external window on MacOS and Windows.
Unlike Linux, Ogre backend *must* use external window handles. When Gazebo client starts, it opens two windows: one is the main client window with GUI, and the other is just an empty window like this:
This PR sets `hidden=true` param for Ogre and Ogre2 which allows to use external window handle but hides window itself.
=> Hide Ogre and Ogre2 external window on MacOS and Windows

ogre/src/CMakeLists.txt, ogre2/src/CMakeLists.txt
There are no longer versioned libraries so we can removed these symlinks. Same thing was done in https://github.com/gazebosim/gz-physics/pull/747
=> Remove symlinks of versioned to unversioned engine libraries

ogre/src/OgreRenderEngine.cc, ogre2/src/Ogre2RenderEngine.cc, optix/src/OptixRenderEngine.cc, src/RenderEngineManager.cc, test/BUILD.bazel, test/integration/load_static_render_engine_plugin.cc
Extends `RenderEngineManager` to load a render engine plugin from the static plugin registry.
Also registered the default render engine plugins based on lookup in the plugin registry at runtime, in case one or more of the default render engines were statically linked in. This is required so that `unloadEngine()` can correctly unload the instantiated engine using the standard name, e.g. "ogre2". (Note: `unloadEngine` is called from the [`gz::sim::Sensors` system](https://github.com/gazebosim/gz-sim/blob/a6b8f05ee20f75b4c65d31bb4f753bdea710c480/src/rendering/RenderUtil.cc#L2682)). To make the plugin filename in the static plugin registry more obvious, I also added aliases for the existing render engine plugins with fully qualified names.
Added a test in the bazel build:
```
$ bazel test …
```
=> Enable loading a render engine plugin from the static plugin registry

MODULE.bazel, bazel/BUILD.bazel, bazel/gz_rendering_engine_libraries.bzl, ogre2/BUILD.bazel
Add bazel build for ogre2 render engine. Two targets are added, one for static linking and another for runtime loading from .so. Both targets are generated by a new `gz_rendering_engine_libraries` rule (similar to [gz-sim system plugins](https://github.com/gazebosim/gz-sim/blob/gz-sim9/bazel/gz_sim_system_libraries.bzl)).
```
$ bazel build ogre2:all
```
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Add bazel build for ogre2 engine

.github/ci/packages.apt, tutorials/02_install.md, tutorials/10_actor_animation_tutorial.md, tutorials/12_mesh_viewer_tutorial.md, tutorials/13_custom_scene_viewer.md, tutorials/14_camera_tracking_tutorial.md, tutorials/15_custom_shaders_tutorial.md, tutorials/17_render_pass_tutorial.md, tutorials/18_simple_demo_tutorial.md, tutorials/19_text_geom_tutorial.md, tutorials/20_particles_tutorial.md, tutorials/21_heightmap.md, tutorials/22_environment_map.md, tutorials/24_boundingbox_camera_tutorial.md
Related: https://github.com/gazebosim/gazebo_test_cases/issues/2052
Add a note to mention that freeglut3-dev is for examples and removed freeimage from installation requirement as we no longer need it in gz-rendering
=> Add a note about glut dependency in installation tutorial

include/gz/rendering/base/BaseMesh.hh, test/common_test/Mesh_TEST.cc
Needed by https://github.com/gazebosim/gz-sim/pull/3085
When `SubMesh::SetMaterial` is called with `_unique = false` (i.e. don't clone the input material),  check if the input material is the same as the original one. If so, return early and don't destroy the original material.
```
GZ_ENGINE_TO_TEST=ogre2 ./build/gz-rendering/bin/UNIT_Mesh_TEST
```
Before the changes, the test will segfault. Now the test should pass without crashing.
Generated-by: Remove this if GenAI was not used.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Prevent material destruction if setting the same material to a submesh

CMakeLists.txt, Changelog.md
Preparation for 10.0.0~pre2 release.
Comparison to 10.0.0-pre1: https://github.com/gazebosim/gz-rendering/compare/gz-rendering10_10.0.0-pre1...prep_10.0.0pre2
=> Prepare for 10.0.0 pre2 release

test/integration/depth_camera.cc
Fixes https://github.com/gazebosim/gz-rendering/issues/1173
Just a light tol increase for arm based macs.
Generated-by: Remove this if GenAI was not used.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
=> Increase depth camera integration test error tol for ogre 1.x on arm based mac

test/integration/heightmap.cc
Fixes https://github.com/gazebosim/gz-rendering/issues/1174 and https://github.com/gazebosim/gz-rendering/issues/1159
I verified locally that the ogre2 engine was able to successfully generate images on mac when running the `INTEGRATION_heightmap` test. The test failed because when comparing the colors between an image generated by a regular camera and the color component of the point cloud data generated by a depth camera, one particular pixel has a higher error than the current allowed tolerance. Fixed by increasing this error tol from `9` -> `10`.
These are the images generated:
Regular RGB image:
Point cloud RGB data:
To run the heightmap test on mac:
```sh
GZ_ENGINE_TO_TEST=ogre2 GZ_ENGINE_BACKEND=metal ./build/gz-rendering/bin/INTEGRATION_heightmap
```
The error about unable to find …
=> Fix ogre2 heightmap test on metal
